-- Tailoring recipes — Source: Wowhead Classic XML (item pages) + wow-classic-items npm
-- WoW Classic Era (Interface 11508)

ProfTooltip_Tailoring = {

    [2570] = { name = "Linen Cloak", skill = 1, spec = nil,
        components = {
            { id = 2996,   qty =  1, name = "Bolt of Linen Cloth" },
            { id = 2320,   qty =  1, name = "Coarse Thread" },
        },
    },
    [2576] = { name = "White Linen Shirt", skill = 1, spec = nil,
        components = {
            { id = 2996,   qty =  1, name = "Bolt of Linen Cloth" },
            { id = 2320,   qty =  1, name = "Coarse Thread" },
            { id = 2324,   qty =  1, name = "Bleach" },
        },
    },
    [2996] = { name = "Bolt of Linen Cloth", skill = 1, spec = nil,
        components = {
            { id = 2589,   qty =  2, name = "Linen Cloth" },
        },
    },
    [4344] = { name = "Brown Linen Shirt", skill = 1, spec = nil,
        components = {
            { id = 2996,   qty =  1, name = "Bolt of Linen Cloth" },
            { id = 2320,   qty =  1, name = "Coarse Thread" },
        },
    },
    [10045] = { name = "Simple Linen Pants", skill = 1, spec = nil,
        components = {
            { id = 2996,   qty =  1, name = "Bolt of Linen Cloth" },
            { id = 2320,   qty =  1, name = "Coarse Thread" },
        },
    },
    [2568] = { name = "Brown Linen Vest", skill = 10, spec = nil,
        components = {
            { id = 2996,   qty =  1, name = "Bolt of Linen Cloth" },
            { id = 2320,   qty =  1, name = "Coarse Thread" },
        },
    },
    [7026] = { name = "Linen Belt", skill = 15, spec = nil,
        components = {
            { id = 2996,   qty =  1, name = "Bolt of Linen Cloth" },
            { id = 2320,   qty =  1, name = "Coarse Thread" },
        },
    },
    [10046] = { name = "Simple Linen Boots", skill = 20, spec = nil,
        components = {
            { id = 2996,   qty =  2, name = "Bolt of Linen Cloth" },
            { id = 2318,   qty =  1, name = "Light Leather" },
            { id = 2320,   qty =  1, name = "Coarse Thread" },
        },
    },
    [4343] = { name = "Brown Linen Pants", skill = 30, spec = nil,
        components = {
            { id = 2996,   qty =  2, name = "Bolt of Linen Cloth" },
            { id = 2320,   qty =  1, name = "Coarse Thread" },
        },
    },
    [6238] = { name = "Brown Linen Robe", skill = 30, spec = nil,
        components = {
            { id = 2996,   qty =  3, name = "Bolt of Linen Cloth" },
            { id = 2320,   qty =  1, name = "Coarse Thread" },
        },
    },
    [6241] = { name = "White Linen Robe", skill = 30, spec = nil,
        components = {
            { id = 2996,   qty =  3, name = "Bolt of Linen Cloth" },
            { id = 2320,   qty =  1, name = "Coarse Thread" },
            { id = 2324,   qty =  1, name = "Bleach" },
        },
    },
    [4307] = { name = "Heavy Linen Gloves", skill = 35, spec = nil,
        components = {
            { id = 2996,   qty =  2, name = "Bolt of Linen Cloth" },
            { id = 2320,   qty =  1, name = "Coarse Thread" },
        },
    },
    [2572] = { name = "Red Linen Robe", skill = 40, spec = nil,
        components = {
            { id = 2996,   qty =  3, name = "Bolt of Linen Cloth" },
            { id = 2320,   qty =  2, name = "Coarse Thread" },
            { id = 2604,   qty =  2, name = "Red Dye" },
        },
    },
    [2575] = { name = "Red Linen Shirt", skill = 40, spec = nil,
        components = {
            { id = 2996,   qty =  2, name = "Bolt of Linen Cloth" },
            { id = 2320,   qty =  1, name = "Coarse Thread" },
            { id = 2604,   qty =  1, name = "Red Dye" },
        },
    },
    [2577] = { name = "Blue Linen Shirt", skill = 40, spec = nil,
        components = {
            { id = 2996,   qty =  2, name = "Bolt of Linen Cloth" },
            { id = 2320,   qty =  1, name = "Coarse Thread" },
            { id = 6260,   qty =  1, name = "Blue Dye" },
        },
    },
    [6786] = { name = "Simple Dress", skill = 40, spec = nil,
        components = {
            { id = 2996,   qty =  2, name = "Bolt of Linen Cloth" },
            { id = 2320,   qty =  1, name = "Coarse Thread" },
            { id = 6260,   qty =  1, name = "Blue Dye" },
            { id = 2324,   qty =  1, name = "Bleach" },
        },
    },
    [4238] = { name = "Linen Bag", skill = 45, spec = nil,
        components = {
            { id = 2996,   qty =  3, name = "Bolt of Linen Cloth" },
            { id = 2320,   qty =  3, name = "Coarse Thread" },
        },
    },
    [6239] = { name = "Red Linen Vest", skill = 55, spec = nil,
        components = {
            { id = 2996,   qty =  3, name = "Bolt of Linen Cloth" },
            { id = 2320,   qty =  1, name = "Coarse Thread" },
            { id = 2604,   qty =  1, name = "Red Dye" },
        },
    },
    [6240] = { name = "Blue Linen Vest", skill = 55, spec = nil,
        components = {
            { id = 2996,   qty =  3, name = "Bolt of Linen Cloth" },
            { id = 2320,   qty =  1, name = "Coarse Thread" },
            { id = 6260,   qty =  1, name = "Blue Dye" },
        },
    },
    [2580] = { name = "Reinforced Linen Cape", skill = 60, spec = nil,
        components = {
            { id = 2996,   qty =  2, name = "Bolt of Linen Cloth" },
            { id = 2320,   qty =  3, name = "Coarse Thread" },
        },
    },
    [4308] = { name = "Green Linen Bracers", skill = 60, spec = nil,
        components = {
            { id = 2996,   qty =  3, name = "Bolt of Linen Cloth" },
            { id = 2320,   qty =  2, name = "Coarse Thread" },
            { id = 2605,   qty =  1, name = "Green Dye" },
        },
    },
    [2569] = { name = "Linen Boots", skill = 65, spec = nil,
        components = {
            { id = 2996,   qty =  3, name = "Bolt of Linen Cloth" },
            { id = 2320,   qty =  1, name = "Coarse Thread" },
            { id = 2318,   qty =  1, name = "Light Leather" },
        },
    },
    [2578] = { name = "Barbaric Linen Vest", skill = 70, spec = nil,
        components = {
            { id = 2996,   qty =  4, name = "Bolt of Linen Cloth" },
            { id = 2318,   qty =  1, name = "Light Leather" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
        },
    },
    [2579] = { name = "Green Linen Shirt", skill = 70, spec = nil,
        components = {
            { id = 2996,   qty =  3, name = "Bolt of Linen Cloth" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
            { id = 2605,   qty =  1, name = "Green Dye" },
        },
    },
    [4309] = { name = "Handstitched Linen Britches", skill = 70, spec = nil,
        components = {
            { id = 2996,   qty =  4, name = "Bolt of Linen Cloth" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
        },
    },
    [5762] = { name = "Red Linen Bag", skill = 70, spec = nil,
        components = {
            { id = 2996,   qty =  4, name = "Bolt of Linen Cloth" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
            { id = 2604,   qty =  1, name = "Red Dye" },
        },
    },
    [6242] = { name = "Blue Linen Robe", skill = 70, spec = nil,
        components = {
            { id = 2996,   qty =  4, name = "Bolt of Linen Cloth" },
            { id = 2320,   qty =  2, name = "Coarse Thread" },
            { id = 6260,   qty =  2, name = "Blue Dye" },
        },
    },
    [2584] = { name = "Woolen Cape", skill = 75, spec = nil,
        components = {
            { id = 2997,   qty =  1, name = "Bolt of Woolen Cloth" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
        },
    },
    [2997] = { name = "Bolt of Woolen Cloth", skill = 75, spec = nil,
        components = {
            { id = 2592,   qty =  3, name = "Wool Cloth" },
        },
    },
    [10047] = { name = "Simple Kilt", skill = 75, spec = nil,
        components = {
            { id = 2996,   qty =  4, name = "Bolt of Linen Cloth" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
        },
    },
    [4240] = { name = "Woolen Bag", skill = 80, spec = nil,
        components = {
            { id = 2997,   qty =  3, name = "Bolt of Woolen Cloth" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
        },
    },
    [4312] = { name = "Soft-soled Linen Boots", skill = 80, spec = nil,
        components = {
            { id = 2996,   qty =  5, name = "Bolt of Linen Cloth" },
            { id = 2318,   qty =  2, name = "Light Leather" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
        },
    },
    [2582] = { name = "Green Woolen Vest", skill = 85, spec = nil,
        components = {
            { id = 2997,   qty =  2, name = "Bolt of Woolen Cloth" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
            { id = 2605,   qty =  1, name = "Green Dye" },
        },
    },
    [4310] = { name = "Heavy Woolen Gloves", skill = 85, spec = nil,
        components = {
            { id = 2997,   qty =  3, name = "Bolt of Woolen Cloth" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
        },
    },
    [5542] = { name = "Pearl-clasped Cloak", skill = 90, spec = nil,
        components = {
            { id = 2997,   qty =  3, name = "Bolt of Woolen Cloth" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
            { id = 5498,   qty =  1, name = "Small Lustrous Pearl" },
        },
    },
    [2583] = { name = "Woolen Boots", skill = 95, spec = nil,
        components = {
            { id = 2997,   qty =  4, name = "Bolt of Woolen Cloth" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
            { id = 2318,   qty =  2, name = "Light Leather" },
        },
    },
    [4241] = { name = "Green Woolen Bag", skill = 95, spec = nil,
        components = {
            { id = 2997,   qty =  4, name = "Bolt of Woolen Cloth" },
            { id = 2605,   qty =  1, name = "Green Dye" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
        },
    },
    [4313] = { name = "Red Woolen Boots", skill = 95, spec = nil,
        components = {
            { id = 2997,   qty =  4, name = "Bolt of Woolen Cloth" },
            { id = 2318,   qty =  2, name = "Light Leather" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
            { id = 2604,   qty =  2, name = "Red Dye" },
        },
    },
    [2587] = { name = "Gray Woolen Shirt", skill = 100, spec = nil,
        components = {
            { id = 2997,   qty =  2, name = "Bolt of Woolen Cloth" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
            { id = 4340,   qty =  1, name = "Gray Dye" },
        },
    },
    [4311] = { name = "Heavy Woolen Cloak", skill = 100, spec = nil,
        components = {
            { id = 2997,   qty =  3, name = "Bolt of Woolen Cloth" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
            { id = 5498,   qty =  2, name = "Small Lustrous Pearl" },
        },
    },
    [6263] = { name = "Blue Overalls", skill = 100, spec = nil,
        components = {
            { id = 2997,   qty =  4, name = "Bolt of Woolen Cloth" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
            { id = 6260,   qty =  2, name = "Blue Dye" },
        },
    },
    [2585] = { name = "Gray Woolen Robe", skill = 105, spec = nil,
        components = {
            { id = 2997,   qty =  4, name = "Bolt of Woolen Cloth" },
            { id = 2321,   qty =  3, name = "Fine Thread" },
            { id = 4340,   qty =  1, name = "Gray Dye" },
        },
    },
    [4314] = { name = "Double-stitched Woolen Shoulders", skill = 110, spec = nil,
        components = {
            { id = 2997,   qty =  3, name = "Bolt of Woolen Cloth" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
        },
    },
    [4316] = { name = "Heavy Woolen Pants", skill = 110, spec = nil,
        components = {
            { id = 2997,   qty =  5, name = "Bolt of Woolen Cloth" },
            { id = 2321,   qty =  4, name = "Fine Thread" },
        },
    },
    [4330] = { name = "Stylish Red Shirt", skill = 110, spec = nil,
        components = {
            { id = 2997,   qty =  3, name = "Bolt of Woolen Cloth" },
            { id = 2604,   qty =  2, name = "Red Dye" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
        },
    },
    [6787] = { name = "White Woolen Dress", skill = 110, spec = nil,
        components = {
            { id = 2997,   qty =  3, name = "Bolt of Woolen Cloth" },
            { id = 2324,   qty =  4, name = "Bleach" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
        },
    },
    [5763] = { name = "Red Woolen Bag", skill = 115, spec = nil,
        components = {
            { id = 2997,   qty =  4, name = "Bolt of Woolen Cloth" },
            { id = 2604,   qty =  1, name = "Red Dye" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
        },
    },
    [6264] = { name = "Greater Adept's Robe", skill = 115, spec = nil,
        components = {
            { id = 2997,   qty =  5, name = "Bolt of Woolen Cloth" },
            { id = 2321,   qty =  3, name = "Fine Thread" },
            { id = 2604,   qty =  3, name = "Red Dye" },
        },
    },
    [4315] = { name = "Reinforced Woolen Shoulders", skill = 120, spec = nil,
        components = {
            { id = 2997,   qty =  6, name = "Bolt of Woolen Cloth" },
            { id = 2319,   qty =  2, name = "Medium Leather" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
        },
    },
    [6384] = { name = "Stylish Blue Shirt", skill = 120, spec = nil,
        components = {
            { id = 2997,   qty =  4, name = "Bolt of Woolen Cloth" },
            { id = 6260,   qty =  2, name = "Blue Dye" },
            { id = 4340,   qty =  1, name = "Gray Dye" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
        },
    },
    [6385] = { name = "Stylish Green Shirt", skill = 120, spec = nil,
        components = {
            { id = 2997,   qty =  4, name = "Bolt of Woolen Cloth" },
            { id = 2605,   qty =  2, name = "Green Dye" },
            { id = 4340,   qty =  1, name = "Gray Dye" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
        },
    },
    [10048] = { name = "Colorful Kilt", skill = 120, spec = nil,
        components = {
            { id = 2997,   qty =  5, name = "Bolt of Woolen Cloth" },
            { id = 2604,   qty =  3, name = "Red Dye" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
        },
    },
    [4305] = { name = "Bolt of Silk Cloth", skill = 125, spec = nil,
        components = {
            { id = 4306,   qty =  4, name = "Silk Cloth" },
        },
    },
    [4317] = { name = "Phoenix Pants", skill = 125, spec = nil,
        components = {
            { id = 2997,   qty =  6, name = "Bolt of Woolen Cloth" },
            { id = 5500,   qty =  1, name = "Iridescent Pearl" },
            { id = 2321,   qty =  3, name = "Fine Thread" },
        },
    },
    [4320] = { name = "Spidersilk Boots", skill = 125, spec = nil,
        components = {
            { id = 4305,   qty =  2, name = "Bolt of Silk Cloth" },
            { id = 2319,   qty =  4, name = "Medium Leather" },
            { id = 3182,   qty =  4, name = "Spider's Silk" },
            { id = 5500,   qty =  2, name = "Iridescent Pearl" },
        },
    },
    [4331] = { name = "Phoenix Gloves", skill = 125, spec = nil,
        components = {
            { id = 2997,   qty =  4, name = "Bolt of Woolen Cloth" },
            { id = 5500,   qty =  1, name = "Iridescent Pearl" },
            { id = 2321,   qty =  4, name = "Fine Thread" },
            { id = 2324,   qty =  2, name = "Bleach" },
        },
    },
    [4318] = { name = "Gloves of Meditation", skill = 130, spec = nil,
        components = {
            { id = 2997,   qty =  4, name = "Bolt of Woolen Cloth" },
            { id = 2321,   qty =  3, name = "Fine Thread" },
            { id = 3383,   qty =  1, name = "Elixir of Wisdom" },
        },
    },
    [4332] = { name = "Bright Yellow Shirt", skill = 135, spec = nil,
        components = {
            { id = 4305,   qty =  1, name = "Bolt of Silk Cloth" },
            { id = 4341,   qty =  1, name = "Yellow Dye" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
        },
    },
    [5766] = { name = "Lesser Wizard's Robe", skill = 135, spec = nil,
        components = {
            { id = 4305,   qty =  2, name = "Bolt of Silk Cloth" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
            { id = 3182,   qty =  2, name = "Spider's Silk" },
        },
    },
    [4321] = { name = "Spider Silk Slippers", skill = 140, spec = nil,
        components = {
            { id = 4305,   qty =  3, name = "Bolt of Silk Cloth" },
            { id = 3182,   qty =  1, name = "Spider's Silk" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
        },
    },
    [7046] = { name = "Azure Silk Pants", skill = 140, spec = nil,
        components = {
            { id = 4305,   qty =  4, name = "Bolt of Silk Cloth" },
            { id = 6260,   qty =  2, name = "Blue Dye" },
            { id = 2321,   qty =  3, name = "Fine Thread" },
        },
    },
    [4319] = { name = "Azure Silk Gloves", skill = 145, spec = nil,
        components = {
            { id = 4305,   qty =  3, name = "Bolt of Silk Cloth" },
            { id = 4234,   qty =  2, name = "Heavy Leather" },
            { id = 6260,   qty =  2, name = "Blue Dye" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
        },
    },
    [7047] = { name = "Hands of Darkness", skill = 145, spec = nil,
        components = {
            { id = 4305,   qty =  3, name = "Bolt of Silk Cloth" },
            { id = 4234,   qty =  2, name = "Heavy Leather" },
            { id = 6048,   qty =  2, name = "Shadow Protection Potion" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
        },
    },
    [7048] = { name = "Azure Silk Hood", skill = 145, spec = nil,
        components = {
            { id = 4305,   qty =  2, name = "Bolt of Silk Cloth" },
            { id = 6260,   qty =  2, name = "Blue Dye" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
        },
    },
    [4245] = { name = "Small Silk Pack", skill = 150, spec = nil,
        components = {
            { id = 4305,   qty =  3, name = "Bolt of Silk Cloth" },
            { id = 4234,   qty =  2, name = "Heavy Leather" },
            { id = 2321,   qty =  3, name = "Fine Thread" },
        },
    },
    [4324] = { name = "Azure Silk Vest", skill = 150, spec = nil,
        components = {
            { id = 4305,   qty =  5, name = "Bolt of Silk Cloth" },
            { id = 6260,   qty =  4, name = "Blue Dye" },
        },
    },
    [5770] = { name = "Robes of Arcana", skill = 150, spec = nil,
        components = {
            { id = 4305,   qty =  4, name = "Bolt of Silk Cloth" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
            { id = 3182,   qty =  2, name = "Spider's Silk" },
        },
    },
    [7049] = { name = "Truefaith Gloves", skill = 150, spec = nil,
        components = {
            { id = 4305,   qty =  3, name = "Bolt of Silk Cloth" },
            { id = 4234,   qty =  2, name = "Heavy Leather" },
            { id = 929,    qty =  4, name = "Healing Potion" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
        },
    },
    [4333] = { name = "Dark Silk Shirt", skill = 155, spec = nil,
        components = {
            { id = 4305,   qty =  2, name = "Bolt of Silk Cloth" },
            { id = 4340,   qty =  2, name = "Gray Dye" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
        },
    },
    [6795] = { name = "White Swashbuckler's Shirt", skill = 160, spec = nil,
        components = {
            { id = 4305,   qty =  3, name = "Bolt of Silk Cloth" },
            { id = 2324,   qty =  2, name = "Bleach" },
            { id = 4291,   qty =  1, name = "Silken Thread" },
        },
    },
    [7050] = { name = "Silk Headband", skill = 160, spec = nil,
        components = {
            { id = 4305,   qty =  3, name = "Bolt of Silk Cloth" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
        },
    },
    [4322] = { name = "Enchanter's Cowl", skill = 165, spec = nil,
        components = {
            { id = 4305,   qty =  3, name = "Bolt of Silk Cloth" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
            { id = 4337,   qty =  2, name = "Thick Spider's Silk" },
        },
    },
    [7065] = { name = "Green Silk Armor", skill = 165, spec = nil,
        components = {
            { id = 4305,   qty =  5, name = "Bolt of Silk Cloth" },
            { id = 2605,   qty =  2, name = "Green Dye" },
            { id = 4291,   qty =  1, name = "Silken Thread" },
        },
    },
    [4323] = { name = "Shadow Hood", skill = 170, spec = nil,
        components = {
            { id = 4305,   qty =  4, name = "Bolt of Silk Cloth" },
            { id = 4291,   qty =  1, name = "Silken Thread" },
            { id = 3824,   qty =  1, name = "Shadow Oil" },
        },
    },
    [4334] = { name = "Formal White Shirt", skill = 170, spec = nil,
        components = {
            { id = 4305,   qty =  3, name = "Bolt of Silk Cloth" },
            { id = 2324,   qty =  2, name = "Bleach" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
        },
    },
    [7051] = { name = "Earthen Vest", skill = 170, spec = nil,
        components = {
            { id = 4305,   qty =  3, name = "Bolt of Silk Cloth" },
            { id = 7067,   qty =  1, name = "Elemental Earth" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
        },
    },
    [4325] = { name = "Boots of the Enchanter", skill = 175, spec = nil,
        components = {
            { id = 4305,   qty =  4, name = "Bolt of Silk Cloth" },
            { id = 4291,   qty =  1, name = "Silken Thread" },
            { id = 4337,   qty =  2, name = "Thick Spider's Silk" },
        },
    },
    [4339] = { name = "Bolt of Mageweave", skill = 175, spec = nil,
        components = {
            { id = 4338,   qty =  5, name = "Mageweave Cloth" },
        },
    },
    [5764] = { name = "Green Silk Pack", skill = 175, spec = nil,
        components = {
            { id = 4305,   qty =  4, name = "Bolt of Silk Cloth" },
            { id = 4234,   qty =  3, name = "Heavy Leather" },
            { id = 2321,   qty =  3, name = "Fine Thread" },
            { id = 2605,   qty =  1, name = "Green Dye" },
        },
    },
    [6796] = { name = "Red Swashbuckler's Shirt", skill = 175, spec = nil,
        components = {
            { id = 4305,   qty =  3, name = "Bolt of Silk Cloth" },
            { id = 2604,   qty =  2, name = "Red Dye" },
            { id = 4291,   qty =  1, name = "Silken Thread" },
        },
    },
    [7052] = { name = "Azure Silk Belt", skill = 175, spec = nil,
        components = {
            { id = 4305,   qty =  4, name = "Bolt of Silk Cloth" },
            { id = 7070,   qty =  1, name = "Elemental Water" },
            { id = 6260,   qty =  2, name = "Blue Dye" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
            { id = 7071,   qty =  1, name = "Iron Buckle" },
        },
    },
    [7053] = { name = "Azure Silk Cloak", skill = 175, spec = nil,
        components = {
            { id = 4305,   qty =  3, name = "Bolt of Silk Cloth" },
            { id = 6260,   qty =  2, name = "Blue Dye" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
        },
    },
    [7055] = { name = "Crimson Silk Belt", skill = 175, spec = nil,
        components = {
            { id = 4305,   qty =  4, name = "Bolt of Silk Cloth" },
            { id = 7071,   qty =  1, name = "Iron Buckle" },
            { id = 2604,   qty =  2, name = "Red Dye" },
            { id = 4291,   qty =  1, name = "Silken Thread" },
        },
    },
    [4328] = { name = "Spider Belt", skill = 180, spec = nil,
        components = {
            { id = 4305,   qty =  4, name = "Bolt of Silk Cloth" },
            { id = 4337,   qty =  2, name = "Thick Spider's Silk" },
            { id = 7071,   qty =  1, name = "Iron Buckle" },
        },
    },
    [7056] = { name = "Crimson Silk Cloak", skill = 180, spec = nil,
        components = {
            { id = 4305,   qty =  5, name = "Bolt of Silk Cloth" },
            { id = 2604,   qty =  2, name = "Red Dye" },
            { id = 6371,   qty =  2, name = "Fire Oil" },
            { id = 4291,   qty =  1, name = "Silken Thread" },
        },
    },
    [7057] = { name = "Green Silken Shoulders", skill = 180, spec = nil,
        components = {
            { id = 4305,   qty =  5, name = "Bolt of Silk Cloth" },
            { id = 4291,   qty =  2, name = "Silken Thread" },
        },
    },
    [4326] = { name = "Long Silken Cloak", skill = 185, spec = nil,
        components = {
            { id = 4305,   qty =  4, name = "Bolt of Silk Cloth" },
            { id = 3827,   qty =  1, name = "Mana Potion" },
            { id = 4291,   qty =  1, name = "Silken Thread" },
        },
    },
    [4335] = { name = "Rich Purple Silk Shirt", skill = 185, spec = nil,
        components = {
            { id = 4305,   qty =  4, name = "Bolt of Silk Cloth" },
            { id = 4342,   qty =  1, name = "Purple Dye" },
            { id = 4291,   qty =  1, name = "Silken Thread" },
        },
    },
    [5765] = { name = "Black Silk Pack", skill = 185, spec = nil,
        components = {
            { id = 4305,   qty =  5, name = "Bolt of Silk Cloth" },
            { id = 2325,   qty =  1, name = "Black Dye" },
            { id = 2321,   qty =  4, name = "Fine Thread" },
        },
    },
    [7058] = { name = "Crimson Silk Vest", skill = 185, spec = nil,
        components = {
            { id = 4305,   qty =  4, name = "Bolt of Silk Cloth" },
            { id = 2604,   qty =  2, name = "Red Dye" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
        },
    },
    [7054] = { name = "Robe of Power", skill = 190, spec = nil,
        components = {
            { id = 4339,   qty =  2, name = "Bolt of Mageweave" },
            { id = 7067,   qty =  2, name = "Elemental Earth" },
            { id = 7070,   qty =  2, name = "Elemental Water" },
            { id = 7068,   qty =  2, name = "Elemental Fire" },
            { id = 7069,   qty =  2, name = "Elemental Air" },
            { id = 4291,   qty =  2, name = "Silken Thread" },
        },
    },
    [7059] = { name = "Crimson Silk Shoulders", skill = 190, spec = nil,
        components = {
            { id = 4305,   qty =  5, name = "Bolt of Silk Cloth" },
            { id = 6371,   qty =  2, name = "Fire Oil" },
            { id = 2604,   qty =  2, name = "Red Dye" },
            { id = 4291,   qty =  2, name = "Silken Thread" },
        },
    },
    [7060] = { name = "Azure Shoulders", skill = 190, spec = nil,
        components = {
            { id = 4305,   qty =  6, name = "Bolt of Silk Cloth" },
            { id = 7072,   qty =  2, name = "Naga Scale" },
            { id = 6260,   qty =  2, name = "Blue Dye" },
            { id = 4291,   qty =  2, name = "Silken Thread" },
        },
    },
    [17723] = { name = "Green Holiday Shirt", skill = 190, spec = nil,
        components = {
            { id = 4305,   qty =  5, name = "Bolt of Silk Cloth" },
            { id = 2605,   qty =  4, name = "Green Dye" },
            { id = 4291,   qty =  1, name = "Silken Thread" },
        },
    },
    [7061] = { name = "Earthen Silk Belt", skill = 195, spec = nil,
        components = {
            { id = 4305,   qty =  5, name = "Bolt of Silk Cloth" },
            { id = 7067,   qty =  4, name = "Elemental Earth" },
            { id = 4234,   qty =  4, name = "Heavy Leather" },
            { id = 7071,   qty =  1, name = "Iron Buckle" },
            { id = 4291,   qty =  2, name = "Silken Thread" },
        },
    },
    [7062] = { name = "Crimson Silk Pantaloons", skill = 195, spec = nil,
        components = {
            { id = 4305,   qty =  4, name = "Bolt of Silk Cloth" },
            { id = 2604,   qty =  2, name = "Red Dye" },
            { id = 4291,   qty =  2, name = "Silken Thread" },
        },
    },
    [4327] = { name = "Icy Cloak", skill = 200, spec = nil,
        components = {
            { id = 4339,   qty =  3, name = "Bolt of Mageweave" },
            { id = 4291,   qty =  2, name = "Silken Thread" },
            { id = 3829,   qty =  1, name = "Frost Oil" },
            { id = 4337,   qty =  2, name = "Thick Spider's Silk" },
        },
    },
    [4329] = { name = "Star Belt", skill = 200, spec = nil,
        components = {
            { id = 4339,   qty =  4, name = "Bolt of Mageweave" },
            { id = 4234,   qty =  4, name = "Heavy Leather" },
            { id = 3864,   qty =  1, name = "Citrine" },
            { id = 7071,   qty =  1, name = "Iron Buckle" },
            { id = 4291,   qty =  1, name = "Silken Thread" },
        },
    },
    [4336] = { name = "Black Swashbuckler's Shirt", skill = 200, spec = nil,
        components = {
            { id = 4305,   qty =  5, name = "Bolt of Silk Cloth" },
            { id = 2325,   qty =  1, name = "Black Dye" },
            { id = 4291,   qty =  1, name = "Silken Thread" },
        },
    },
    [7063] = { name = "Crimson Silk Robe", skill = 205, spec = nil,
        components = {
            { id = 4305,   qty =  8, name = "Bolt of Silk Cloth" },
            { id = 7068,   qty =  4, name = "Elemental Fire" },
            { id = 3827,   qty =  2, name = "Mana Potion" },
            { id = 2604,   qty =  4, name = "Red Dye" },
            { id = 4291,   qty =  1, name = "Silken Thread" },
        },
    },
    [9998] = { name = "Black Mageweave Vest", skill = 205, spec = nil,
        components = {
            { id = 4339,   qty =  2, name = "Bolt of Mageweave" },
            { id = 4291,   qty =  3, name = "Silken Thread" },
        },
    },
    [9999] = { name = "Black Mageweave Leggings", skill = 205, spec = nil,
        components = {
            { id = 4339,   qty =  2, name = "Bolt of Mageweave" },
            { id = 4291,   qty =  3, name = "Silken Thread" },
        },
    },
    [7064] = { name = "Crimson Silk Gloves", skill = 210, spec = nil,
        components = {
            { id = 4305,   qty =  6, name = "Bolt of Silk Cloth" },
            { id = 7068,   qty =  2, name = "Elemental Fire" },
            { id = 6371,   qty =  2, name = "Fire Oil" },
            { id = 4304,   qty =  2, name = "Thick Leather" },
            { id = 2604,   qty =  4, name = "Red Dye" },
            { id = 4291,   qty =  2, name = "Silken Thread" },
        },
    },
    [10001] = { name = "Black Mageweave Robe", skill = 210, spec = nil,
        components = {
            { id = 4339,   qty =  3, name = "Bolt of Mageweave" },
            { id = 8343,   qty =  1, name = "Heavy Silken Thread" },
        },
    },
    [10002] = { name = "Shadoweave Pants", skill = 210, spec = nil,
        components = {
            { id = 4339,   qty =  3, name = "Bolt of Mageweave" },
            { id = 10285,  qty =  2, name = "Shadow Silk" },
            { id = 8343,   qty =  1, name = "Heavy Silken Thread" },
        },
    },
    [10003] = { name = "Black Mageweave Gloves", skill = 215, spec = nil,
        components = {
            { id = 4339,   qty =  2, name = "Bolt of Mageweave" },
            { id = 8343,   qty =  2, name = "Heavy Silken Thread" },
        },
    },
    [10004] = { name = "Shadoweave Robe", skill = 215, spec = nil,
        components = {
            { id = 4339,   qty =  3, name = "Bolt of Mageweave" },
            { id = 10285,  qty =  2, name = "Shadow Silk" },
            { id = 8343,   qty =  1, name = "Heavy Silken Thread" },
        },
    },
    [10007] = { name = "Red Mageweave Vest", skill = 215, spec = nil,
        components = {
            { id = 4339,   qty =  3, name = "Bolt of Mageweave" },
            { id = 2604,   qty =  2, name = "Red Dye" },
            { id = 8343,   qty =  1, name = "Heavy Silken Thread" },
        },
    },
    [10008] = { name = "White Bandit Mask", skill = 215, spec = nil,
        components = {
            { id = 4339,   qty =  1, name = "Bolt of Mageweave" },
            { id = 2324,   qty =  1, name = "Bleach" },
            { id = 8343,   qty =  1, name = "Heavy Silken Thread" },
        },
    },
    [10009] = { name = "Red Mageweave Pants", skill = 215, spec = nil,
        components = {
            { id = 4339,   qty =  3, name = "Bolt of Mageweave" },
            { id = 2604,   qty =  2, name = "Red Dye" },
            { id = 8343,   qty =  1, name = "Heavy Silken Thread" },
        },
    },
    [10056] = { name = "Orange Mageweave Shirt", skill = 215, spec = nil,
        components = {
            { id = 4339,   qty =  1, name = "Bolt of Mageweave" },
            { id = 6261,   qty =  1, name = "Orange Dye" },
            { id = 8343,   qty =  1, name = "Heavy Silken Thread" },
        },
    },
    [10052] = { name = "Orange Martial Shirt", skill = 220, spec = nil,
        components = {
            { id = 4339,   qty =  2, name = "Bolt of Mageweave" },
            { id = 6261,   qty =  2, name = "Orange Dye" },
            { id = 8343,   qty =  1, name = "Heavy Silken Thread" },
        },
    },
    [10018] = { name = "Red Mageweave Gloves", skill = 225, spec = nil,
        components = {
            { id = 4339,   qty =  3, name = "Bolt of Mageweave" },
            { id = 2604,   qty =  2, name = "Red Dye" },
            { id = 8343,   qty =  2, name = "Heavy Silken Thread" },
        },
    },
    [10019] = { name = "Dreamweave Gloves", skill = 225, spec = nil,
        components = {
            { id = 4339,   qty =  4, name = "Bolt of Mageweave" },
            { id = 8153,   qty =  4, name = "Wildvine" },
            { id = 10286,  qty =  2, name = "Heart of the Wild" },
            { id = 8343,   qty =  2, name = "Heavy Silken Thread" },
        },
    },
    [10021] = { name = "Dreamweave Vest", skill = 225, spec = nil,
        components = {
            { id = 4339,   qty =  6, name = "Bolt of Mageweave" },
            { id = 8153,   qty =  6, name = "Wildvine" },
            { id = 10286,  qty =  2, name = "Heart of the Wild" },
            { id = 8343,   qty =  2, name = "Heavy Silken Thread" },
        },
    },
    [10023] = { name = "Shadoweave Gloves", skill = 225, spec = nil,
        components = {
            { id = 4339,   qty =  5, name = "Bolt of Mageweave" },
            { id = 10285,  qty =  5, name = "Shadow Silk" },
            { id = 8343,   qty =  2, name = "Heavy Silken Thread" },
        },
    },
    [10042] = { name = "Cindercloth Robe", skill = 225, spec = nil,
        components = {
            { id = 4339,   qty =  5, name = "Bolt of Mageweave" },
            { id = 7077,   qty =  2, name = "Heart of Fire" },
            { id = 8343,   qty =  2, name = "Heavy Silken Thread" },
        },
    },
    [10050] = { name = "Mageweave Bag", skill = 225, spec = nil,
        components = {
            { id = 4339,   qty =  4, name = "Bolt of Mageweave" },
            { id = 4291,   qty =  2, name = "Silken Thread" },
        },
    },
    [22246] = { name = "Enchanted Mageweave Pouch", skill = 225, spec = nil,
        components = {
            { id = 4339,   qty =  4, name = "Bolt of Mageweave" },
            { id = 11137,  qty =  4, name = "Vision Dust" },
            { id = 8343,   qty =  2, name = "Heavy Silken Thread" },
        },
    },
    [10024] = { name = "Black Mageweave Headband", skill = 230, spec = nil,
        components = {
            { id = 4339,   qty =  3, name = "Bolt of Mageweave" },
            { id = 8343,   qty =  2, name = "Heavy Silken Thread" },
        },
    },
    [10026] = { name = "Black Mageweave Boots", skill = 230, spec = nil,
        components = {
            { id = 4339,   qty =  3, name = "Bolt of Mageweave" },
            { id = 8343,   qty =  2, name = "Heavy Silken Thread" },
            { id = 4304,   qty =  2, name = "Thick Leather" },
        },
    },
    [10027] = { name = "Black Mageweave Shoulders", skill = 230, spec = nil,
        components = {
            { id = 4339,   qty =  3, name = "Bolt of Mageweave" },
            { id = 8343,   qty =  2, name = "Heavy Silken Thread" },
        },
    },
    [10054] = { name = "Lavender Mageweave Shirt", skill = 230, spec = nil,
        components = {
            { id = 4339,   qty =  2, name = "Bolt of Mageweave" },
            { id = 4342,   qty =  2, name = "Purple Dye" },
            { id = 8343,   qty =  2, name = "Heavy Silken Thread" },
        },
    },
    [10028] = { name = "Shadoweave Shoulders", skill = 235, spec = nil,
        components = {
            { id = 4339,   qty =  5, name = "Bolt of Mageweave" },
            { id = 10285,  qty =  4, name = "Shadow Silk" },
            { id = 8343,   qty =  2, name = "Heavy Silken Thread" },
        },
    },
    [10029] = { name = "Red Mageweave Shoulders", skill = 235, spec = nil,
        components = {
            { id = 4339,   qty =  4, name = "Bolt of Mageweave" },
            { id = 2604,   qty =  2, name = "Red Dye" },
            { id = 8343,   qty =  3, name = "Heavy Silken Thread" },
        },
    },
    [10051] = { name = "Red Mageweave Bag", skill = 235, spec = nil,
        components = {
            { id = 4339,   qty =  4, name = "Bolt of Mageweave" },
            { id = 2604,   qty =  2, name = "Red Dye" },
            { id = 8343,   qty =  2, name = "Heavy Silken Thread" },
        },
    },
    [10053] = { name = "Simple Black Dress", skill = 235, spec = nil,
        components = {
            { id = 4339,   qty =  3, name = "Bolt of Mageweave" },
            { id = 2325,   qty =  1, name = "Black Dye" },
            { id = 8343,   qty =  1, name = "Heavy Silken Thread" },
            { id = 2324,   qty =  1, name = "Bleach" },
        },
    },
    [10055] = { name = "Pink Mageweave Shirt", skill = 235, spec = nil,
        components = {
            { id = 4339,   qty =  3, name = "Bolt of Mageweave" },
            { id = 10290,  qty =  1, name = "Pink Dye" },
            { id = 8343,   qty =  1, name = "Heavy Silken Thread" },
        },
    },
    [10030] = { name = "Admiral's Hat", skill = 240, spec = nil,
        components = {
            { id = 4339,   qty =  3, name = "Bolt of Mageweave" },
            { id = 4589,   qty =  6, name = "Long Elegant Feather" },
            { id = 8343,   qty =  2, name = "Heavy Silken Thread" },
        },
    },
    [10031] = { name = "Shadoweave Boots", skill = 240, spec = nil,
        components = {
            { id = 4339,   qty =  6, name = "Bolt of Mageweave" },
            { id = 10285,  qty =  6, name = "Shadow Silk" },
            { id = 8343,   qty =  3, name = "Heavy Silken Thread" },
            { id = 4304,   qty =  2, name = "Thick Leather" },
        },
    },
    [10033] = { name = "Red Mageweave Headband", skill = 240, spec = nil,
        components = {
            { id = 4339,   qty =  4, name = "Bolt of Mageweave" },
            { id = 2604,   qty =  2, name = "Red Dye" },
            { id = 8343,   qty =  2, name = "Heavy Silken Thread" },
        },
    },
    [10034] = { name = "Tuxedo Shirt", skill = 240, spec = nil,
        components = {
            { id = 4339,   qty =  4, name = "Bolt of Mageweave" },
            { id = 8343,   qty =  2, name = "Heavy Silken Thread" },
        },
    },
    [10025] = { name = "Shadoweave Mask", skill = 245, spec = nil,
        components = {
            { id = 4339,   qty =  2, name = "Bolt of Mageweave" },
            { id = 10285,  qty =  8, name = "Shadow Silk" },
            { id = 8343,   qty =  2, name = "Heavy Silken Thread" },
        },
    },
    [10035] = { name = "Tuxedo Pants", skill = 245, spec = nil,
        components = {
            { id = 4339,   qty =  4, name = "Bolt of Mageweave" },
            { id = 8343,   qty =  3, name = "Heavy Silken Thread" },
        },
    },
    [10044] = { name = "Cindercloth Boots", skill = 245, spec = nil,
        components = {
            { id = 4339,   qty =  5, name = "Bolt of Mageweave" },
            { id = 7077,   qty =  1, name = "Heart of Fire" },
            { id = 8343,   qty =  3, name = "Heavy Silken Thread" },
            { id = 4304,   qty =  2, name = "Thick Leather" },
        },
    },
    [10036] = { name = "Tuxedo Jacket", skill = 250, spec = nil,
        components = {
            { id = 4339,   qty =  5, name = "Bolt of Mageweave" },
            { id = 8343,   qty =  3, name = "Heavy Silken Thread" },
        },
    },
    [10040] = { name = "White Wedding Dress", skill = 250, spec = nil,
        components = {
            { id = 4339,   qty =  5, name = "Bolt of Mageweave" },
            { id = 8343,   qty =  3, name = "Heavy Silken Thread" },
            { id = 2324,   qty =  1, name = "Bleach" },
        },
    },
    [10041] = { name = "Dreamweave Circlet", skill = 250, spec = nil,
        components = {
            { id = 4339,   qty =  8, name = "Bolt of Mageweave" },
            { id = 8153,   qty =  4, name = "Wildvine" },
            { id = 10286,  qty =  2, name = "Heart of the Wild" },
            { id = 8343,   qty =  3, name = "Heavy Silken Thread" },
            { id = 6037,   qty =  1, name = "Truesilver Bar" },
            { id = 1529,   qty =  1, name = "Jade" },
        },
    },
    [14048] = { name = "Bolt of Runecloth", skill = 250, spec = nil,
        components = {
            { id = 14047,  qty =  5, name = "Runecloth" },
        },
    },
    [14342] = { name = "Mooncloth", skill = 250, spec = nil,
        components = {
            { id = 14256,  qty =  2, name = "Felcloth" },
        },
    },
    [21154] = { name = "Festival Dress", skill = 250, spec = nil,
        components = {
            { id = 14048,  qty =  4, name = "Bolt of Runecloth" },
            { id = 4625,   qty =  2, name = "Firebloom" },
            { id = 2604,   qty =  2, name = "Red Dye" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [21542] = { name = "Festival Suit", skill = 250, spec = nil,
        components = {
            { id = 14048,  qty =  4, name = "Bolt of Runecloth" },
            { id = 4625,   qty =  2, name = "Firebloom" },
            { id = 2604,   qty =  2, name = "Red Dye" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [13856] = { name = "Runecloth Belt", skill = 255, spec = nil,
        components = {
            { id = 14048,  qty =  3, name = "Bolt of Runecloth" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [13868] = { name = "Frostweave Robe", skill = 255, spec = nil,
        components = {
            { id = 14048,  qty =  5, name = "Bolt of Runecloth" },
            { id = 7079,   qty =  2, name = "Globe of Water" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [13869] = { name = "Frostweave Tunic", skill = 255, spec = nil,
        components = {
            { id = 14048,  qty =  5, name = "Bolt of Runecloth" },
            { id = 7079,   qty =  2, name = "Globe of Water" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [13857] = { name = "Runecloth Tunic", skill = 260, spec = nil,
        components = {
            { id = 14048,  qty =  5, name = "Bolt of Runecloth" },
            { id = 14227,  qty =  1, name = "Ironweb Spider Silk" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [13858] = { name = "Runecloth Robe", skill = 260, spec = nil,
        components = {
            { id = 14048,  qty =  5, name = "Bolt of Runecloth" },
            { id = 14227,  qty =  1, name = "Ironweb Spider Silk" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [14042] = { name = "Cindercloth Vest", skill = 260, spec = nil,
        components = {
            { id = 14048,  qty =  5, name = "Bolt of Runecloth" },
            { id = 7077,   qty =  3, name = "Heart of Fire" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [14046] = { name = "Runecloth Bag", skill = 260, spec = nil,
        components = {
            { id = 14048,  qty =  5, name = "Bolt of Runecloth" },
            { id = 8170,   qty =  2, name = "Rugged Leather" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [21340] = { name = "Soul Pouch", skill = 260, spec = nil,
        components = {
            { id = 14048,  qty =  6, name = "Bolt of Runecloth" },
            { id = 8170,   qty =  4, name = "Rugged Leather" },
            { id = 7972,   qty =  2, name = "Ichor of Undeath" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [13860] = { name = "Runecloth Cloak", skill = 265, spec = nil,
        components = {
            { id = 14048,  qty =  4, name = "Bolt of Runecloth" },
            { id = 14227,  qty =  1, name = "Ironweb Spider Silk" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [13870] = { name = "Frostweave Gloves", skill = 265, spec = nil,
        components = {
            { id = 14048,  qty =  3, name = "Bolt of Runecloth" },
            { id = 7080,   qty =  1, name = "Essence of Water" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [14143] = { name = "Ghostweave Belt", skill = 265, spec = nil,
        components = {
            { id = 14048,  qty =  3, name = "Bolt of Runecloth" },
            { id = 9210,   qty =  2, name = "Ghost Dye" },
            { id = 14227,  qty =  1, name = "Ironweb Spider Silk" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [14043] = { name = "Cindercloth Gloves", skill = 270, spec = nil,
        components = {
            { id = 14048,  qty =  4, name = "Bolt of Runecloth" },
            { id = 7077,   qty =  3, name = "Heart of Fire" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [14100] = { name = "Brightcloth Robe", skill = 270, spec = nil,
        components = {
            { id = 14048,  qty =  5, name = "Bolt of Runecloth" },
            { id = 3577,   qty =  2, name = "Gold Bar" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [14101] = { name = "Brightcloth Gloves", skill = 270, spec = nil,
        components = {
            { id = 14048,  qty =  4, name = "Bolt of Runecloth" },
            { id = 3577,   qty =  2, name = "Gold Bar" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [14142] = { name = "Ghostweave Gloves", skill = 270, spec = nil,
        components = {
            { id = 14048,  qty =  4, name = "Bolt of Runecloth" },
            { id = 9210,   qty =  2, name = "Ghost Dye" },
            { id = 14227,  qty =  1, name = "Ironweb Spider Silk" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [13863] = { name = "Runecloth Gloves", skill = 275, spec = nil,
        components = {
            { id = 14048,  qty =  4, name = "Bolt of Runecloth" },
            { id = 8170,   qty =  4, name = "Rugged Leather" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [14044] = { name = "Cindercloth Cloak", skill = 275, spec = nil,
        components = {
            { id = 14048,  qty =  5, name = "Bolt of Runecloth" },
            { id = 7078,   qty =  1, name = "Essence of Fire" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [14103] = { name = "Brightcloth Cloak", skill = 275, spec = nil,
        components = {
            { id = 14048,  qty =  4, name = "Bolt of Runecloth" },
            { id = 3577,   qty =  2, name = "Gold Bar" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [14107] = { name = "Felcloth Pants", skill = 275, spec = nil,
        components = {
            { id = 14048,  qty =  5, name = "Bolt of Runecloth" },
            { id = 14256,  qty =  4, name = "Felcloth" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [14132] = { name = "Wizardweave Leggings", skill = 275, spec = nil,
        components = {
            { id = 14048,  qty =  6, name = "Bolt of Runecloth" },
            { id = 11176,  qty =  1, name = "Dream Dust" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [14134] = { name = "Cloak of Fire", skill = 275, spec = nil,
        components = {
            { id = 14048,  qty =  6, name = "Bolt of Runecloth" },
            { id = 7078,   qty =  4, name = "Essence of Fire" },
            { id = 7077,   qty =  4, name = "Heart of Fire" },
            { id = 7068,   qty =  4, name = "Elemental Fire" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [14141] = { name = "Ghostweave Vest", skill = 275, spec = nil,
        components = {
            { id = 14048,  qty =  6, name = "Bolt of Runecloth" },
            { id = 9210,   qty =  4, name = "Ghost Dye" },
            { id = 14227,  qty =  1, name = "Ironweb Spider Silk" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [22248] = { name = "Enchanted Runecloth Bag", skill = 275, spec = nil,
        components = {
            { id = 14048,  qty =  5, name = "Bolt of Runecloth" },
            { id = 16203,  qty =  2, name = "Greater Eternal Essence" },
            { id = 14341,  qty =  2, name = "Rune Thread" },
        },
    },
    [22251] = { name = "Cenarion Herb Bag", skill = 275, spec = nil,
        components = {
            { id = 14048,  qty =  5, name = "Bolt of Runecloth" },
            { id = 8831,   qty = 10, name = "Purple Lotus" },
            { id = 11040,  qty =  8, name = "Morrowgrain" },
            { id = 14341,  qty =  2, name = "Rune Thread" },
        },
    },
    [13864] = { name = "Runecloth Boots", skill = 280, spec = nil,
        components = {
            { id = 14048,  qty =  4, name = "Bolt of Runecloth" },
            { id = 14227,  qty =  2, name = "Ironweb Spider Silk" },
            { id = 8170,   qty =  4, name = "Rugged Leather" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [13871] = { name = "Frostweave Pants", skill = 280, spec = nil,
        components = {
            { id = 14048,  qty =  6, name = "Bolt of Runecloth" },
            { id = 7080,   qty =  1, name = "Essence of Water" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [14045] = { name = "Cindercloth Pants", skill = 280, spec = nil,
        components = {
            { id = 14048,  qty =  6, name = "Bolt of Runecloth" },
            { id = 7078,   qty =  1, name = "Essence of Fire" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [13865] = { name = "Runecloth Pants", skill = 285, spec = nil,
        components = {
            { id = 14048,  qty =  6, name = "Bolt of Runecloth" },
            { id = 14227,  qty =  2, name = "Ironweb Spider Silk" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [14108] = { name = "Felcloth Boots", skill = 285, spec = nil,
        components = {
            { id = 14048,  qty =  6, name = "Bolt of Runecloth" },
            { id = 14256,  qty =  4, name = "Felcloth" },
            { id = 8170,   qty =  4, name = "Rugged Leather" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [14136] = { name = "Robe of Winter Night", skill = 285, spec = nil,
        components = {
            { id = 14048,  qty = 10, name = "Bolt of Runecloth" },
            { id = 14256,  qty = 12, name = "Felcloth" },
            { id = 12808,  qty =  4, name = "Essence of Undeath" },
            { id = 7080,   qty =  4, name = "Essence of Water" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [18258] = { name = "Gordok Ogre Suit", skill = 285, spec = nil,
        components = {
            { id = 14048,  qty =  2, name = "Bolt of Runecloth" },
            { id = 8170,   qty =  4, name = "Rugged Leather" },
            { id = 18240,  qty =  1, name = "Ogre Tannin" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
            { id = 8170,   qty =  4, name = "Rugged Leather" },
            { id = 14048,  qty =  2, name = "Bolt of Runecloth" },
            { id = 18240,  qty =  1, name = "Ogre Tannin" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [21341] = { name = "Felcloth Bag", skill = 285, spec = nil,
        components = {
            { id = 14256,  qty = 12, name = "Felcloth" },
            { id = 12810,  qty =  6, name = "Enchanted Leather" },
            { id = 20520,  qty =  2, name = "Dark Rune" },
            { id = 14227,  qty =  4, name = "Ironweb Spider Silk" },
        },
    },
    [14104] = { name = "Brightcloth Pants", skill = 290, spec = nil,
        components = {
            { id = 14048,  qty =  6, name = "Bolt of Runecloth" },
            { id = 3577,   qty =  4, name = "Gold Bar" },
            { id = 14227,  qty =  1, name = "Ironweb Spider Silk" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [14111] = { name = "Felcloth Hood", skill = 290, spec = nil,
        components = {
            { id = 14048,  qty =  5, name = "Bolt of Runecloth" },
            { id = 14256,  qty =  4, name = "Felcloth" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [14137] = { name = "Mooncloth Leggings", skill = 290, spec = nil,
        components = {
            { id = 14048,  qty =  6, name = "Bolt of Runecloth" },
            { id = 14342,  qty =  4, name = "Mooncloth" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [14144] = { name = "Ghostweave Pants", skill = 290, spec = nil,
        components = {
            { id = 14048,  qty =  6, name = "Bolt of Runecloth" },
            { id = 9210,   qty =  4, name = "Ghost Dye" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [15802] = { name = "Mooncloth Boots", skill = 290, spec = nil,
        components = {
            { id = 14048,  qty =  6, name = "Bolt of Runecloth" },
            { id = 14342,  qty =  4, name = "Mooncloth" },
            { id = 7971,   qty =  2, name = "Black Pearl" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [19047] = { name = "Wisdom of the Timbermaw", skill = 290, spec = nil,
        components = {
            { id = 14048,  qty =  8, name = "Bolt of Runecloth" },
            { id = 7076,   qty =  3, name = "Essence of Earth" },
            { id = 12803,  qty =  3, name = "Living Essence" },
            { id = 14227,  qty =  2, name = "Ironweb Spider Silk" },
        },
    },
    [19056] = { name = "Argent Boots", skill = 290, spec = nil,
        components = {
            { id = 14048,  qty =  6, name = "Bolt of Runecloth" },
            { id = 12810,  qty =  4, name = "Enchanted Leather" },
            { id = 13926,  qty =  2, name = "Golden Pearl" },
            { id = 12809,  qty =  2, name = "Guardian Stone" },
            { id = 14227,  qty =  2, name = "Ironweb Spider Silk" },
        },
    },
    [13866] = { name = "Runecloth Headband", skill = 295, spec = nil,
        components = {
            { id = 14048,  qty =  4, name = "Bolt of Runecloth" },
            { id = 14227,  qty =  2, name = "Ironweb Spider Silk" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [13867] = { name = "Runecloth Shoulders", skill = 300, spec = nil,
        components = {
            { id = 14048,  qty =  7, name = "Bolt of Runecloth" },
            { id = 14227,  qty =  2, name = "Ironweb Spider Silk" },
            { id = 8170,   qty =  4, name = "Rugged Leather" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [14106] = { name = "Felcloth Robe", skill = 300, spec = nil,
        components = {
            { id = 14048,  qty =  8, name = "Bolt of Runecloth" },
            { id = 14256,  qty =  8, name = "Felcloth" },
            { id = 12662,  qty =  4, name = "Demonic Rune" },
            { id = 14341,  qty =  2, name = "Rune Thread" },
        },
    },
    [14112] = { name = "Felcloth Shoulders", skill = 300, spec = nil,
        components = {
            { id = 14048,  qty =  7, name = "Bolt of Runecloth" },
            { id = 14256,  qty =  6, name = "Felcloth" },
            { id = 12662,  qty =  4, name = "Demonic Rune" },
            { id = 8170,   qty =  4, name = "Rugged Leather" },
            { id = 14341,  qty =  2, name = "Rune Thread" },
        },
    },
    [14128] = { name = "Wizardweave Robe", skill = 300, spec = nil,
        components = {
            { id = 14048,  qty =  8, name = "Bolt of Runecloth" },
            { id = 11176,  qty =  2, name = "Dream Dust" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [14130] = { name = "Wizardweave Turban", skill = 300, spec = nil,
        components = {
            { id = 14048,  qty =  6, name = "Bolt of Runecloth" },
            { id = 11176,  qty =  4, name = "Dream Dust" },
            { id = 7910,   qty =  1, name = "Star Ruby" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [14138] = { name = "Mooncloth Vest", skill = 300, spec = nil,
        components = {
            { id = 14048,  qty =  6, name = "Bolt of Runecloth" },
            { id = 14342,  qty =  4, name = "Mooncloth" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [14139] = { name = "Mooncloth Shoulders", skill = 300, spec = nil,
        components = {
            { id = 14048,  qty =  5, name = "Bolt of Runecloth" },
            { id = 14342,  qty =  5, name = "Mooncloth" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [14140] = { name = "Mooncloth Circlet", skill = 300, spec = nil,
        components = {
            { id = 14048,  qty =  4, name = "Bolt of Runecloth" },
            { id = 14342,  qty =  6, name = "Mooncloth" },
            { id = 12800,  qty =  1, name = "Azerothian Diamond" },
            { id = 12810,  qty =  2, name = "Enchanted Leather" },
            { id = 14341,  qty =  2, name = "Rune Thread" },
        },
    },
    [14146] = { name = "Gloves of Spell Mastery", skill = 300, spec = nil,
        components = {
            { id = 14048,  qty = 10, name = "Bolt of Runecloth" },
            { id = 14342,  qty = 10, name = "Mooncloth" },
            { id = 9210,   qty = 10, name = "Ghost Dye" },
            { id = 13926,  qty =  6, name = "Golden Pearl" },
            { id = 12364,  qty =  6, name = "Huge Emerald" },
            { id = 12810,  qty =  8, name = "Enchanted Leather" },
            { id = 14341,  qty =  2, name = "Rune Thread" },
        },
    },
    [14152] = { name = "Robe of the Archmage", skill = 300, spec = nil,
        components = {
            { id = 14048,  qty = 12, name = "Bolt of Runecloth" },
            { id = 7078,   qty = 10, name = "Essence of Fire" },
            { id = 7082,   qty = 10, name = "Essence of Air" },
            { id = 7076,   qty = 10, name = "Essence of Earth" },
            { id = 7080,   qty = 10, name = "Essence of Water" },
            { id = 14341,  qty =  2, name = "Rune Thread" },
        },
    },
    [14153] = { name = "Robe of the Void", skill = 300, spec = nil,
        components = {
            { id = 14048,  qty = 12, name = "Bolt of Runecloth" },
            { id = 12662,  qty = 20, name = "Demonic Rune" },
            { id = 14256,  qty = 40, name = "Felcloth" },
            { id = 7078,   qty = 12, name = "Essence of Fire" },
            { id = 12808,  qty = 12, name = "Essence of Undeath" },
            { id = 14341,  qty =  2, name = "Rune Thread" },
        },
    },
    [14154] = { name = "Truefaith Vestments", skill = 300, spec = nil,
        components = {
            { id = 14048,  qty = 12, name = "Bolt of Runecloth" },
            { id = 14342,  qty = 10, name = "Mooncloth" },
            { id = 12811,  qty =  4, name = "Righteous Orb" },
            { id = 13926,  qty =  4, name = "Golden Pearl" },
            { id = 9210,   qty = 10, name = "Ghost Dye" },
            { id = 14341,  qty =  2, name = "Rune Thread" },
        },
    },
    [14155] = { name = "Mooncloth Bag", skill = 300, spec = nil,
        components = {
            { id = 14048,  qty =  4, name = "Bolt of Runecloth" },
            { id = 14342,  qty =  1, name = "Mooncloth" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [14156] = { name = "Bottomless Bag", skill = 300, spec = nil,
        components = {
            { id = 14048,  qty =  8, name = "Bolt of Runecloth" },
            { id = 14342,  qty = 12, name = "Mooncloth" },
            { id = 14344,  qty =  2, name = "Large Brilliant Shard" },
            { id = 17012,  qty =  2, name = "Core Leather" },
            { id = 14341,  qty =  2, name = "Rune Thread" },
        },
    },
    [16979] = { name = "Flarecore Gloves", skill = 300, spec = nil,
        components = {
            { id = 14048,  qty =  8, name = "Bolt of Runecloth" },
            { id = 17010,  qty =  6, name = "Fiery Core" },
            { id = 7078,   qty =  4, name = "Essence of Fire" },
            { id = 12810,  qty =  2, name = "Enchanted Leather" },
            { id = 14341,  qty =  2, name = "Rune Thread" },
        },
    },
    [16980] = { name = "Flarecore Mantle", skill = 300, spec = nil,
        components = {
            { id = 14048,  qty = 12, name = "Bolt of Runecloth" },
            { id = 17010,  qty =  4, name = "Fiery Core" },
            { id = 17011,  qty =  4, name = "Lava Core" },
            { id = 12810,  qty =  6, name = "Enchanted Leather" },
            { id = 14341,  qty =  2, name = "Rune Thread" },
        },
    },
    [18263] = { name = "Flarecore Wraps", skill = 300, spec = nil,
        components = {
            { id = 14342,  qty =  6, name = "Mooncloth" },
            { id = 17010,  qty =  8, name = "Fiery Core" },
            { id = 7078,   qty =  2, name = "Essence of Fire" },
            { id = 12810,  qty =  6, name = "Enchanted Leather" },
            { id = 14341,  qty =  4, name = "Rune Thread" },
        },
    },
    [18405] = { name = "Belt of the Archmage", skill = 300, spec = nil,
        components = {
            { id = 14048,  qty = 16, name = "Bolt of Runecloth" },
            { id = 9210,   qty = 10, name = "Ghost Dye" },
            { id = 14342,  qty = 10, name = "Mooncloth" },
            { id = 7080,   qty = 12, name = "Essence of Water" },
            { id = 7078,   qty = 12, name = "Essence of Fire" },
            { id = 14344,  qty =  6, name = "Large Brilliant Shard" },
            { id = 14341,  qty =  6, name = "Rune Thread" },
        },
    },
    [18407] = { name = "Felcloth Gloves", skill = 300, spec = nil,
        components = {
            { id = 14048,  qty = 12, name = "Bolt of Runecloth" },
            { id = 14256,  qty = 20, name = "Felcloth" },
            { id = 12662,  qty =  6, name = "Demonic Rune" },
            { id = 12808,  qty =  8, name = "Essence of Undeath" },
            { id = 14341,  qty =  2, name = "Rune Thread" },
        },
    },
    [18408] = { name = "Inferno Gloves", skill = 300, spec = nil,
        components = {
            { id = 14048,  qty = 12, name = "Bolt of Runecloth" },
            { id = 7078,   qty = 10, name = "Essence of Fire" },
            { id = 7910,   qty =  2, name = "Star Ruby" },
            { id = 14341,  qty =  2, name = "Rune Thread" },
        },
    },
    [18409] = { name = "Mooncloth Gloves", skill = 300, spec = nil,
        components = {
            { id = 14048,  qty = 12, name = "Bolt of Runecloth" },
            { id = 14342,  qty =  6, name = "Mooncloth" },
            { id = 13926,  qty =  2, name = "Golden Pearl" },
            { id = 14341,  qty =  2, name = "Rune Thread" },
        },
    },
    [18413] = { name = "Cloak of Warding", skill = 300, spec = nil,
        components = {
            { id = 14048,  qty = 12, name = "Bolt of Runecloth" },
            { id = 12809,  qty =  4, name = "Guardian Stone" },
            { id = 12360,  qty =  1, name = "Arcanite Bar" },
            { id = 14341,  qty =  2, name = "Rune Thread" },
        },
    },
    [18486] = { name = "Mooncloth Robe", skill = 300, spec = nil,
        components = {
            { id = 14048,  qty =  6, name = "Bolt of Runecloth" },
            { id = 14342,  qty =  4, name = "Mooncloth" },
            { id = 13926,  qty =  2, name = "Golden Pearl" },
            { id = 14341,  qty =  2, name = "Rune Thread" },
        },
    },
    [19050] = { name = "Mantle of the Timbermaw", skill = 300, spec = nil,
        components = {
            { id = 14342,  qty =  5, name = "Mooncloth" },
            { id = 7076,   qty =  5, name = "Essence of Earth" },
            { id = 12803,  qty =  5, name = "Living Essence" },
            { id = 14227,  qty =  2, name = "Ironweb Spider Silk" },
        },
    },
    [19059] = { name = "Argent Shoulders", skill = 300, spec = nil,
        components = {
            { id = 14342,  qty =  5, name = "Mooncloth" },
            { id = 12809,  qty =  2, name = "Guardian Stone" },
            { id = 14227,  qty =  2, name = "Ironweb Spider Silk" },
        },
    },
    [19156] = { name = "Flarecore Robe", skill = 300, spec = nil,
        components = {
            { id = 14342,  qty = 10, name = "Mooncloth" },
            { id = 17010,  qty =  2, name = "Fiery Core" },
            { id = 17011,  qty =  3, name = "Lava Core" },
            { id = 7078,   qty =  6, name = "Essence of Fire" },
            { id = 14227,  qty =  4, name = "Ironweb Spider Silk" },
        },
    },
    [19165] = { name = "Flarecore Leggings", skill = 300, spec = nil,
        components = {
            { id = 14342,  qty =  8, name = "Mooncloth" },
            { id = 17010,  qty =  5, name = "Fiery Core" },
            { id = 17011,  qty =  3, name = "Lava Core" },
            { id = 7078,   qty = 10, name = "Essence of Fire" },
            { id = 14227,  qty =  4, name = "Ironweb Spider Silk" },
        },
    },
    [19682] = { name = "Bloodvine Vest", skill = 300, spec = nil,
        components = {
            { id = 14342,  qty =  3, name = "Mooncloth" },
            { id = 19726,  qty =  5, name = "Bloodvine" },
            { id = 12804,  qty =  4, name = "Powerful Mojo" },
            { id = 14048,  qty =  4, name = "Bolt of Runecloth" },
            { id = 14227,  qty =  2, name = "Ironweb Spider Silk" },
        },
    },
    [19683] = { name = "Bloodvine Leggings", skill = 300, spec = nil,
        components = {
            { id = 14342,  qty =  4, name = "Mooncloth" },
            { id = 19726,  qty =  4, name = "Bloodvine" },
            { id = 12804,  qty =  4, name = "Powerful Mojo" },
            { id = 14048,  qty =  4, name = "Bolt of Runecloth" },
            { id = 14227,  qty =  2, name = "Ironweb Spider Silk" },
        },
    },
    [19684] = { name = "Bloodvine Boots", skill = 300, spec = nil,
        components = {
            { id = 14342,  qty =  3, name = "Mooncloth" },
            { id = 19726,  qty =  3, name = "Bloodvine" },
            { id = 12810,  qty =  4, name = "Enchanted Leather" },
            { id = 14048,  qty =  4, name = "Bolt of Runecloth" },
            { id = 14227,  qty =  4, name = "Ironweb Spider Silk" },
        },
    },
    [20537] = { name = "Runed Stygian Boots", skill = 300, spec = nil,
        components = {
            { id = 14048,  qty =  4, name = "Bolt of Runecloth" },
            { id = 20520,  qty =  6, name = "Dark Rune" },
            { id = 14256,  qty =  4, name = "Felcloth" },
            { id = 12810,  qty =  2, name = "Enchanted Leather" },
            { id = 14227,  qty =  2, name = "Ironweb Spider Silk" },
        },
    },
    [20538] = { name = "Runed Stygian Leggings", skill = 300, spec = nil,
        components = {
            { id = 14048,  qty =  6, name = "Bolt of Runecloth" },
            { id = 20520,  qty =  8, name = "Dark Rune" },
            { id = 14256,  qty =  6, name = "Felcloth" },
            { id = 14227,  qty =  2, name = "Ironweb Spider Silk" },
        },
    },
    [20539] = { name = "Runed Stygian Belt", skill = 300, spec = nil,
        components = {
            { id = 14048,  qty =  2, name = "Bolt of Runecloth" },
            { id = 20520,  qty =  6, name = "Dark Rune" },
            { id = 14256,  qty =  2, name = "Felcloth" },
            { id = 12810,  qty =  2, name = "Enchanted Leather" },
            { id = 14227,  qty =  2, name = "Ironweb Spider Silk" },
        },
    },
    [21342] = { name = "Core Felcloth Bag", skill = 300, spec = nil,
        components = {
            { id = 14256,  qty = 20, name = "Felcloth" },
            { id = 17012,  qty = 16, name = "Core Leather" },
            { id = 19726,  qty =  8, name = "Bloodvine" },
            { id = 7078,   qty =  4, name = "Essence of Fire" },
            { id = 14227,  qty =  4, name = "Ironweb Spider Silk" },
        },
    },
    [22249] = { name = "Big Bag of Enchantment", skill = 300, spec = nil,
        components = {
            { id = 14048,  qty =  6, name = "Bolt of Runecloth" },
            { id = 14344,  qty =  4, name = "Large Brilliant Shard" },
            { id = 12810,  qty =  4, name = "Enchanted Leather" },
            { id = 14227,  qty =  4, name = "Ironweb Spider Silk" },
        },
    },
    [22252] = { name = "Satchel of Cenarius", skill = 300, spec = nil,
        components = {
            { id = 14048,  qty =  6, name = "Bolt of Runecloth" },
            { id = 14342,  qty =  2, name = "Mooncloth" },
            { id = 13468,  qty =  1, name = "Black Lotus" },
            { id = 14227,  qty =  4, name = "Ironweb Spider Silk" },
        },
    },
    [22652] = { name = "Glacial Vest", skill = 300, spec = nil,
        components = {
            { id = 22682,  qty =  7, name = "Frozen Rune" },
            { id = 14048,  qty =  8, name = "Bolt of Runecloth" },
            { id = 7080,   qty =  6, name = "Essence of Water" },
            { id = 14227,  qty =  8, name = "Ironweb Spider Silk" },
        },
    },
    [22654] = { name = "Glacial Gloves", skill = 300, spec = nil,
        components = {
            { id = 22682,  qty =  5, name = "Frozen Rune" },
            { id = 14048,  qty =  4, name = "Bolt of Runecloth" },
            { id = 7080,   qty =  4, name = "Essence of Water" },
            { id = 14227,  qty =  4, name = "Ironweb Spider Silk" },
        },
    },
    [22655] = { name = "Glacial Wrists", skill = 300, spec = nil,
        components = {
            { id = 22682,  qty =  4, name = "Frozen Rune" },
            { id = 14048,  qty =  2, name = "Bolt of Runecloth" },
            { id = 7080,   qty =  2, name = "Essence of Water" },
            { id = 14227,  qty =  4, name = "Ironweb Spider Silk" },
        },
    },
    [22658] = { name = "Glacial Cloak", skill = 300, spec = nil,
        components = {
            { id = 22682,  qty =  5, name = "Frozen Rune" },
            { id = 14048,  qty =  4, name = "Bolt of Runecloth" },
            { id = 7080,   qty =  2, name = "Essence of Water" },
            { id = 14227,  qty =  4, name = "Ironweb Spider Silk" },
        },
    },
    [22660] = { name = "Gaea's Embrace", skill = 300, spec = nil,
        components = {
            { id = 19726,  qty =  1, name = "Bloodvine" },
            { id = 14342,  qty =  2, name = "Mooncloth" },
            { id = 12803,  qty =  4, name = "Living Essence" },
            { id = 14227,  qty =  4, name = "Ironweb Spider Silk" },
        },
    },
    [22756] = { name = "Sylvan Vest", skill = 300, spec = nil,
        components = {
            { id = 14048,  qty =  4, name = "Bolt of Runecloth" },
            { id = 19726,  qty =  2, name = "Bloodvine" },
            { id = 12803,  qty =  2, name = "Living Essence" },
            { id = 14227,  qty =  2, name = "Ironweb Spider Silk" },
        },
    },
    [22757] = { name = "Sylvan Crown", skill = 300, spec = nil,
        components = {
            { id = 14048,  qty =  4, name = "Bolt of Runecloth" },
            { id = 14342,  qty =  2, name = "Mooncloth" },
            { id = 12803,  qty =  2, name = "Living Essence" },
            { id = 14227,  qty =  2, name = "Ironweb Spider Silk" },
        },
    },
    [22758] = { name = "Sylvan Shoulders", skill = 300, spec = nil,
        components = {
            { id = 14048,  qty =  2, name = "Bolt of Runecloth" },
            { id = 12803,  qty =  4, name = "Living Essence" },
            { id = 14227,  qty =  2, name = "Ironweb Spider Silk" },
        },
    },
}