-- Alchemy recipes - Source: wow-classic-items npm
-- IDs et composants 100% automatiques

ProfTooltip_Alchemy = {
    [118] = { name = "Minor Healing Potion", skill = 1,
        components = {
            { id = 2447  , qty =  1, name = "Peacebloom" },
            { id = 765   , qty =  1, name = "Silverleaf" },
            { id = 3371  , qty =  1, name = "Empty Vial" },
        },
    },
    [2454] = { name = "Elixir of Lion's Strength", skill = 1,
        components = {
            { id = 2449  , qty =  1, name = "Earthroot" },
            { id = 765   , qty =  1, name = "Silverleaf" },
            { id = 3371  , qty =  1, name = "Empty Vial" },
        },
    },
    [5997] = { name = "Elixir of Minor Defense", skill = 1,
        components = {
            { id = 765   , qty =  2, name = "Silverleaf" },
            { id = 3371  , qty =  1, name = "Empty Vial" },
        },
    },
    [3382] = { name = "Weak Troll's Blood Elixir", skill = 15,
        components = {
            { id = 2447  , qty =  1, name = "Peacebloom" },
            { id = 2449  , qty =  2, name = "Earthroot" },
            { id = 3371  , qty =  1, name = "Empty Vial" },
        },
    },
    [2455] = { name = "Minor Mana Potion", skill = 25,
        components = {
            { id = 785   , qty =  1, name = "Mageroyal" },
            { id = 765   , qty =  1, name = "Silverleaf" },
            { id = 3371  , qty =  1, name = "Empty Vial" },
        },
    },
    [2456] = { name = "Minor Rejuvenation Potion", skill = 40,
        components = {
            { id = 785   , qty =  2, name = "Mageroyal" },
            { id = 2447  , qty =  1, name = "Peacebloom" },
            { id = 3371  , qty =  1, name = "Empty Vial" },
        },
    },
    [2457] = { name = "Elixir of Minor Agility", skill = 50,
        components = {
            { id = 2452  , qty =  1, name = "Swiftthistle" },
            { id = 765   , qty =  1, name = "Silverleaf" },
            { id = 3371  , qty =  1, name = "Empty Vial" },
        },
    },
    [2458] = { name = "Elixir of Minor Fortitude", skill = 50,
        components = {
            { id = 2449  , qty =  2, name = "Earthroot" },
            { id = 2447  , qty =  1, name = "Peacebloom" },
            { id = 3371  , qty =  1, name = "Empty Vial" },
        },
    },
    [4596] = { name = "Discolored Healing Potion", skill = 50,
        components = {
            { id = 3164  , qty =  1, name = "Discolored Worg Heart" },
            { id = 2447  , qty =  1, name = "Peacebloom" },
            { id = 3371  , qty =  1, name = "Empty Vial" },
        },
    },
    [858] = { name = "Lesser Healing Potion", skill = 55,
        components = {
            { id = 118   , qty =  1, name = "Minor Healing Potion" },
            { id = 2450  , qty =  1, name = "Briarthorn" },
        },
    },
    [2459] = { name = "Swiftness Potion", skill = 60,
        components = {
            { id = 2452  , qty =  1, name = "Swiftthistle" },
            { id = 2450  , qty =  1, name = "Briarthorn" },
            { id = 3371  , qty =  1, name = "Empty Vial" },
        },
    },
    [5631] = { name = "Rage Potion", skill = 60,
        components = {
            { id = 5635  , qty =  2, name = "Sharp Claw" },
            { id = 3371  , qty =  1, name = "Empty Vial" },
        },
    },
    [6370] = { name = "Blackmouth Oil", skill = 80,
        components = {
            { id = 6358  , qty =  2, name = "Oily Blackmouth" },
        },
    },
    [3383] = { name = "Elixir of Wisdom", skill = 90,
        components = {
            { id = 785   , qty =  1, name = "Mageroyal" },
            { id = 2450  , qty =  2, name = "Briarthorn" },
            { id = 3371  , qty =  1, name = "Empty Vial" },
        },
    },
    [5996] = { name = "Elixir of Water Breathing", skill = 90,
        components = {
            { id = 3820  , qty =  1, name = "Stranglekelp" },
            { id = 6370  , qty =  2, name = "Blackmouth Oil" },
            { id = 3371  , qty =  1, name = "Empty Vial" },
        },
    },
    [6662] = { name = "Elixir of Giant Growth", skill = 90,
        components = {
            { id = 6522  , qty =  1, name = "Deviate Fish" },
            { id = 2449  , qty =  1, name = "Earthroot" },
            { id = 3371  , qty =  1, name = "Empty Vial" },
        },
    },
    [6051] = { name = "Holy Protection Potion", skill = 100,
        components = {
            { id = 2453  , qty =  1, name = "Bruiseweed" },
            { id = 2452  , qty =  1, name = "Swiftthistle" },
            { id = 3371  , qty =  1, name = "Empty Vial" },
        },
    },
    [6372] = { name = "Swim Speed Potion", skill = 100,
        components = {
            { id = 2452  , qty =  1, name = "Swiftthistle" },
            { id = 6370  , qty =  1, name = "Blackmouth Oil" },
            { id = 3371  , qty =  1, name = "Empty Vial" },
        },
    },
    [929] = { name = "Healing Potion", skill = 110,
        components = {
            { id = 2453  , qty =  1, name = "Bruiseweed" },
            { id = 2450  , qty =  1, name = "Briarthorn" },
            { id = 3372  , qty =  1, name = "Leaded Vial" },
        },
    },
    [3384] = { name = "Minor Magic Resistance Potion", skill = 110,
        components = {
            { id = 785   , qty =  3, name = "Mageroyal" },
            { id = 3355  , qty =  1, name = "Wild Steelbloom" },
            { id = 3371  , qty =  1, name = "Empty Vial" },
        },
    },
    [3386] = { name = "Potion of Curing", skill = 120,
        components = {
            { id = 1288  , qty =  1, name = "Large Venom Sac" },
            { id = 2453  , qty =  1, name = "Bruiseweed" },
            { id = 3372  , qty =  1, name = "Leaded Vial" },
        },
    },
    [3385] = { name = "Lesser Mana Potion", skill = 120,
        components = {
            { id = 785   , qty =  1, name = "Mageroyal" },
            { id = 3820  , qty =  1, name = "Stranglekelp" },
            { id = 3371  , qty =  1, name = "Empty Vial" },
        },
    },
    [3388] = { name = "Strong Troll's Blood Elixir", skill = 125,
        components = {
            { id = 2453  , qty =  2, name = "Bruiseweed" },
            { id = 2450  , qty =  2, name = "Briarthorn" },
            { id = 3372  , qty =  1, name = "Leaded Vial" },
        },
    },
    [3389] = { name = "Elixir of Defense", skill = 130,
        components = {
            { id = 3355  , qty =  1, name = "Wild Steelbloom" },
            { id = 3820  , qty =  1, name = "Stranglekelp" },
            { id = 3372  , qty =  1, name = "Leaded Vial" },
        },
    },
    [6371] = { name = "Fire Oil", skill = 130,
        components = {
            { id = 6359  , qty =  2, name = "Firefin Snapper" },
        },
    },
    [6048] = { name = "Shadow Protection Potion", skill = 135,
        components = {
            { id = 3369  , qty =  1, name = "Grave Moss" },
            { id = 3356  , qty =  1, name = "Kingsblood" },
            { id = 3372  , qty =  1, name = "Leaded Vial" },
        },
    },
    [45621] = { name = "Elixir of Minor Accuracy", skill = 135,
        components = {
            { id = 6371  , qty =  1, name = "Fire Oil" },
            { id = 2453  , qty =  1, name = "Bruiseweed" },
            { id = 3371  , qty =  1, name = "Empty Vial" },
        },
    },
    [3390] = { name = "Elixir of Lesser Agility", skill = 140,
        components = {
            { id = 3355  , qty =  1, name = "Wild Steelbloom" },
            { id = 2452  , qty =  1, name = "Swiftthistle" },
            { id = 3372  , qty =  1, name = "Leaded Vial" },
        },
    },
    [6373] = { name = "Elixir of Firepower", skill = 140,
        components = {
            { id = 6371  , qty =  2, name = "Fire Oil" },
            { id = 3356  , qty =  1, name = "Kingsblood" },
            { id = 3372  , qty =  1, name = "Leaded Vial" },
        },
    },
    [3391] = { name = "Elixir of Ogre's Strength", skill = 150,
        components = {
            { id = 2449  , qty =  1, name = "Earthroot" },
            { id = 3356  , qty =  1, name = "Kingsblood" },
            { id = 3372  , qty =  1, name = "Leaded Vial" },
        },
    },
    [5634] = { name = "Free Action Potion", skill = 150,
        components = {
            { id = 6370  , qty =  2, name = "Blackmouth Oil" },
            { id = 3820  , qty =  1, name = "Stranglekelp" },
            { id = 3372  , qty =  1, name = "Leaded Vial" },
        },
    },
    [1710] = { name = "Greater Healing Potion", skill = 155,
        components = {
            { id = 3357  , qty =  1, name = "Liferoot" },
            { id = 3356  , qty =  1, name = "Kingsblood" },
            { id = 3372  , qty =  1, name = "Leaded Vial" },
        },
    },
    [3827] = { name = "Mana Potion", skill = 160,
        components = {
            { id = 3820  , qty =  1, name = "Stranglekelp" },
            { id = 3356  , qty =  1, name = "Kingsblood" },
            { id = 3372  , qty =  1, name = "Leaded Vial" },
        },
    },
    [3824] = { name = "Shadow Oil", skill = 165,
        components = {
            { id = 3818  , qty =  4, name = "Fadeleaf" },
            { id = 3369  , qty =  4, name = "Grave Moss" },
            { id = 3372  , qty =  1, name = "Leaded Vial" },
        },
    },
    [3823] = { name = "Lesser Invisibility Potion", skill = 165,
        components = {
            { id = 3818  , qty =  1, name = "Fadeleaf" },
            { id = 3355  , qty =  1, name = "Wild Steelbloom" },
            { id = 3372  , qty =  1, name = "Leaded Vial" },
        },
    },
    [6049] = { name = "Fire Protection Potion", skill = 165,
        components = {
            { id = 4402  , qty =  1, name = "Small Flame Sac" },
            { id = 6371  , qty =  1, name = "Fire Oil" },
            { id = 3372  , qty =  1, name = "Leaded Vial" },
        },
    },
    [3825] = { name = "Elixir of Fortitude", skill = 175,
        components = {
            { id = 3355  , qty =  1, name = "Wild Steelbloom" },
            { id = 3821  , qty =  1, name = "Goldthorn" },
            { id = 3372  , qty =  1, name = "Leaded Vial" },
        },
    },
    [5633] = { name = "Great Rage Potion", skill = 175,
        components = {
            { id = 5637  , qty =  1, name = "Large Fang" },
            { id = 3356  , qty =  1, name = "Kingsblood" },
            { id = 3372  , qty =  1, name = "Leaded Vial" },
        },
    },
    [3826] = { name = "Major Troll's Blood Elixir", skill = 180,
        components = {
            { id = 3357  , qty =  1, name = "Liferoot" },
            { id = 2453  , qty =  1, name = "Bruiseweed" },
            { id = 3372  , qty =  1, name = "Leaded Vial" },
        },
    },
    [8949] = { name = "Elixir of Agility", skill = 185,
        components = {
            { id = 3820  , qty =  1, name = "Stranglekelp" },
            { id = 3821  , qty =  1, name = "Goldthorn" },
            { id = 3372  , qty =  1, name = "Leaded Vial" },
        },
    },
    [6050] = { name = "Frost Protection Potion", skill = 190,
        components = {
            { id = 3819  , qty =  1, name = "Wintersbite" },
            { id = 3821  , qty =  1, name = "Goldthorn" },
            { id = 3372  , qty =  1, name = "Leaded Vial" },
        },
    },
    [6052] = { name = "Nature Protection Potion", skill = 190,
        components = {
            { id = 3357  , qty =  1, name = "Liferoot" },
            { id = 3820  , qty =  1, name = "Stranglekelp" },
            { id = 3372  , qty =  1, name = "Leaded Vial" },
        },
    },
    [17708] = { name = "Elixir of Frost Power", skill = 190,
        components = {
            { id = 3819  , qty =  2, name = "Wintersbite" },
            { id = 3358  , qty =  1, name = "Khadgar's Whisker" },
            { id = 3372  , qty =  1, name = "Leaded Vial" },
        },
    },
    [3828] = { name = "Elixir of Detect Lesser Invisibility", skill = 195,
        components = {
            { id = 3358  , qty =  1, name = "Khadgar's Whisker" },
            { id = 3818  , qty =  1, name = "Fadeleaf" },
            { id = 3372  , qty =  1, name = "Leaded Vial" },
        },
    },
    [8951] = { name = "Elixir of Greater Defense", skill = 195,
        components = {
            { id = 3355  , qty =  1, name = "Wild Steelbloom" },
            { id = 3821  , qty =  1, name = "Goldthorn" },
            { id = 3372  , qty =  1, name = "Leaded Vial" },
        },
    },
    [3829] = { name = "Frost Oil", skill = 200,
        components = {
            { id = 3358  , qty =  4, name = "Khadgar's Whisker" },
            { id = 3819  , qty =  2, name = "Wintersbite" },
            { id = 3372  , qty =  1, name = "Leaded Vial" },
        },
    },
    [10592] = { name = "Catseye Elixir", skill = 200,
        components = {
            { id = 3821  , qty =  1, name = "Goldthorn" },
            { id = 3818  , qty =  1, name = "Fadeleaf" },
            { id = 3372  , qty =  1, name = "Leaded Vial" },
        },
    },
    [6149] = { name = "Greater Mana Potion", skill = 205,
        components = {
            { id = 3358  , qty =  1, name = "Khadgar's Whisker" },
            { id = 3821  , qty =  1, name = "Goldthorn" },
            { id = 3372  , qty =  1, name = "Leaded Vial" },
        },
    },
    [8956] = { name = "Oil of Immolation", skill = 205,
        components = {
            { id = 4625  , qty =  1, name = "Firebloom" },
            { id = 3821  , qty =  1, name = "Goldthorn" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [9036] = { name = "Magic Resistance Potion", skill = 210,
        components = {
            { id = 3358  , qty =  1, name = "Khadgar's Whisker" },
            { id = 8831  , qty =  1, name = "Purple Lotus" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [9061] = { name = "Goblin Rocket Fuel", skill = 210,
        components = {
            { id = 4625  , qty =  1, name = "Firebloom" },
            { id = 9260  , qty =  1, name = "Volatile Rum" },
            { id = 3372  , qty =  1, name = "Leaded Vial" },
        },
    },
    [3928] = { name = "Superior Healing Potion", skill = 215,
        components = {
            { id = 8838  , qty =  1, name = "Sungrass" },
            { id = 3358  , qty =  1, name = "Khadgar's Whisker" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [4623] = { name = "Lesser Stoneshield Potion", skill = 215,
        components = {
            { id = 3858  , qty =  1, name = "Mithril Ore" },
            { id = 3821  , qty =  1, name = "Goldthorn" },
            { id = 3372  , qty =  1, name = "Leaded Vial" },
        },
    },
    [9030] = { name = "Restorative Potion", skill = 215,
        components = {
            { id = 7067  , qty =  1, name = "Elemental Earth" },
            { id = 3821  , qty =  1, name = "Goldthorn" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [18294] = { name = "Elixir of Greater Water Breathing", skill = 215,
        components = {
            { id = 7972  , qty =  1, name = "Ichor of Undeath" },
            { id = 8831  , qty =  2, name = "Purple Lotus" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [3577] = { name = "Gold Bar", skill = 225,
        components = {
            { id = 3575  , qty =  1, name = "Iron Bar" },
        },
    },
    [6037] = { name = "Truesilver Bar", skill = 225,
        components = {
            { id = 3860  , qty =  1, name = "Mithril Bar" },
        },
    },
    [9144] = { name = "Wildvine Potion", skill = 225,
        components = {
            { id = 8153  , qty =  1, name = "Wildvine" },
            { id = 8831  , qty =  1, name = "Purple Lotus" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [9149] = { name = "Philosopher's Stone", skill = 225,
        components = {
            { id = 3575  , qty =  4, name = "Iron Bar" },
            { id = 9262  , qty =  1, name = "Black Vitriol" },
            { id = 8831  , qty =  4, name = "Purple Lotus" },
            { id = 4625  , qty =  4, name = "Firebloom" },
        },
    },
    [9154] = { name = "Elixir of Detect Undead", skill = 230,
        components = {
            { id = 8836  , qty =  1, name = "Arthas' Tears" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [12190] = { name = "Dreamless Sleep Potion", skill = 230,
        components = {
            { id = 8831  , qty =  3, name = "Purple Lotus" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [9155] = { name = "Arcane Elixir", skill = 235,
        components = {
            { id = 8839  , qty =  1, name = "Blindweed" },
            { id = 3821  , qty =  1, name = "Goldthorn" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [9172] = { name = "Invisibility Potion", skill = 235,
        components = {
            { id = 8845  , qty =  1, name = "Ghost Mushroom" },
            { id = 8838  , qty =  1, name = "Sungrass" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [9179] = { name = "Elixir of Greater Intellect", skill = 235,
        components = {
            { id = 8839  , qty =  1, name = "Blindweed" },
            { id = 3358  , qty =  1, name = "Khadgar's Whisker" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [9088] = { name = "Gift of Arthas", skill = 240,
        components = {
            { id = 8836  , qty =  1, name = "Arthas' Tears" },
            { id = 8839  , qty =  1, name = "Blindweed" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [9187] = { name = "Elixir of Greater Agility", skill = 240,
        components = {
            { id = 8838  , qty =  1, name = "Sungrass" },
            { id = 3821  , qty =  1, name = "Goldthorn" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [9197] = { name = "Elixir of Dream Vision", skill = 240,
        components = {
            { id = 8831  , qty =  3, name = "Purple Lotus" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [9206] = { name = "Elixir of Giants", skill = 245,
        components = {
            { id = 8838  , qty =  1, name = "Sungrass" },
            { id = 8846  , qty =  1, name = "Gromsblood" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [9210] = { name = "Ghost Dye", skill = 245,
        components = {
            { id = 8845  , qty =  2, name = "Ghost Mushroom" },
            { id = 4342  , qty =  1, name = "Purple Dye" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [3387] = { name = "Limited Invulnerability Potion", skill = 250,
        components = {
            { id = 8839  , qty =  2, name = "Blindweed" },
            { id = 8845  , qty =  1, name = "Ghost Mushroom" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [9224] = { name = "Elixir of Demonslaying", skill = 250,
        components = {
            { id = 8846  , qty =  1, name = "Gromsblood" },
            { id = 8845  , qty =  1, name = "Ghost Mushroom" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [9233] = { name = "Elixir of Detect Demon", skill = 250,
        components = {
            { id = 8846  , qty =  2, name = "Gromsblood" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [9264] = { name = "Elixir of Shadow Power", skill = 250,
        components = {
            { id = 8845  , qty =  3, name = "Ghost Mushroom" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [13423] = { name = "Stonescale Oil", skill = 250,
        components = {
            { id = 13422 , qty =  1, name = "Stonescale Eel" },
        },
    },
    [21546] = { name = "Elixir of Greater Firepower", skill = 250,
        components = {
            { id = 6371  , qty =  3, name = "Fire Oil" },
            { id = 4625  , qty =  3, name = "Firebloom" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [13442] = { name = "Mighty Rage Potion", skill = 255,
        components = {
            { id = 8846  , qty =  3, name = "Gromsblood" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [13443] = { name = "Superior Mana Potion", skill = 260,
        components = {
            { id = 8838  , qty =  2, name = "Sungrass" },
            { id = 8839  , qty =  2, name = "Blindweed" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [13445] = { name = "Elixir of Superior Defense", skill = 265,
        components = {
            { id = 13423 , qty =  2, name = "Stonescale Oil" },
            { id = 8838  , qty =  1, name = "Sungrass" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [13447] = { name = "Elixir of the Sages", skill = 270,
        components = {
            { id = 13463 , qty =  1, name = "Dreamfoil" },
            { id = 13466 , qty =  2, name = "Plaguebloom" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [7078] = { name = "Essence of Fire", skill = 275,
        components = {
            { id = 7082  , qty =  1, name = "Essence of Air" },
        },
    },
    [7076] = { name = "Essence of Earth", skill = 275,
        components = {
            { id = 7078  , qty =  1, name = "Essence of Fire" },
        },
    },
    [7080] = { name = "Essence of Water", skill = 275,
        components = {
            { id = 7076  , qty =  1, name = "Essence of Earth" },
        },
    },
    [7082] = { name = "Essence of Air", skill = 275,
        components = {
            { id = 7080  , qty =  1, name = "Essence of Water" },
        },
    },
    [12360] = { name = "Arcanite Bar", skill = 275,
        components = {
            { id = 12359 , qty =  1, name = "Thorium Bar" },
            { id = 12363 , qty =  1, name = "Arcane Crystal" },
        },
    },
    [12803] = { name = "Living Essence", skill = 275,
        components = {
            { id = 7076  , qty =  1, name = "Essence of Earth" },
        },
    },
    [12808] = { name = "Essence of Undeath", skill = 275,
        components = {
            { id = 7080  , qty =  1, name = "Essence of Water" },
        },
    },
    [13446] = { name = "Major Healing Potion", skill = 275,
        components = {
            { id = 13464 , qty =  2, name = "Golden Sansam" },
            { id = 13465 , qty =  1, name = "Mountain Silversage" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [13453] = { name = "Elixir of Brute Force", skill = 275,
        components = {
            { id = 8846  , qty =  2, name = "Gromsblood" },
            { id = 13466 , qty =  2, name = "Plaguebloom" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [20002] = { name = "Greater Dreamless Sleep Potion", skill = 275,
        components = {
            { id = 13463 , qty =  2, name = "Dreamfoil" },
            { id = 13464 , qty =  1, name = "Golden Sansam" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [20007] = { name = "Mageblood Elixir", skill = 275,
        components = {
            { id = 13463 , qty =  1, name = "Dreamfoil" },
            { id = 13466 , qty =  2, name = "Plaguebloom" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [13452] = { name = "Elixir of the Mongoose", skill = 280,
        components = {
            { id = 13465 , qty =  2, name = "Mountain Silversage" },
            { id = 13466 , qty =  2, name = "Plaguebloom" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [13455] = { name = "Greater Stoneshield Potion", skill = 280,
        components = {
            { id = 13423 , qty =  2, name = "Stonescale Oil" },
            { id = 10620 , qty =  1, name = "Thorium Ore" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [13454] = { name = "Greater Arcane Elixir", skill = 285,
        components = {
            { id = 13463 , qty =  3, name = "Dreamfoil" },
            { id = 13465 , qty =  1, name = "Mountain Silversage" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [13462] = { name = "Purification Potion", skill = 285,
        components = {
            { id = 13467 , qty =  2, name = "Icecap" },
            { id = 13466 , qty =  2, name = "Plaguebloom" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [20008] = { name = "Living Action Potion", skill = 285,
        components = {
            { id = 13467 , qty =  2, name = "Icecap" },
            { id = 13465 , qty =  2, name = "Mountain Silversage" },
            { id = 10286 , qty =  2, name = "Heart of the Wild" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [13456] = { name = "Greater Frost Protection Potion", skill = 290,
        components = {
            { id = 7070  , qty =  1, name = "Elemental Water" },
            { id = 13463 , qty =  1, name = "Dreamfoil" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [13458] = { name = "Greater Nature Protection Potion", skill = 290,
        components = {
            { id = 7067  , qty =  1, name = "Elemental Earth" },
            { id = 13463 , qty =  1, name = "Dreamfoil" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [13459] = { name = "Greater Shadow Protection Potion", skill = 290,
        components = {
            { id = 3824  , qty =  1, name = "Shadow Oil" },
            { id = 13463 , qty =  1, name = "Dreamfoil" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [13457] = { name = "Greater Fire Protection Potion", skill = 290,
        components = {
            { id = 7068  , qty =  1, name = "Elemental Fire" },
            { id = 13463 , qty =  1, name = "Dreamfoil" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [13461] = { name = "Greater Arcane Protection Potion", skill = 290,
        components = {
            { id = 11176 , qty =  1, name = "Dream Dust" },
            { id = 13463 , qty =  1, name = "Dreamfoil" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [20004] = { name = "Mighty Troll's Blood Elixir", skill = 290,
        components = {
            { id = 8846  , qty =  1, name = "Gromsblood" },
            { id = 13466 , qty =  2, name = "Plaguebloom" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [13444] = { name = "Major Mana Potion", skill = 295,
        components = {
            { id = 13463 , qty =  3, name = "Dreamfoil" },
            { id = 13467 , qty =  2, name = "Icecap" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [7068] = { name = "Elemental Fire", skill = 300,
        components = {
            { id = 7077  , qty =  1, name = "Heart of Fire" },
        },
    },
    [13503] = { name = "Alchemist's Stone", skill = 300,
        components = {
            { id = 9149  , qty =  1, name = "Philosopher's Stone" },
            { id = 25867 , qty =  1, name = "Earthstorm Diamond" },
            { id = 25868 , qty =  1, name = "Skyfire Diamond" },
            { id = 22794 , qty =  2, name = "Fel Lotus" },
            { id = 23571 , qty =  5, name = "Primal Might" },
        },
    },
    [13506] = { name = "Potion of Petrification", skill = 300,
        components = {
            { id = 13423 , qty =  7, name = "Stonescale Oil" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [13510] = { name = "Flask of the Titans", skill = 300,
        components = {
            { id = 8846  , qty =  7, name = "Gromsblood" },
            { id = 13423 , qty =  3, name = "Stonescale Oil" },
            { id = 13468 , qty =  1, name = "Black Lotus" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [13511] = { name = "Flask of Distilled Wisdom", skill = 300,
        components = {
            { id = 13463 , qty =  7, name = "Dreamfoil" },
            { id = 13467 , qty =  3, name = "Icecap" },
            { id = 13468 , qty =  1, name = "Black Lotus" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [13513] = { name = "Flask of Chromatic Resistance", skill = 300,
        components = {
            { id = 13467 , qty =  7, name = "Icecap" },
            { id = 13465 , qty =  3, name = "Mountain Silversage" },
            { id = 13468 , qty =  1, name = "Black Lotus" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [13512] = { name = "Flask of Supreme Power", skill = 300,
        components = {
            { id = 13463 , qty =  7, name = "Dreamfoil" },
            { id = 13465 , qty =  3, name = "Mountain Silversage" },
            { id = 13468 , qty =  1, name = "Black Lotus" },
            { id = 8925  , qty =  1, name = "Crystal Vial" },
        },
    },
    [18253] = { name = "Major Rejuvenation Potion", skill = 300,
        components = {
            { id = 10286 , qty =  1, name = "Heart of the Wild" },
            { id = 13464 , qty =  4, name = "Golden Sansam" },
            { id = 13463 , qty =  4, name = "Dreamfoil" },
            { id = 18256 , qty =  1, name = "Imbued Vial" },
        },
    },
    [28100] = { name = "Volatile Healing Potion", skill = 300,
        components = {
            { id = 13464 , qty =  1, name = "Golden Sansam" },
            { id = 22785 , qty =  1, name = "Felweed" },
            { id = 18256 , qty =  1, name = "Imbued Vial" },
        },
    },
    [28102] = { name = "Onslaught Elixir", skill = 300,
        components = {
            { id = 13465 , qty =  1, name = "Mountain Silversage" },
            { id = 22785 , qty =  1, name = "Felweed" },
            { id = 18256 , qty =  1, name = "Imbued Vial" },
        },
    },
    [28103] = { name = "Adept's Elixir", skill = 300,
        components = {
            { id = 13463 , qty =  1, name = "Dreamfoil" },
            { id = 22785 , qty =  1, name = "Felweed" },
            { id = 18256 , qty =  1, name = "Imbued Vial" },
        },
    },
}