-- Leatherworking recipes - Source: wow-classic-items npm
-- WoW Classic Era (Interface 11508)

ProfTooltip_Leatherworking = {

    [2302] = { name = "Handstitched Leather Boots", skill = 1, spec = nil,
        components = {
            { id = 2318,   qty =  2, name = "Light Leather" },
            { id = 2320,   qty =  1, name = "Coarse Thread" },
        },
    },
    [2304] = { name = "Light Armor Kit", skill = 1, spec = nil,
        components = {
            { id = 2318,   qty =  1, name = "Light Leather" },
        },
    },
    [2318] = { name = "Light Leather", skill = 1, spec = nil,
        components = {
            { id = 2934,   qty =  3, name = "Ruined Leather Scraps" },
        },
    },
    [5957] = { name = "Handstitched Leather Vest", skill = 1, spec = nil,
        components = {
            { id = 2318,   qty =  3, name = "Light Leather" },
            { id = 2320,   qty =  1, name = "Coarse Thread" },
        },
    },
    [7276] = { name = "Handstitched Leather Cloak", skill = 1, spec = nil,
        components = {
            { id = 2318,   qty =  2, name = "Light Leather" },
            { id = 2320,   qty =  1, name = "Coarse Thread" },
        },
    },
    [7277] = { name = "Handstitched Leather Bracers", skill = 1, spec = nil,
        components = {
            { id = 2318,   qty =  2, name = "Light Leather" },
            { id = 2320,   qty =  3, name = "Coarse Thread" },
        },
    },
    [2303] = { name = "Handstitched Leather Pants", skill = 15, spec = nil,
        components = {
            { id = 2318,   qty =  4, name = "Light Leather" },
            { id = 2320,   qty =  1, name = "Coarse Thread" },
        },
    },
    [4237] = { name = "Handstitched Leather Belt", skill = 25, spec = nil,
        components = {
            { id = 2318,   qty =  6, name = "Light Leather" },
            { id = 2320,   qty =  1, name = "Coarse Thread" },
        },
    },
    [7278] = { name = "Light Leather Quiver", skill = 30, spec = nil,
        components = {
            { id = 2318,   qty =  4, name = "Light Leather" },
            { id = 2320,   qty =  2, name = "Coarse Thread" },
        },
    },
    [7279] = { name = "Small Leather Ammo Pouch", skill = 30, spec = nil,
        components = {
            { id = 2318,   qty =  3, name = "Light Leather" },
            { id = 2320,   qty =  4, name = "Coarse Thread" },
        },
    },
    [4231] = { name = "Cured Light Hide", skill = 35, spec = nil,
        components = {
            { id = 783,    qty =  1, name = "Light Hide" },
            { id = 4289,   qty =  1, name = "Salt" },
        },
    },
    [7280] = { name = "Rugged Leather Pants", skill = 35, spec = nil,
        components = {
            { id = 2318,   qty =  5, name = "Light Leather" },
            { id = 2320,   qty =  5, name = "Coarse Thread" },
        },
    },
    [2300] = { name = "Embossed Leather Vest", skill = 40, spec = nil,
        components = {
            { id = 2318,   qty =  8, name = "Light Leather" },
            { id = 2320,   qty =  4, name = "Coarse Thread" },
        },
    },
    [5081] = { name = "Kodo Hide Bag", skill = 40, spec = nil,
        components = {
            { id = 5082,   qty =  3, name = "Thin Kodo Leather" },
            { id = 2318,   qty =  4, name = "Light Leather" },
            { id = 2320,   qty =  1, name = "Coarse Thread" },
        },
    },
    [2309] = { name = "Embossed Leather Boots", skill = 55, spec = nil,
        components = {
            { id = 2318,   qty =  8, name = "Light Leather" },
            { id = 2320,   qty =  5, name = "Coarse Thread" },
        },
    },
    [4239] = { name = "Embossed Leather Gloves", skill = 55, spec = nil,
        components = {
            { id = 2318,   qty =  3, name = "Light Leather" },
            { id = 2320,   qty =  2, name = "Coarse Thread" },
        },
    },
    [2310] = { name = "Embossed Leather Cloak", skill = 60, spec = nil,
        components = {
            { id = 2318,   qty =  5, name = "Light Leather" },
            { id = 2320,   qty =  2, name = "Coarse Thread" },
        },
    },
    [2311] = { name = "White Leather Jerkin", skill = 60, spec = nil,
        components = {
            { id = 2318,   qty =  8, name = "Light Leather" },
            { id = 2320,   qty =  2, name = "Coarse Thread" },
            { id = 2324,   qty =  1, name = "Bleach" },
        },
    },
    [7281] = { name = "Light Leather Bracers", skill = 70, spec = nil,
        components = {
            { id = 2318,   qty =  6, name = "Light Leather" },
            { id = 2320,   qty =  4, name = "Coarse Thread" },
        },
    },
    [2312] = { name = "Fine Leather Gloves", skill = 75, spec = nil,
        components = {
            { id = 4231,   qty =  1, name = "Cured Light Hide" },
            { id = 2318,   qty =  4, name = "Light Leather" },
            { id = 2320,   qty =  2, name = "Coarse Thread" },
        },
    },
    [4242] = { name = "Embossed Leather Pants", skill = 75, spec = nil,
        components = {
            { id = 4231,   qty =  1, name = "Cured Light Hide" },
            { id = 2318,   qty =  6, name = "Light Leather" },
            { id = 2320,   qty =  2, name = "Coarse Thread" },
        },
    },
    [4246] = { name = "Fine Leather Belt", skill = 80, spec = nil,
        components = {
            { id = 2318,   qty =  6, name = "Light Leather" },
            { id = 2320,   qty =  2, name = "Coarse Thread" },
        },
    },
    [2308] = { name = "Fine Leather Cloak", skill = 85, spec = nil,
        components = {
            { id = 2318,   qty = 10, name = "Light Leather" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
        },
    },
    [4243] = { name = "Fine Leather Tunic", skill = 85, spec = nil,
        components = {
            { id = 4231,   qty =  3, name = "Cured Light Hide" },
            { id = 2318,   qty =  6, name = "Light Leather" },
            { id = 2320,   qty =  4, name = "Coarse Thread" },
        },
    },
    [2307] = { name = "Fine Leather Boots", skill = 90, spec = nil,
        components = {
            { id = 2318,   qty =  7, name = "Light Leather" },
            { id = 2320,   qty =  2, name = "Coarse Thread" },
        },
    },
    [5780] = { name = "Murloc Scale Belt", skill = 90, spec = nil,
        components = {
            { id = 5784,   qty =  8, name = "Slimy Murloc Scale" },
            { id = 2318,   qty =  6, name = "Light Leather" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
        },
    },
    [6466] = { name = "Deviate Scale Cloak", skill = 90, spec = nil,
        components = {
            { id = 6470,   qty =  4, name = "Deviate Scale" },
            { id = 4231,   qty =  1, name = "Cured Light Hide" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
        },
    },
    [6709] = { name = "Moonglow Vest", skill = 90, spec = nil,
        components = {
            { id = 2318,   qty =  6, name = "Light Leather" },
            { id = 4231,   qty =  1, name = "Cured Light Hide" },
            { id = 2320,   qty =  4, name = "Coarse Thread" },
            { id = 5498,   qty =  1, name = "Small Lustrous Pearl" },
        },
    },
    [5781] = { name = "Murloc Scale Breastplate", skill = 95, spec = nil,
        components = {
            { id = 5784,   qty = 12, name = "Slimy Murloc Scale" },
            { id = 4231,   qty =  1, name = "Cured Light Hide" },
            { id = 2318,   qty =  8, name = "Light Leather" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
        },
    },
    [7282] = { name = "Light Leather Pants", skill = 95, spec = nil,
        components = {
            { id = 2318,   qty = 10, name = "Light Leather" },
            { id = 4231,   qty =  1, name = "Cured Light Hide" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
        },
    },
    [2313] = { name = "Medium Armor Kit", skill = 100, spec = nil,
        components = {
            { id = 2319,   qty =  4, name = "Medium Leather" },
            { id = 2320,   qty =  1, name = "Coarse Thread" },
        },
    },
    [2315] = { name = "Dark Leather Boots", skill = 100, spec = nil,
        components = {
            { id = 2319,   qty =  4, name = "Medium Leather" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
            { id = 4340,   qty =  1, name = "Gray Dye" },
        },
    },
    [2317] = { name = "Dark Leather Tunic", skill = 100, spec = nil,
        components = {
            { id = 2319,   qty =  6, name = "Medium Leather" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
            { id = 4340,   qty =  1, name = "Gray Dye" },
        },
    },
    [2319] = { name = "Medium Leather", skill = 100, spec = nil,
        components = {
            { id = 2318,   qty =  4, name = "Light Leather" },
        },
    },
    [4233] = { name = "Cured Medium Hide", skill = 100, spec = nil,
        components = {
            { id = 4232,   qty =  1, name = "Medium Hide" },
            { id = 4289,   qty =  1, name = "Salt" },
        },
    },
    [4244] = { name = "Hillman's Leather Vest", skill = 100, spec = nil,
        components = {
            { id = 4243,   qty =  1, name = "Fine Leather Tunic" },
            { id = 4231,   qty =  2, name = "Cured Light Hide" },
            { id = 2320,   qty =  2, name = "Coarse Thread" },
        },
    },
    [7283] = { name = "Black Whelp Cloak", skill = 100, spec = nil,
        components = {
            { id = 7286,   qty = 12, name = "Black Whelp Scale" },
            { id = 2319,   qty =  4, name = "Medium Leather" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
        },
    },
    [20575] = { name = "Black Whelp Tunic", skill = 100, spec = nil,
        components = {
            { id = 2319,   qty =  8, name = "Medium Leather" },
            { id = 7286,   qty =  8, name = "Black Whelp Scale" },
            { id = 4231,   qty =  1, name = "Cured Light Hide" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
        },
    },
    [5958] = { name = "Fine Leather Pants", skill = 105, spec = nil,
        components = {
            { id = 2319,   qty =  8, name = "Medium Leather" },
            { id = 2997,   qty =  1, name = "Bolt of Woolen Cloth" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
        },
    },
    [6467] = { name = "Deviate Scale Gloves", skill = 105, spec = nil,
        components = {
            { id = 6470,   qty =  5, name = "Deviate Scale" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
        },
    },
    [2316] = { name = "Dark Leather Cloak", skill = 110, spec = nil,
        components = {
            { id = 2319,   qty =  8, name = "Medium Leather" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
            { id = 4340,   qty =  1, name = "Gray Dye" },
        },
    },
    [5961] = { name = "Dark Leather Pants", skill = 115, spec = nil,
        components = {
            { id = 2319,   qty = 12, name = "Medium Leather" },
            { id = 4340,   qty =  1, name = "Gray Dye" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
        },
    },
    [6468] = { name = "Deviate Scale Belt", skill = 115, spec = nil,
        components = {
            { id = 6471,   qty =  6, name = "Perfect Deviate Scale" },
            { id = 6470,   qty =  4, name = "Deviate Scale" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
        },
    },
    [2314] = { name = "Toughened Leather Armor", skill = 120, spec = nil,
        components = {
            { id = 2319,   qty = 10, name = "Medium Leather" },
            { id = 4231,   qty =  6, name = "Cured Light Hide" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
        },
    },
    [4248] = { name = "Dark Leather Gloves", skill = 120, spec = nil,
        components = {
            { id = 2319,   qty =  8, name = "Medium Leather" },
            { id = 5373,   qty =  2, name = "Lucky Charm" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
            { id = 4340,   qty =  1, name = "Gray Dye" },
        },
    },
    [4250] = { name = "Hillman's Belt", skill = 120, spec = nil,
        components = {
            { id = 2319,   qty =  8, name = "Medium Leather" },
            { id = 3383,   qty =  1, name = "Elixir of Wisdom" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
        },
    },
    [7284] = { name = "Red Whelp Gloves", skill = 120, spec = nil,
        components = {
            { id = 7287,   qty =  6, name = "Red Whelp Scale" },
            { id = 2319,   qty =  4, name = "Medium Leather" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
        },
    },
    [7285] = { name = "Nimble Leather Gloves", skill = 120, spec = nil,
        components = {
            { id = 2457,   qty =  1, name = "Elixir of Minor Agility" },
            { id = 2319,   qty =  6, name = "Medium Leather" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
        },
    },
    [4249] = { name = "Dark Leather Belt", skill = 125, spec = nil,
        components = {
            { id = 4246,   qty =  1, name = "Fine Leather Belt" },
            { id = 4233,   qty =  1, name = "Cured Medium Hide" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
            { id = 4340,   qty =  1, name = "Gray Dye" },
        },
    },
    [7348] = { name = "Fletcher's Gloves", skill = 125, spec = nil,
        components = {
            { id = 2319,   qty =  8, name = "Medium Leather" },
            { id = 4233,   qty =  4, name = "Cured Medium Hide" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
        },
    },
    [4251] = { name = "Hillman's Shoulders", skill = 130, spec = nil,
        components = {
            { id = 4233,   qty =  1, name = "Cured Medium Hide" },
            { id = 2319,   qty =  4, name = "Medium Leather" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
        },
    },
    [4253] = { name = "Toughened Leather Gloves", skill = 135, spec = nil,
        components = {
            { id = 2319,   qty =  4, name = "Medium Leather" },
            { id = 4233,   qty =  2, name = "Cured Medium Hide" },
            { id = 3389,   qty =  2, name = "Elixir of Defense" },
            { id = 3182,   qty =  2, name = "Spider's Silk" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
        },
    },
    [7349] = { name = "Herbalist's Gloves", skill = 135, spec = nil,
        components = {
            { id = 2319,   qty =  8, name = "Medium Leather" },
            { id = 3356,   qty =  4, name = "Kingsblood" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
        },
    },
    [7352] = { name = "Earthen Leather Shoulders", skill = 135, spec = nil,
        components = {
            { id = 2319,   qty =  6, name = "Medium Leather" },
            { id = 7067,   qty =  1, name = "Elemental Earth" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
        },
    },
    [4252] = { name = "Dark Leather Shoulders", skill = 140, spec = nil,
        components = {
            { id = 2319,   qty = 12, name = "Medium Leather" },
            { id = 3390,   qty =  1, name = "Elixir of Lesser Agility" },
            { id = 4340,   qty =  1, name = "Gray Dye" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
        },
    },
    [7358] = { name = "Pilferer's Gloves", skill = 140, spec = nil,
        components = {
            { id = 2319,   qty = 10, name = "Medium Leather" },
            { id = 5373,   qty =  2, name = "Lucky Charm" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
        },
    },
    [4247] = { name = "Hillman's Leather Gloves", skill = 145, spec = nil,
        components = {
            { id = 2319,   qty = 14, name = "Medium Leather" },
            { id = 2321,   qty =  4, name = "Fine Thread" },
        },
    },
    [7359] = { name = "Heavy Earthen Gloves", skill = 145, spec = nil,
        components = {
            { id = 2319,   qty = 12, name = "Medium Leather" },
            { id = 7067,   qty =  2, name = "Elemental Earth" },
            { id = 2997,   qty =  2, name = "Bolt of Woolen Cloth" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
        },
    },
    [3719] = { name = "Hillman's Cloak", skill = 150, spec = nil,
        components = {
            { id = 4234,   qty =  5, name = "Heavy Leather" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
        },
    },
    [4234] = { name = "Heavy Leather", skill = 150, spec = nil,
        components = {
            { id = 2319,   qty =  5, name = "Medium Leather" },
        },
    },
    [4236] = { name = "Cured Heavy Hide", skill = 150, spec = nil,
        components = {
            { id = 4235,   qty =  1, name = "Heavy Hide" },
            { id = 4289,   qty =  3, name = "Salt" },
        },
    },
    [4254] = { name = "Barbaric Gloves", skill = 150, spec = nil,
        components = {
            { id = 4234,   qty =  6, name = "Heavy Leather" },
            { id = 5637,   qty =  2, name = "Large Fang" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
        },
    },
    [4265] = { name = "Heavy Armor Kit", skill = 150, spec = nil,
        components = {
            { id = 4234,   qty =  5, name = "Heavy Leather" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
        },
    },
    [7371] = { name = "Heavy Quiver", skill = 150, spec = nil,
        components = {
            { id = 4234,   qty =  8, name = "Heavy Leather" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
        },
    },
    [7372] = { name = "Heavy Leather Ammo Pouch", skill = 150, spec = nil,
        components = {
            { id = 4234,   qty =  8, name = "Heavy Leather" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
        },
    },
    [18662] = { name = "Heavy Leather Ball", skill = 150, spec = nil,
        components = {
            { id = 4234,   qty =  2, name = "Heavy Leather" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
        },
    },
    [4255] = { name = "Green Leather Armor", skill = 155, spec = nil,
        components = {
            { id = 4234,   qty =  9, name = "Heavy Leather" },
            { id = 2605,   qty =  2, name = "Green Dye" },
            { id = 2321,   qty =  4, name = "Fine Thread" },
        },
    },
    [18948] = { name = "Barbaric Bracers", skill = 155, spec = nil,
        components = {
            { id = 4234,   qty =  8, name = "Heavy Leather" },
            { id = 4236,   qty =  2, name = "Cured Heavy Hide" },
            { id = 5498,   qty =  4, name = "Small Lustrous Pearl" },
            { id = 4461,   qty =  1, name = "Raptor Hide" },
            { id = 5637,   qty =  4, name = "Large Fang" },
        },
    },
    [4257] = { name = "Green Leather Belt", skill = 160, spec = nil,
        components = {
            { id = 4236,   qty =  1, name = "Cured Heavy Hide" },
            { id = 4234,   qty =  5, name = "Heavy Leather" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
            { id = 2605,   qty =  1, name = "Green Dye" },
            { id = 7071,   qty =  1, name = "Iron Buckle" },
        },
    },
    [5962] = { name = "Guardian Pants", skill = 160, spec = nil,
        components = {
            { id = 4234,   qty = 12, name = "Heavy Leather" },
            { id = 4305,   qty =  2, name = "Bolt of Silk Cloth" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
        },
    },
    [4455] = { name = "Raptor Hide Harness", skill = 165, spec = nil,
        components = {
            { id = 4461,   qty =  6, name = "Raptor Hide" },
            { id = 4234,   qty =  4, name = "Heavy Leather" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
        },
    },
    [4456] = { name = "Raptor Hide Belt", skill = 165, spec = nil,
        components = {
            { id = 4461,   qty =  4, name = "Raptor Hide" },
            { id = 4234,   qty =  4, name = "Heavy Leather" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
        },
    },
    [7373] = { name = "Dusky Leather Leggings", skill = 165, spec = nil,
        components = {
            { id = 4234,   qty = 10, name = "Heavy Leather" },
            { id = 2325,   qty =  1, name = "Black Dye" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
        },
    },
    [4258] = { name = "Guardian Belt", skill = 170, spec = nil,
        components = {
            { id = 4236,   qty =  2, name = "Cured Heavy Hide" },
            { id = 4234,   qty =  4, name = "Heavy Leather" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
            { id = 7071,   qty =  1, name = "Iron Buckle" },
        },
    },
    [5782] = { name = "Thick Murloc Armor", skill = 170, spec = nil,
        components = {
            { id = 5785,   qty = 12, name = "Thick Murloc Scale" },
            { id = 4236,   qty =  1, name = "Cured Heavy Hide" },
            { id = 4234,   qty = 10, name = "Heavy Leather" },
            { id = 2321,   qty =  3, name = "Fine Thread" },
        },
    },
    [5963] = { name = "Barbaric Leggings", skill = 170, spec = nil,
        components = {
            { id = 4234,   qty = 10, name = "Heavy Leather" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
            { id = 1206,   qty =  1, name = "Moss Agate" },
        },
    },
    [4256] = { name = "Guardian Armor", skill = 175, spec = nil,
        components = {
            { id = 4236,   qty =  2, name = "Cured Heavy Hide" },
            { id = 4234,   qty = 12, name = "Heavy Leather" },
            { id = 3824,   qty =  1, name = "Shadow Oil" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
        },
    },
    [5964] = { name = "Barbaric Shoulders", skill = 175, spec = nil,
        components = {
            { id = 4234,   qty =  8, name = "Heavy Leather" },
            { id = 4236,   qty =  1, name = "Cured Heavy Hide" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
        },
    },
    [7374] = { name = "Dusky Leather Armor", skill = 175, spec = nil,
        components = {
            { id = 4234,   qty = 10, name = "Heavy Leather" },
            { id = 3824,   qty =  1, name = "Shadow Oil" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
        },
    },
    [7375] = { name = "Green Whelp Armor", skill = 175, spec = nil,
        components = {
            { id = 7392,   qty =  4, name = "Green Whelp Scale" },
            { id = 4234,   qty = 10, name = "Heavy Leather" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
        },
    },
    [4259] = { name = "Green Leather Bracers", skill = 180, spec = nil,
        components = {
            { id = 4236,   qty =  2, name = "Cured Heavy Hide" },
            { id = 4234,   qty =  6, name = "Heavy Leather" },
            { id = 2605,   qty =  1, name = "Green Dye" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
        },
    },
    [7377] = { name = "Frost Leather Cloak", skill = 180, spec = nil,
        components = {
            { id = 4234,   qty =  6, name = "Heavy Leather" },
            { id = 7067,   qty =  2, name = "Elemental Earth" },
            { id = 7070,   qty =  2, name = "Elemental Water" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
        },
    },
    [4262] = { name = "Gem-studded Leather Belt", skill = 185, spec = nil,
        components = {
            { id = 4236,   qty =  4, name = "Cured Heavy Hide" },
            { id = 5500,   qty =  1, name = "Iridescent Pearl" },
            { id = 1529,   qty =  1, name = "Jade" },
            { id = 3864,   qty =  1, name = "Citrine" },
            { id = 2321,   qty =  1, name = "Fine Thread" },
        },
    },
    [5965] = { name = "Guardian Cloak", skill = 185, spec = nil,
        components = {
            { id = 4234,   qty = 14, name = "Heavy Leather" },
            { id = 4305,   qty =  2, name = "Bolt of Silk Cloth" },
            { id = 4291,   qty =  2, name = "Silken Thread" },
        },
    },
    [7378] = { name = "Dusky Bracers", skill = 185, spec = nil,
        components = {
            { id = 4234,   qty = 16, name = "Heavy Leather" },
            { id = 2325,   qty =  1, name = "Black Dye" },
            { id = 4291,   qty =  2, name = "Silken Thread" },
        },
    },
    [5739] = { name = "Barbaric Harness", skill = 190, spec = nil,
        components = {
            { id = 4234,   qty = 14, name = "Heavy Leather" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
            { id = 7071,   qty =  1, name = "Iron Buckle" },
        },
    },
    [5783] = { name = "Murloc Scale Bracers", skill = 190, spec = nil,
        components = {
            { id = 5785,   qty = 16, name = "Thick Murloc Scale" },
            { id = 4236,   qty =  1, name = "Cured Heavy Hide" },
            { id = 4234,   qty = 14, name = "Heavy Leather" },
            { id = 4291,   qty =  1, name = "Silken Thread" },
        },
    },
    [5966] = { name = "Guardian Gloves", skill = 190, spec = nil,
        components = {
            { id = 4234,   qty =  4, name = "Heavy Leather" },
            { id = 4236,   qty =  1, name = "Cured Heavy Hide" },
            { id = 4291,   qty =  1, name = "Silken Thread" },
        },
    },
    [7386] = { name = "Green Whelp Bracers", skill = 190, spec = nil,
        components = {
            { id = 7392,   qty =  6, name = "Green Whelp Scale" },
            { id = 4234,   qty =  8, name = "Heavy Leather" },
            { id = 4291,   qty =  2, name = "Silken Thread" },
        },
    },
    [17721] = { name = "Gloves of the Greatfather", skill = 190, spec = nil,
        components = {
            { id = 4234,   qty =  8, name = "Heavy Leather" },
            { id = 7067,   qty =  4, name = "Elemental Earth" },
            { id = 4291,   qty =  1, name = "Silken Thread" },
        },
    },
    [4260] = { name = "Guardian Leather Bracers", skill = 195, spec = nil,
        components = {
            { id = 4234,   qty =  6, name = "Heavy Leather" },
            { id = 4236,   qty =  2, name = "Cured Heavy Hide" },
            { id = 4291,   qty =  1, name = "Silken Thread" },
        },
    },
    [7387] = { name = "Dusky Belt", skill = 195, spec = nil,
        components = {
            { id = 4234,   qty = 10, name = "Heavy Leather" },
            { id = 4305,   qty =  2, name = "Bolt of Silk Cloth" },
            { id = 2325,   qty =  2, name = "Black Dye" },
            { id = 7071,   qty =  1, name = "Iron Buckle" },
        },
    },
    [4264] = { name = "Barbaric Belt", skill = 200, spec = nil,
        components = {
            { id = 4234,   qty =  6, name = "Heavy Leather" },
            { id = 4236,   qty =  2, name = "Cured Heavy Hide" },
            { id = 4096,   qty =  2, name = "Coarse Gorilla Hair" },
            { id = 5633,   qty =  1, name = "Great Rage Potion" },
            { id = 4291,   qty =  1, name = "Silken Thread" },
            { id = 7071,   qty =  1, name = "Iron Buckle" },
        },
    },
    [4304] = { name = "Thick Leather", skill = 200, spec = nil,
        components = {
            { id = 4234,   qty =  6, name = "Heavy Leather" },
        },
    },
    [7390] = { name = "Dusky Boots", skill = 200, spec = nil,
        components = {
            { id = 4234,   qty =  8, name = "Heavy Leather" },
            { id = 10285,  qty =  2, name = "Shadow Silk" },
            { id = 4291,   qty =  2, name = "Silken Thread" },
        },
    },
    [7391] = { name = "Swift Boots", skill = 200, spec = nil,
        components = {
            { id = 4234,   qty = 10, name = "Heavy Leather" },
            { id = 2459,   qty =  2, name = "Swiftness Potion" },
            { id = 4337,   qty =  2, name = "Thick Spider's Silk" },
            { id = 4291,   qty =  1, name = "Silken Thread" },
        },
    },
    [8172] = { name = "Cured Thick Hide", skill = 200, spec = nil,
        components = {
            { id = 8169,   qty =  1, name = "Thick Hide" },
            { id = 8150,   qty =  1, name = "Deeprock Salt" },
        },
    },
    [8173] = { name = "Thick Armor Kit", skill = 200, spec = nil,
        components = {
            { id = 4304,   qty =  5, name = "Thick Leather" },
            { id = 4291,   qty =  1, name = "Silken Thread" },
        },
    },
    [8174] = { name = "Comfortable Leather Hat", skill = 200, spec = nil,
        components = {
            { id = 4234,   qty = 12, name = "Heavy Leather" },
            { id = 4236,   qty =  2, name = "Cured Heavy Hide" },
            { id = 4291,   qty =  2, name = "Silken Thread" },
        },
    },
    [18238] = { name = "Shadowskin Gloves", skill = 200, spec = nil,
        components = {
            { id = 4304,   qty =  6, name = "Thick Leather" },
            { id = 10285,  qty =  8, name = "Shadow Silk" },
            { id = 4236,   qty =  4, name = "Cured Heavy Hide" },
            { id = 8343,   qty =  1, name = "Heavy Silken Thread" },
        },
    },
    [8175] = { name = "Nightscape Tunic", skill = 205, spec = nil,
        components = {
            { id = 4304,   qty =  7, name = "Thick Leather" },
            { id = 4291,   qty =  2, name = "Silken Thread" },
        },
    },
    [8176] = { name = "Nightscape Headband", skill = 205, spec = nil,
        components = {
            { id = 4304,   qty =  5, name = "Thick Leather" },
            { id = 4291,   qty =  2, name = "Silken Thread" },
        },
    },
    [8187] = { name = "Turtle Scale Gloves", skill = 205, spec = nil,
        components = {
            { id = 4304,   qty =  6, name = "Thick Leather" },
            { id = 8167,   qty =  8, name = "Turtle Scale" },
            { id = 8343,   qty =  1, name = "Heavy Silken Thread" },
        },
    },
    [8189] = { name = "Turtle Scale Breastplate", skill = 210, spec = nil,
        components = {
            { id = 4304,   qty =  6, name = "Thick Leather" },
            { id = 8167,   qty = 12, name = "Turtle Scale" },
            { id = 8343,   qty =  1, name = "Heavy Silken Thread" },
        },
    },
    [8192] = { name = "Nightscape Shoulders", skill = 210, spec = nil,
        components = {
            { id = 4304,   qty =  8, name = "Thick Leather" },
            { id = 4338,   qty =  6, name = "Mageweave Cloth" },
            { id = 4291,   qty =  3, name = "Silken Thread" },
        },
    },
    [8198] = { name = "Turtle Scale Bracers", skill = 210, spec = nil,
        components = {
            { id = 4304,   qty =  8, name = "Thick Leather" },
            { id = 8167,   qty = 12, name = "Turtle Scale" },
            { id = 8343,   qty =  1, name = "Heavy Silken Thread" },
        },
    },
    [8200] = { name = "Big Voodoo Robe", skill = 215, spec = nil,
        components = {
            { id = 4304,   qty = 10, name = "Thick Leather" },
            { id = 8151,   qty =  4, name = "Flask of Mojo" },
            { id = 8343,   qty =  1, name = "Heavy Silken Thread" },
        },
    },
    [8201] = { name = "Big Voodoo Mask", skill = 220, spec = nil,
        components = {
            { id = 4304,   qty =  8, name = "Thick Leather" },
            { id = 8151,   qty =  6, name = "Flask of Mojo" },
            { id = 8343,   qty =  1, name = "Heavy Silken Thread" },
        },
    },
    [8203] = { name = "Tough Scorpid Breastplate", skill = 220, spec = nil,
        components = {
            { id = 4304,   qty = 12, name = "Thick Leather" },
            { id = 8154,   qty = 12, name = "Scorpid Scale" },
            { id = 4291,   qty =  4, name = "Silken Thread" },
        },
    },
    [8205] = { name = "Tough Scorpid Bracers", skill = 220, spec = nil,
        components = {
            { id = 4304,   qty = 10, name = "Thick Leather" },
            { id = 8154,   qty =  4, name = "Scorpid Scale" },
            { id = 4291,   qty =  2, name = "Silken Thread" },
        },
    },
    [8210] = { name = "Wild Leather Shoulders", skill = 220, spec = nil,
        components = {
            { id = 4304,   qty = 10, name = "Thick Leather" },
            { id = 8153,   qty =  1, name = "Wildvine" },
            { id = 8172,   qty =  1, name = "Cured Thick Hide" },
        },
    },
    [8204] = { name = "Tough Scorpid Gloves", skill = 225, spec = nil,
        components = {
            { id = 4304,   qty =  6, name = "Thick Leather" },
            { id = 8154,   qty =  8, name = "Scorpid Scale" },
            { id = 4291,   qty =  2, name = "Silken Thread" },
        },
    },
    [8211] = { name = "Wild Leather Vest", skill = 225, spec = nil,
        components = {
            { id = 4304,   qty = 12, name = "Thick Leather" },
            { id = 8153,   qty =  2, name = "Wildvine" },
            { id = 8172,   qty =  1, name = "Cured Thick Hide" },
        },
    },
    [8214] = { name = "Wild Leather Helmet", skill = 225, spec = nil,
        components = {
            { id = 4304,   qty = 10, name = "Thick Leather" },
            { id = 8153,   qty =  2, name = "Wildvine" },
            { id = 8172,   qty =  1, name = "Cured Thick Hide" },
        },
    },
    [8217] = { name = "Quickdraw Quiver", skill = 225, spec = nil,
        components = {
            { id = 4304,   qty = 12, name = "Thick Leather" },
            { id = 8172,   qty =  1, name = "Cured Thick Hide" },
            { id = 8949,   qty =  1, name = "Elixir of Agility" },
            { id = 4291,   qty =  4, name = "Silken Thread" },
        },
    },
    [8218] = { name = "Thick Leather Ammo Pouch", skill = 225, spec = nil,
        components = {
            { id = 4304,   qty = 10, name = "Thick Leather" },
            { id = 8172,   qty =  1, name = "Cured Thick Hide" },
            { id = 8951,   qty =  1, name = "Elixir of Greater Defense" },
            { id = 4291,   qty =  6, name = "Silken Thread" },
        },
    },
    [8345] = { name = "Wolfshead Helm", skill = 225, spec = nil,
        components = {
            { id = 4304,   qty = 18, name = "Thick Leather" },
            { id = 8153,   qty = 12, name = "Wildvine" },
            { id = 8172,   qty =  4, name = "Cured Thick Hide" },
            { id = 8343,   qty =  1, name = "Heavy Silken Thread" },
        },
    },
    [8347] = { name = "Dragonscale Gauntlets", skill = 225, spec = nil,
        components = {
            { id = 4304,   qty = 24, name = "Thick Leather" },
            { id = 8165,   qty = 12, name = "Worn Dragonscale" },
            { id = 8343,   qty =  4, name = "Heavy Silken Thread" },
            { id = 8172,   qty =  2, name = "Cured Thick Hide" },
        },
    },
    [8191] = { name = "Turtle Scale Helm", skill = 230, spec = nil,
        components = {
            { id = 4304,   qty = 14, name = "Thick Leather" },
            { id = 8167,   qty = 24, name = "Turtle Scale" },
            { id = 8343,   qty =  1, name = "Heavy Silken Thread" },
        },
    },
    [8193] = { name = "Nightscape Pants", skill = 230, spec = nil,
        components = {
            { id = 4304,   qty = 14, name = "Thick Leather" },
            { id = 4291,   qty =  4, name = "Silken Thread" },
        },
    },
    [8346] = { name = "Gauntlets of the Sea", skill = 230, spec = nil,
        components = {
            { id = 4304,   qty = 20, name = "Thick Leather" },
            { id = 7079,   qty =  4, name = "Globe of Water" },
            { id = 8172,   qty =  1, name = "Cured Thick Hide" },
            { id = 8343,   qty =  4, name = "Heavy Silken Thread" },
        },
    },
    [8185] = { name = "Turtle Scale Leggings", skill = 235, spec = nil,
        components = {
            { id = 4304,   qty = 14, name = "Thick Leather" },
            { id = 8167,   qty = 28, name = "Turtle Scale" },
            { id = 8343,   qty =  1, name = "Heavy Silken Thread" },
        },
    },
    [8197] = { name = "Nightscape Boots", skill = 235, spec = nil,
        components = {
            { id = 4304,   qty = 16, name = "Thick Leather" },
            { id = 8343,   qty =  2, name = "Heavy Silken Thread" },
        },
    },
    [8209] = { name = "Tough Scorpid Boots", skill = 235, spec = nil,
        components = {
            { id = 4304,   qty = 12, name = "Thick Leather" },
            { id = 8154,   qty = 12, name = "Scorpid Scale" },
            { id = 4291,   qty =  6, name = "Silken Thread" },
        },
    },
    [8202] = { name = "Big Voodoo Pants", skill = 240, spec = nil,
        components = {
            { id = 4304,   qty = 10, name = "Thick Leather" },
            { id = 8152,   qty =  6, name = "Flask of Big Mojo" },
            { id = 8343,   qty =  2, name = "Heavy Silken Thread" },
        },
    },
    [8207] = { name = "Tough Scorpid Shoulders", skill = 240, spec = nil,
        components = {
            { id = 4304,   qty = 12, name = "Thick Leather" },
            { id = 8154,   qty = 16, name = "Scorpid Scale" },
            { id = 8343,   qty =  2, name = "Heavy Silken Thread" },
        },
    },
    [8216] = { name = "Big Voodoo Cloak", skill = 240, spec = nil,
        components = {
            { id = 4304,   qty = 14, name = "Thick Leather" },
            { id = 8152,   qty =  4, name = "Flask of Big Mojo" },
            { id = 8343,   qty =  2, name = "Heavy Silken Thread" },
        },
    },
    [8206] = { name = "Tough Scorpid Leggings", skill = 245, spec = nil,
        components = {
            { id = 4304,   qty = 14, name = "Thick Leather" },
            { id = 8154,   qty =  8, name = "Scorpid Scale" },
            { id = 8343,   qty =  2, name = "Heavy Silken Thread" },
        },
    },
    [8213] = { name = "Wild Leather Boots", skill = 245, spec = nil,
        components = {
            { id = 4304,   qty = 14, name = "Thick Leather" },
            { id = 8153,   qty =  4, name = "Wildvine" },
            { id = 8172,   qty =  2, name = "Cured Thick Hide" },
        },
    },
    [8170] = { name = "Rugged Leather", skill = 250, spec = nil,
        components = {
            { id = 4304,   qty =  6, name = "Thick Leather" },
        },
    },
    [8208] = { name = "Tough Scorpid Helm", skill = 250, spec = nil,
        components = {
            { id = 4304,   qty = 10, name = "Thick Leather" },
            { id = 8154,   qty = 20, name = "Scorpid Scale" },
            { id = 8343,   qty =  2, name = "Heavy Silken Thread" },
        },
    },
    [8212] = { name = "Wild Leather Leggings", skill = 250, spec = nil,
        components = {
            { id = 4304,   qty = 16, name = "Thick Leather" },
            { id = 8153,   qty =  6, name = "Wildvine" },
            { id = 8172,   qty =  2, name = "Cured Thick Hide" },
        },
    },
    [8215] = { name = "Wild Leather Cloak", skill = 250, spec = nil,
        components = {
            { id = 4304,   qty = 16, name = "Thick Leather" },
            { id = 8153,   qty =  6, name = "Wildvine" },
            { id = 8172,   qty =  2, name = "Cured Thick Hide" },
        },
    },
    [8348] = { name = "Helm of Fire", skill = 250, spec = nil,
        components = {
            { id = 4304,   qty = 30, name = "Thick Leather" },
            { id = 7077,   qty =  8, name = "Heart of Fire" },
            { id = 8172,   qty =  2, name = "Cured Thick Hide" },
            { id = 8343,   qty =  4, name = "Heavy Silken Thread" },
        },
    },
    [8349] = { name = "Feathered Breastplate", skill = 250, spec = nil,
        components = {
            { id = 4304,   qty = 25, name = "Thick Leather" },
            { id = 17056,  qty = 20, name = "Light Feather" },
            { id = 7971,   qty =  2, name = "Black Pearl" },
            { id = 8172,   qty =  4, name = "Cured Thick Hide" },
            { id = 8343,   qty =  4, name = "Heavy Silken Thread" },
        },
    },
    [15407] = { name = "Cured Rugged Hide", skill = 250, spec = nil,
        components = {
            { id = 8171,   qty =  1, name = "Rugged Hide" },
            { id = 15409,  qty =  1, name = "Refined Deeprock Salt" },
        },
    },
    [15564] = { name = "Rugged Armor Kit", skill = 250, spec = nil,
        components = {
            { id = 8170,   qty =  5, name = "Rugged Leather" },
        },
    },
    [8367] = { name = "Dragonscale Breastplate", skill = 255, spec = nil,
        components = {
            { id = 4304,   qty = 40, name = "Thick Leather" },
            { id = 8165,   qty = 30, name = "Worn Dragonscale" },
            { id = 8343,   qty =  4, name = "Heavy Silken Thread" },
            { id = 8172,   qty =  4, name = "Cured Thick Hide" },
        },
    },
    [15077] = { name = "Heavy Scorpid Bracers", skill = 255, spec = "Tribal",
        components = {
            { id = 8170,   qty =  4, name = "Rugged Leather" },
            { id = 15408,  qty =  4, name = "Heavy Scorpid Scale" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [15045] = { name = "Green Dragonscale Breastplate", skill = 260, spec = "Dragonscale",
        components = {
            { id = 8170,   qty = 20, name = "Rugged Leather" },
            { id = 15412,  qty = 25, name = "Green Dragonscale" },
            { id = 14341,  qty =  2, name = "Rune Thread" },
        },
    },
    [15083] = { name = "Wicked Leather Gauntlets", skill = 260, spec = "Tribal",
        components = {
            { id = 8170,   qty =  8, name = "Rugged Leather" },
            { id = 2325,   qty =  1, name = "Black Dye" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [15074] = { name = "Chimeric Gloves", skill = 265, spec = nil,
        components = {
            { id = 8170,   qty =  6, name = "Rugged Leather" },
            { id = 12803,  qty =  1, name = "Living Essence" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [15076] = { name = "Heavy Scorpid Vest", skill = 265, spec = nil,
        components = {
            { id = 8170,   qty =  6, name = "Rugged Leather" },
            { id = 15408,  qty =  6, name = "Heavy Scorpid Scale" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [15084] = { name = "Wicked Leather Bracers", skill = 265, spec = nil,
        components = {
            { id = 8170,   qty =  8, name = "Rugged Leather" },
            { id = 2325,   qty =  1, name = "Black Dye" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [15046] = { name = "Green Dragonscale Leggings", skill = 270, spec = nil,
        components = {
            { id = 8170,   qty = 20, name = "Rugged Leather" },
            { id = 15412,  qty = 25, name = "Green Dragonscale" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [15054] = { name = "Volcanic Leggings", skill = 270, spec = nil,
        components = {
            { id = 8170,   qty =  6, name = "Rugged Leather" },
            { id = 7078,   qty =  1, name = "Essence of Fire" },
            { id = 7075,   qty =  1, name = "Core of Earth" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [15061] = { name = "Living Shoulders", skill = 270, spec = nil,
        components = {
            { id = 8170,   qty = 12, name = "Rugged Leather" },
            { id = 12803,  qty =  4, name = "Living Essence" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [15067] = { name = "Ironfeather Shoulders", skill = 270, spec = "Elemental",
        components = {
            { id = 8170,   qty = 24, name = "Rugged Leather" },
            { id = 17056,  qty = 40, name = "Light Feather" },
            { id = 1529,   qty =  2, name = "Jade" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [15091] = { name = "Runic Leather Gauntlets", skill = 270, spec = nil,
        components = {
            { id = 8170,   qty = 10, name = "Rugged Leather" },
            { id = 14047,  qty =  6, name = "Runecloth" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [15057] = { name = "Stormshroud Pants", skill = 275, spec = nil,
        components = {
            { id = 8170,   qty = 16, name = "Rugged Leather" },
            { id = 7082,   qty =  2, name = "Essence of Air" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [15064] = { name = "Warbear Harness", skill = 275, spec = nil,
        components = {
            { id = 8170,   qty = 28, name = "Rugged Leather" },
            { id = 15419,  qty = 12, name = "Warbear Leather" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [15071] = { name = "Frostsaber Boots", skill = 275, spec = "Elemental",
        components = {
            { id = 8170,   qty =  4, name = "Rugged Leather" },
            { id = 7080,   qty =  1, name = "Essence of Water" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [15073] = { name = "Chimeric Boots", skill = 275, spec = "Tribal",
        components = {
            { id = 8170,   qty =  4, name = "Rugged Leather" },
            { id = 12803,  qty =  1, name = "Living Essence" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [15078] = { name = "Heavy Scorpid Gauntlets", skill = 275, spec = nil,
        components = {
            { id = 8170,   qty =  6, name = "Rugged Leather" },
            { id = 15408,  qty =  8, name = "Heavy Scorpid Scale" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [15092] = { name = "Runic Leather Bracers", skill = 275, spec = nil,
        components = {
            { id = 8170,   qty =  6, name = "Rugged Leather" },
            { id = 7971,   qty =  1, name = "Black Pearl" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [15072] = { name = "Chimeric Leggings", skill = 280, spec = nil,
        components = {
            { id = 8170,   qty =  8, name = "Rugged Leather" },
            { id = 12803,  qty =  1, name = "Living Essence" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [15082] = { name = "Heavy Scorpid Belt", skill = 280, spec = nil,
        components = {
            { id = 8170,   qty =  6, name = "Rugged Leather" },
            { id = 15408,  qty =  8, name = "Heavy Scorpid Scale" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [15086] = { name = "Wicked Leather Headband", skill = 280, spec = nil,
        components = {
            { id = 8170,   qty = 12, name = "Rugged Leather" },
            { id = 2325,   qty =  1, name = "Black Dye" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [15093] = { name = "Runic Leather Belt", skill = 280, spec = nil,
        components = {
            { id = 8170,   qty = 10, name = "Rugged Leather" },
            { id = 14047,  qty = 10, name = "Runecloth" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [20296] = { name = "Green Dragonscale Gauntlets", skill = 280, spec = nil,
        components = {
            { id = 8170,   qty = 20, name = "Rugged Leather" },
            { id = 15412,  qty = 30, name = "Green Dragonscale" },
            { id = 15407,  qty =  1, name = "Cured Rugged Hide" },
            { id = 14341,  qty =  2, name = "Rune Thread" },
        },
    },
    [15048] = { name = "Blue Dragonscale Breastplate", skill = 285, spec = nil,
        components = {
            { id = 8170,   qty = 28, name = "Rugged Leather" },
            { id = 15415,  qty = 30, name = "Blue Dragonscale" },
            { id = 15407,  qty =  1, name = "Cured Rugged Hide" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [15053] = { name = "Volcanic Breastplate", skill = 285, spec = "Dragonscale",
        components = {
            { id = 8170,   qty =  8, name = "Rugged Leather" },
            { id = 7078,   qty =  1, name = "Essence of Fire" },
            { id = 7076,   qty =  1, name = "Essence of Earth" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [15056] = { name = "Stormshroud Armor", skill = 285, spec = nil,
        components = {
            { id = 8170,   qty = 16, name = "Rugged Leather" },
            { id = 7082,   qty =  3, name = "Essence of Air" },
            { id = 15407,  qty =  1, name = "Cured Rugged Hide" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [15060] = { name = "Living Leggings", skill = 285, spec = nil,
        components = {
            { id = 8170,   qty = 16, name = "Rugged Leather" },
            { id = 12803,  qty =  6, name = "Living Essence" },
            { id = 15407,  qty =  1, name = "Cured Rugged Hide" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [15065] = { name = "Warbear Woolies", skill = 285, spec = "Elemental",
        components = {
            { id = 8170,   qty = 24, name = "Rugged Leather" },
            { id = 15419,  qty = 14, name = "Warbear Leather" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [15069] = { name = "Frostsaber Leggings", skill = 285, spec = "Elemental",
        components = {
            { id = 8170,   qty =  6, name = "Rugged Leather" },
            { id = 7080,   qty =  1, name = "Essence of Water" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [15079] = { name = "Heavy Scorpid Leggings", skill = 285, spec = "Tribal",
        components = {
            { id = 8170,   qty =  8, name = "Rugged Leather" },
            { id = 15408,  qty = 12, name = "Heavy Scorpid Scale" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [18258] = { name = "Gordok Ogre Suit", skill = 285, spec = nil,
        components = {
            { id = 8170,   qty =  4, name = "Rugged Leather" },
            { id = 14048,  qty =  2, name = "Bolt of Runecloth" },
            { id = 18240,  qty =  1, name = "Ogre Tannin" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [15050] = { name = "Black Dragonscale Breastplate", skill = 290, spec = nil,
        components = {
            { id = 8170,   qty = 25, name = "Rugged Leather" },
            { id = 15416,  qty = 25, name = "Black Dragonscale" },
            { id = 15407,  qty =  1, name = "Cured Rugged Hide" },
            { id = 14341,  qty =  2, name = "Rune Thread" },
        },
    },
    [15063] = { name = "Devilsaur Gauntlets", skill = 290, spec = "Elemental",
        components = {
            { id = 8170,   qty = 30, name = "Rugged Leather" },
            { id = 15417,  qty =  8, name = "Devilsaur Leather" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [15066] = { name = "Ironfeather Breastplate", skill = 290, spec = nil,
        components = {
            { id = 8170,   qty = 35, name = "Rugged Leather" },
            { id = 17056,  qty = 40, name = "Light Feather" },
            { id = 1529,   qty =  1, name = "Jade" },
            { id = 15407,  qty =  1, name = "Cured Rugged Hide" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [15075] = { name = "Chimeric Vest", skill = 290, spec = "Tribal",
        components = {
            { id = 8170,   qty = 10, name = "Rugged Leather" },
            { id = 12803,  qty =  1, name = "Living Essence" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [15087] = { name = "Wicked Leather Pants", skill = 290, spec = nil,
        components = {
            { id = 8170,   qty = 12, name = "Rugged Leather" },
            { id = 15407,  qty =  1, name = "Cured Rugged Hide" },
            { id = 2325,   qty =  3, name = "Black Dye" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [15094] = { name = "Runic Leather Headband", skill = 290, spec = nil,
        components = {
            { id = 8170,   qty = 14, name = "Rugged Leather" },
            { id = 14047,  qty = 10, name = "Runecloth" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [19044] = { name = "Might of the Timbermaw", skill = 290, spec = nil,
        components = {
            { id = 8170,   qty = 30, name = "Rugged Leather" },
            { id = 12803,  qty =  4, name = "Living Essence" },
            { id = 15407,  qty =  2, name = "Cured Rugged Hide" },
            { id = 14341,  qty =  2, name = "Rune Thread" },
        },
    },
    [19052] = { name = "Dawn Treaders", skill = 290, spec = nil,
        components = {
            { id = 8170,   qty = 30, name = "Rugged Leather" },
            { id = 12809,  qty =  2, name = "Guardian Stone" },
            { id = 7080,   qty =  4, name = "Essence of Water" },
            { id = 15407,  qty =  2, name = "Cured Rugged Hide" },
            { id = 14341,  qty =  2, name = "Rune Thread" },
        },
    },
    [15049] = { name = "Blue Dragonscale Shoulders", skill = 295, spec = "Dragonscale",
        components = {
            { id = 8170,   qty = 28, name = "Rugged Leather" },
            { id = 15415,  qty = 30, name = "Blue Dragonscale" },
            { id = 12810,  qty =  2, name = "Enchanted Leather" },
            { id = 15407,  qty =  1, name = "Cured Rugged Hide" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [15058] = { name = "Stormshroud Shoulders", skill = 295, spec = nil,
        components = {
            { id = 8170,   qty = 12, name = "Rugged Leather" },
            { id = 7082,   qty =  3, name = "Essence of Air" },
            { id = 14227,  qty =  2, name = "Ironweb Spider Silk" },
        },
    },
    [15070] = { name = "Frostsaber Gloves", skill = 295, spec = nil,
        components = {
            { id = 8170,   qty =  6, name = "Rugged Leather" },
            { id = 7080,   qty =  1, name = "Essence of Water" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [15080] = { name = "Heavy Scorpid Helm", skill = 295, spec = nil,
        components = {
            { id = 8170,   qty =  8, name = "Rugged Leather" },
            { id = 15408,  qty = 12, name = "Heavy Scorpid Scale" },
            { id = 15407,  qty =  1, name = "Cured Rugged Hide" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [16982] = { name = "Corehound Boots", skill = 295, spec = nil,
        components = {
            { id = 17012,  qty = 20, name = "Core Leather" },
            { id = 17010,  qty =  6, name = "Fiery Core" },
            { id = 17011,  qty =  2, name = "Lava Core" },
            { id = 14341,  qty =  2, name = "Rune Thread" },
        },
    },
    [15047] = { name = "Red Dragonscale Breastplate", skill = 300, spec = "Dragonscale",
        components = {
            { id = 8170,   qty = 40, name = "Rugged Leather" },
            { id = 15414,  qty = 30, name = "Red Dragonscale" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [15051] = { name = "Black Dragonscale Shoulders", skill = 300, spec = "Dragonscale",
        components = {
            { id = 8170,   qty = 20, name = "Rugged Leather" },
            { id = 15416,  qty = 15, name = "Black Dragonscale" },
            { id = 15407,  qty =  1, name = "Cured Rugged Hide" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [15052] = { name = "Black Dragonscale Leggings", skill = 300, spec = nil,
        components = {
            { id = 8170,   qty = 25, name = "Rugged Leather" },
            { id = 15416,  qty = 25, name = "Black Dragonscale" },
            { id = 15407,  qty =  1, name = "Cured Rugged Hide" },
            { id = 14341,  qty =  2, name = "Rune Thread" },
        },
    },
    [15055] = { name = "Volcanic Shoulders", skill = 300, spec = "Dragonscale",
        components = {
            { id = 8170,   qty = 10, name = "Rugged Leather" },
            { id = 7078,   qty =  1, name = "Essence of Fire" },
            { id = 7076,   qty =  1, name = "Essence of Earth" },
            { id = 14341,  qty =  2, name = "Rune Thread" },
        },
    },
    [15059] = { name = "Living Breastplate", skill = 300, spec = nil,
        components = {
            { id = 8170,   qty = 16, name = "Rugged Leather" },
            { id = 12803,  qty =  8, name = "Living Essence" },
            { id = 14342,  qty =  2, name = "Mooncloth" },
            { id = 15407,  qty =  1, name = "Cured Rugged Hide" },
            { id = 14341,  qty =  2, name = "Rune Thread" },
        },
    },
    [15062] = { name = "Devilsaur Leggings", skill = 300, spec = nil,
        components = {
            { id = 8170,   qty = 30, name = "Rugged Leather" },
            { id = 15417,  qty = 14, name = "Devilsaur Leather" },
            { id = 15407,  qty =  1, name = "Cured Rugged Hide" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [15068] = { name = "Frostsaber Tunic", skill = 300, spec = nil,
        components = {
            { id = 8170,   qty = 12, name = "Rugged Leather" },
            { id = 7080,   qty =  1, name = "Essence of Water" },
            { id = 15407,  qty =  1, name = "Cured Rugged Hide" },
            { id = 14341,  qty =  2, name = "Rune Thread" },
        },
    },
    [15081] = { name = "Heavy Scorpid Shoulders", skill = 300, spec = "Tribal",
        components = {
            { id = 8170,   qty = 14, name = "Rugged Leather" },
            { id = 15408,  qty = 14, name = "Heavy Scorpid Scale" },
            { id = 15407,  qty =  1, name = "Cured Rugged Hide" },
            { id = 14341,  qty =  2, name = "Rune Thread" },
        },
    },
    [15085] = { name = "Wicked Leather Armor", skill = 300, spec = "Tribal",
        components = {
            { id = 8170,   qty = 20, name = "Rugged Leather" },
            { id = 15407,  qty =  2, name = "Cured Rugged Hide" },
            { id = 14256,  qty =  2, name = "Felcloth" },
            { id = 2325,   qty =  4, name = "Black Dye" },
            { id = 14341,  qty =  2, name = "Rune Thread" },
        },
    },
    [15088] = { name = "Wicked Leather Belt", skill = 300, spec = nil,
        components = {
            { id = 8170,   qty = 14, name = "Rugged Leather" },
            { id = 2325,   qty =  2, name = "Black Dye" },
            { id = 14341,  qty =  2, name = "Rune Thread" },
        },
    },
    [15090] = { name = "Runic Leather Armor", skill = 300, spec = nil,
        components = {
            { id = 8170,   qty = 22, name = "Rugged Leather" },
            { id = 12810,  qty =  4, name = "Enchanted Leather" },
            { id = 14047,  qty = 16, name = "Runecloth" },
            { id = 15407,  qty =  1, name = "Cured Rugged Hide" },
            { id = 14341,  qty =  2, name = "Rune Thread" },
        },
    },
    [15095] = { name = "Runic Leather Pants", skill = 300, spec = nil,
        components = {
            { id = 8170,   qty = 18, name = "Rugged Leather" },
            { id = 14047,  qty = 12, name = "Runecloth" },
            { id = 12810,  qty =  2, name = "Enchanted Leather" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [15096] = { name = "Runic Leather Shoulders", skill = 300, spec = nil,
        components = {
            { id = 8170,   qty = 16, name = "Rugged Leather" },
            { id = 12810,  qty =  4, name = "Enchanted Leather" },
            { id = 14047,  qty = 18, name = "Runecloth" },
            { id = 15407,  qty =  1, name = "Cured Rugged Hide" },
            { id = 14341,  qty =  2, name = "Rune Thread" },
        },
    },
    [15138] = { name = "Onyxia Scale Cloak", skill = 300, spec = nil,
        components = {
            { id = 15410,  qty =  1, name = "Scale of Onyxia" },
            { id = 14044,  qty =  1, name = "Cindercloth Cloak" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [16983] = { name = "Molten Helm", skill = 300, spec = nil,
        components = {
            { id = 17012,  qty = 12, name = "Core Leather" },
            { id = 17010,  qty =  3, name = "Fiery Core" },
            { id = 17011,  qty =  3, name = "Lava Core" },
            { id = 14341,  qty =  2, name = "Rune Thread" },
        },
    },
    [16984] = { name = "Black Dragonscale Boots", skill = 300, spec = nil,
        components = {
            { id = 15416,  qty = 18, name = "Black Dragonscale" },
            { id = 17010,  qty =  3, name = "Fiery Core" },
            { id = 17011,  qty =  3, name = "Lava Core" },
            { id = 14341,  qty =  2, name = "Rune Thread" },
        },
    },
    [18251] = { name = "Core Armor Kit", skill = 300, spec = nil,
        components = {
            { id = 17012,  qty =  3, name = "Core Leather" },
            { id = 14341,  qty =  2, name = "Rune Thread" },
        },
    },
    [18504] = { name = "Girdle of Insight", skill = 300, spec = nil,
        components = {
            { id = 8170,   qty = 12, name = "Rugged Leather" },
            { id = 12804,  qty = 12, name = "Powerful Mojo" },
            { id = 15407,  qty =  2, name = "Cured Rugged Hide" },
            { id = 14341,  qty =  4, name = "Rune Thread" },
        },
    },
    [18506] = { name = "Mongoose Boots", skill = 300, spec = nil,
        components = {
            { id = 8170,   qty = 12, name = "Rugged Leather" },
            { id = 7082,   qty =  6, name = "Essence of Air" },
            { id = 11754,  qty =  4, name = "Black Diamond" },
            { id = 15407,  qty =  2, name = "Cured Rugged Hide" },
            { id = 14341,  qty =  4, name = "Rune Thread" },
        },
    },
    [18508] = { name = "Swift Flight Bracers", skill = 300, spec = nil,
        components = {
            { id = 8170,   qty = 12, name = "Rugged Leather" },
            { id = 18512,  qty =  8, name = "Larval Acid" },
            { id = 15407,  qty =  4, name = "Cured Rugged Hide" },
            { id = 14341,  qty =  4, name = "Rune Thread" },
        },
    },
    [18509] = { name = "Chromatic Cloak", skill = 300, spec = nil,
        components = {
            { id = 8170,   qty = 25, name = "Rugged Leather" },
            { id = 12607,  qty =  4, name = "Brilliant Chromatic Scale" },
            { id = 15416,  qty = 12, name = "Black Dragonscale" },
            { id = 15414,  qty = 12, name = "Red Dragonscale" },
            { id = 14341,  qty =  2, name = "Rune Thread" },
        },
    },
    [18510] = { name = "Hide of the Wild", skill = 300, spec = nil,
        components = {
            { id = 8170,   qty = 30, name = "Rugged Leather" },
            { id = 18512,  qty =  5, name = "Larval Acid" },
            { id = 15407,  qty =  2, name = "Cured Rugged Hide" },
            { id = 14341,  qty =  2, name = "Rune Thread" },
        },
    },
    [18511] = { name = "Shifting Cloak", skill = 300, spec = nil,
        components = {
            { id = 12810,  qty = 10, name = "Enchanted Leather" },
            { id = 12753,  qty =  2, name = "Skin of Shadow" },
            { id = 14341,  qty =  1, name = "Rune Thread" },
        },
    },
    [19049] = { name = "Timbermaw Brawlers", skill = 300, spec = nil,
        components = {
            { id = 12810,  qty =  8, name = "Enchanted Leather" },
            { id = 12804,  qty =  6, name = "Powerful Mojo" },
            { id = 12803,  qty =  6, name = "Living Essence" },
            { id = 15407,  qty =  2, name = "Cured Rugged Hide" },
            { id = 14227,  qty =  2, name = "Ironweb Spider Silk" },
        },
    },
    [19058] = { name = "Golden Mantle of the Dawn", skill = 300, spec = nil,
        components = {
            { id = 12810,  qty =  8, name = "Enchanted Leather" },
            { id = 12803,  qty =  4, name = "Living Essence" },
            { id = 12809,  qty =  4, name = "Guardian Stone" },
            { id = 15407,  qty =  2, name = "Cured Rugged Hide" },
            { id = 14341,  qty =  2, name = "Rune Thread" },
        },
    },
    [19149] = { name = "Lava Belt", skill = 300, spec = nil,
        components = {
            { id = 17011,  qty =  2, name = "Lava Core" },
            { id = 17012,  qty =  2, name = "Core Leather" },
            { id = 14227,  qty =  4, name = "Ironweb Spider Silk" },
        },
    },
    [19157] = { name = "Chromatic Gauntlets", skill = 300, spec = nil,
        components = {
            { id = 17010,  qty =  3, name = "Fiery Core" },
            { id = 17011,  qty =  2, name = "Lava Core" },
            { id = 17012,  qty =  8, name = "Core Leather" },
            { id = 14227,  qty =  4, name = "Ironweb Spider Silk" },
        },
    },
    [19162] = { name = "Corehound Belt", skill = 300, spec = nil,
        components = {
            { id = 17010,  qty =  4, name = "Fiery Core" },
            { id = 17012,  qty = 12, name = "Core Leather" },
            { id = 8170,   qty = 12, name = "Rugged Leather" },
            { id = 14227,  qty =  4, name = "Ironweb Spider Silk" },
        },
    },
    [19163] = { name = "Molten Belt", skill = 300, spec = nil,
        components = {
            { id = 17010,  qty =  2, name = "Fiery Core" },
            { id = 17011,  qty =  2, name = "Lava Core" },
            { id = 17012,  qty =  2, name = "Core Leather" },
            { id = 14227,  qty =  4, name = "Ironweb Spider Silk" },
        },
    },
    [19685] = { name = "Primal Batskin Jerkin", skill = 300, spec = nil,
        components = {
            { id = 19767,  qty = 14, name = "Primal Bat Leather" },
            { id = 15407,  qty =  5, name = "Cured Rugged Hide" },
            { id = 12803,  qty =  4, name = "Living Essence" },
            { id = 14341,  qty =  4, name = "Rune Thread" },
        },
    },
    [19686] = { name = "Primal Batskin Gloves", skill = 300, spec = nil,
        components = {
            { id = 19767,  qty = 10, name = "Primal Bat Leather" },
            { id = 15407,  qty =  4, name = "Cured Rugged Hide" },
            { id = 12803,  qty =  4, name = "Living Essence" },
            { id = 14341,  qty =  3, name = "Rune Thread" },
        },
    },
    [19687] = { name = "Primal Batskin Bracers", skill = 300, spec = nil,
        components = {
            { id = 19767,  qty =  8, name = "Primal Bat Leather" },
            { id = 15407,  qty =  3, name = "Cured Rugged Hide" },
            { id = 12803,  qty =  4, name = "Living Essence" },
            { id = 14341,  qty =  3, name = "Rune Thread" },
        },
    },
    [19688] = { name = "Blood Tiger Breastplate", skill = 300, spec = nil,
        components = {
            { id = 19768,  qty = 25, name = "Primal Tiger Leather" },
            { id = 15407,  qty =  3, name = "Cured Rugged Hide" },
            { id = 14341,  qty =  3, name = "Rune Thread" },
        },
    },
    [19689] = { name = "Blood Tiger Shoulders", skill = 300, spec = nil,
        components = {
            { id = 19768,  qty = 25, name = "Primal Tiger Leather" },
            { id = 15407,  qty =  3, name = "Cured Rugged Hide" },
            { id = 14341,  qty =  3, name = "Rune Thread" },
        },
    },
    [20295] = { name = "Blue Dragonscale Leggings", skill = 300, spec = nil,
        components = {
            { id = 8170,   qty = 28, name = "Rugged Leather" },
            { id = 15415,  qty = 36, name = "Blue Dragonscale" },
            { id = 15407,  qty =  2, name = "Cured Rugged Hide" },
            { id = 14341,  qty =  2, name = "Rune Thread" },
        },
    },
    [20380] = { name = "Dreamscale Breastplate", skill = 300, spec = nil,
        components = {
            { id = 8170,   qty = 20, name = "Rugged Leather" },
            { id = 20381,  qty =  3, name = "Dreamscale" },
            { id = 12803,  qty =  3, name = "Living Essence" },
            { id = 14341,  qty =  2, name = "Rune Thread" },
        },
    },
    [20476] = { name = "Sandstalker Bracers", skill = 300, spec = nil,
        components = {
            { id = 20501,  qty =  1, name = "Heavy Silithid Carapace" },
            { id = 20498,  qty = 20, name = "Silithid Chitin" },
            { id = 18512,  qty =  2, name = "Larval Acid" },
        },
    },
    [20477] = { name = "Sandstalker Gauntlets", skill = 300, spec = nil,
        components = {
            { id = 20501,  qty =  2, name = "Heavy Silithid Carapace" },
            { id = 20498,  qty = 30, name = "Silithid Chitin" },
            { id = 18512,  qty =  2, name = "Larval Acid" },
            { id = 15407,  qty =  1, name = "Cured Rugged Hide" },
        },
    },
    [20478] = { name = "Sandstalker Breastplate", skill = 300, spec = nil,
        components = {
            { id = 20501,  qty =  3, name = "Heavy Silithid Carapace" },
            { id = 20498,  qty = 40, name = "Silithid Chitin" },
            { id = 18512,  qty =  2, name = "Larval Acid" },
            { id = 15407,  qty =  2, name = "Cured Rugged Hide" },
        },
    },
    [20479] = { name = "Spitfire Breastplate", skill = 300, spec = nil,
        components = {
            { id = 20500,  qty =  3, name = "Light Silithid Carapace" },
            { id = 20498,  qty = 40, name = "Silithid Chitin" },
            { id = 7078,   qty =  2, name = "Essence of Fire" },
            { id = 15407,  qty =  2, name = "Cured Rugged Hide" },
        },
    },
    [20480] = { name = "Spitfire Gauntlets", skill = 300, spec = nil,
        components = {
            { id = 20500,  qty =  2, name = "Light Silithid Carapace" },
            { id = 20498,  qty = 30, name = "Silithid Chitin" },
            { id = 7078,   qty =  2, name = "Essence of Fire" },
            { id = 15407,  qty =  1, name = "Cured Rugged Hide" },
        },
    },
    [20481] = { name = "Spitfire Bracers", skill = 300, spec = nil,
        components = {
            { id = 20500,  qty =  1, name = "Light Silithid Carapace" },
            { id = 20498,  qty = 20, name = "Silithid Chitin" },
            { id = 7078,   qty =  2, name = "Essence of Fire" },
        },
    },
    [21278] = { name = "Stormshroud Gloves", skill = 300, spec = nil,
        components = {
            { id = 12810,  qty =  6, name = "Enchanted Leather" },
            { id = 7082,   qty =  4, name = "Essence of Air" },
            { id = 14227,  qty =  2, name = "Ironweb Spider Silk" },
        },
    },
    [22661] = { name = "Polar Tunic", skill = 300, spec = nil,
        components = {
            { id = 22682,  qty =  7, name = "Frozen Rune" },
            { id = 12810,  qty = 16, name = "Enchanted Leather" },
            { id = 7080,   qty =  2, name = "Essence of Water" },
            { id = 15407,  qty =  4, name = "Cured Rugged Hide" },
            { id = 14227,  qty =  4, name = "Ironweb Spider Silk" },
        },
    },
    [22662] = { name = "Polar Gloves", skill = 300, spec = nil,
        components = {
            { id = 22682,  qty =  5, name = "Frozen Rune" },
            { id = 12810,  qty = 12, name = "Enchanted Leather" },
            { id = 7080,   qty =  2, name = "Essence of Water" },
            { id = 15407,  qty =  3, name = "Cured Rugged Hide" },
            { id = 14227,  qty =  4, name = "Ironweb Spider Silk" },
        },
    },
    [22663] = { name = "Polar Bracers", skill = 300, spec = nil,
        components = {
            { id = 22682,  qty =  4, name = "Frozen Rune" },
            { id = 12810,  qty = 12, name = "Enchanted Leather" },
            { id = 7080,   qty =  2, name = "Essence of Water" },
            { id = 15407,  qty =  2, name = "Cured Rugged Hide" },
            { id = 14227,  qty =  4, name = "Ironweb Spider Silk" },
        },
    },
    [22664] = { name = "Icy Scale Breastplate", skill = 300, spec = nil,
        components = {
            { id = 22682,  qty =  7, name = "Frozen Rune" },
            { id = 15408,  qty = 24, name = "Heavy Scorpid Scale" },
            { id = 7080,   qty =  2, name = "Essence of Water" },
            { id = 15407,  qty =  4, name = "Cured Rugged Hide" },
            { id = 14227,  qty =  4, name = "Ironweb Spider Silk" },
        },
    },
    [22665] = { name = "Icy Scale Bracers", skill = 300, spec = nil,
        components = {
            { id = 22682,  qty =  4, name = "Frozen Rune" },
            { id = 15408,  qty = 16, name = "Heavy Scorpid Scale" },
            { id = 7080,   qty =  2, name = "Essence of Water" },
            { id = 15407,  qty =  2, name = "Cured Rugged Hide" },
            { id = 14227,  qty =  4, name = "Ironweb Spider Silk" },
        },
    },
    [22666] = { name = "Icy Scale Gauntlets", skill = 300, spec = "Tribal",
        components = {
            { id = 22682,  qty =  5, name = "Frozen Rune" },
            { id = 15408,  qty = 16, name = "Heavy Scorpid Scale" },
            { id = 7080,   qty =  2, name = "Essence of Water" },
            { id = 15407,  qty =  3, name = "Cured Rugged Hide" },
            { id = 14227,  qty =  4, name = "Ironweb Spider Silk" },
        },
    },
    [22759] = { name = "Bramblewood Helm", skill = 300, spec = nil,
        components = {
            { id = 8170,   qty = 12, name = "Rugged Leather" },
            { id = 19726,  qty =  2, name = "Bloodvine" },
            { id = 12803,  qty =  2, name = "Living Essence" },
            { id = 15407,  qty =  2, name = "Cured Rugged Hide" },
        },
    },
    [22760] = { name = "Bramblewood Boots", skill = 300, spec = nil,
        components = {
            { id = 12810,  qty =  6, name = "Enchanted Leather" },
            { id = 18512,  qty =  2, name = "Larval Acid" },
            { id = 12803,  qty =  2, name = "Living Essence" },
            { id = 15407,  qty =  2, name = "Cured Rugged Hide" },
        },
    },
    [22761] = { name = "Bramblewood Belt", skill = 300, spec = nil,
        components = {
            { id = 12810,  qty =  4, name = "Enchanted Leather" },
            { id = 12803,  qty =  2, name = "Living Essence" },
            { id = 15407,  qty =  1, name = "Cured Rugged Hide" },
        },
    },
}