-- Engineering recipes — Source: database JSON
-- WoW Classic Era (Interface 11508)

ProfTooltip_Engineering = {

    [4357] = { name = "Rough Blasting Powder", skill = 1, spec = nil,
        components = {
            { id = 2835,   qty =  1, name = "Rough Stone" },
        },
    },
    [4358] = { name = "Rough Dynamite", skill = 1, spec = nil,
        components = {
            { id = 4357,   qty =  2, name = "Rough Blasting Powder" },
            { id = 2589,   qty =  1, name = "Linen Cloth" },
        },
    },
    [4359] = { name = "Handful of Copper Bolts", skill = 30, spec = nil,
        components = {
            { id = 2840,   qty =  1, name = "Copper Bar" },
        },
    },
    [4360] = { name = "Rough Copper Bomb", skill = 30, spec = nil,
        components = {
            { id = 2840,   qty =  1, name = "Copper Bar" },
            { id = 4359,   qty =  1, name = "Handful of Copper Bolts" },
            { id = 4357,   qty =  2, name = "Rough Blasting Powder" },
            { id = 2589,   qty =  1, name = "Linen Cloth" },
        },
    },
    [8067] = { name = "Crafted Light Shot", skill = 30, spec = nil,
        components = {
            { id = 4357,   qty =  1, name = "Rough Blasting Powder" },
            { id = 2840,   qty =  1, name = "Copper Bar" },
        },
    },
    [4361] = { name = "Copper Tube", skill = 50, spec = nil,
        components = {
            { id = 2840,   qty =  2, name = "Copper Bar" },
            { id = 2880,   qty =  1, name = "Weak Flux" },
        },
    },
    [4362] = { name = "Rough Boomstick", skill = 50, spec = nil,
        components = {
            { id = 4361,   qty =  1, name = "Copper Tube" },
            { id = 4359,   qty =  1, name = "Handful of Copper Bolts" },
            { id = 4399,   qty =  1, name = "Wooden Stock" },
        },
    },
    [6219] = { name = "Arclight Spanner", skill = 50, spec = nil,
        components = {
            { id = 2840,   qty =  6, name = "Copper Bar" },
        },
    },
    [4405] = { name = "Crude Scope", skill = 60, spec = nil,
        components = {
            { id = 4361,   qty =  1, name = "Copper Tube" },
            { id = 774,    qty =  1, name = "Malachite" },
            { id = 4359,   qty =  1, name = "Handful of Copper Bolts" },
        },
    },
    [4363] = { name = "Copper Modulator", skill = 65, spec = nil,
        components = {
            { id = 4359,   qty =  2, name = "Handful of Copper Bolts" },
            { id = 2840,   qty =  1, name = "Copper Bar" },
            { id = 2589,   qty =  2, name = "Linen Cloth" },
        },
    },
    [4364] = { name = "Coarse Blasting Powder", skill = 75, spec = nil,
        components = {
            { id = 2836,   qty =  1, name = "Coarse Stone" },
        },
    },
    [4365] = { name = "Coarse Dynamite", skill = 75, spec = nil,
        components = {
            { id = 4364,   qty =  3, name = "Coarse Blasting Powder" },
            { id = 2589,   qty =  1, name = "Linen Cloth" },
        },
    },
    [4401] = { name = "Mechanical Squirrel Box", skill = 75, spec = nil,
        components = {
            { id = 4363,   qty =  1, name = "Copper Modulator" },
            { id = 4359,   qty =  1, name = "Handful of Copper Bolts" },
            { id = 2840,   qty =  1, name = "Copper Bar" },
            { id = 774,    qty =  2, name = "Malachite" },
        },
    },
    [8068] = { name = "Crafted Heavy Shot", skill = 75, spec = nil,
        components = {
            { id = 4364,   qty =  1, name = "Coarse Blasting Powder" },
            { id = 2840,   qty =  1, name = "Copper Bar" },
        },
    },
    [4366] = { name = "Target Dummy", skill = 85, spec = nil,
        components = {
            { id = 4363,   qty =  1, name = "Copper Modulator" },
            { id = 4359,   qty =  2, name = "Handful of Copper Bolts" },
            { id = 2841,   qty =  1, name = "Tin Bar" },
            { id = 2592,   qty =  1, name = "Wool Cloth" },
        },
    },
    [4404] = { name = "Silver Contact", skill = 90, spec = nil,
        components = {
            { id = 2842,   qty =  1, name = "Silver Bar" },
        },
    },
    [4367] = { name = "Small Seaforium Charge", skill = 100, spec = nil,
        components = {
            { id = 4364,   qty =  2, name = "Coarse Blasting Powder" },
            { id = 4363,   qty =  1, name = "Copper Modulator" },
            { id = 2318,   qty =  1, name = "Light Leather" },
            { id = 159,    qty =  1, name = "Refreshing Spring Water" },
        },
    },
    [4368] = { name = "Flying Tiger Goggles", skill = 100, spec = nil,
        components = {
            { id = 2318,   qty =  6, name = "Light Leather" },
            { id = 818,    qty =  2, name = "Malachite" },
        },
    },
    [6712] = { name = "Practice Lock", skill = 100, spec = nil,
        components = {
            { id = 2841,   qty =  1, name = "Tin Bar" },
            { id = 4359,   qty =  2, name = "Handful of Copper Bolts" },
            { id = 2880,   qty =  1, name = "Weak Flux" },
        },
    },
    [6714] = { name = "Ez-Thro Dynamite", skill = 100, spec = nil,
        components = {
            { id = 4364,   qty =  4, name = "Coarse Blasting Powder" },
            { id = 2592,   qty =  1, name = "Wool Cloth" },
        },
    },
    [4369] = { name = "Deadly Blunderbuss", skill = 105, spec = nil,
        components = {
            { id = 4361,   qty =  2, name = "Copper Tube" },
            { id = 4359,   qty =  4, name = "Handful of Copper Bolts" },
            { id = 4399,   qty =  1, name = "Wooden Stock" },
            { id = 2319,   qty =  2, name = "Medium Leather" },
        },
    },
    [4370] = { name = "Large Copper Bomb", skill = 105, spec = nil,
        components = {
            { id = 2840,   qty =  3, name = "Copper Bar" },
            { id = 4364,   qty =  4, name = "Coarse Blasting Powder" },
            { id = 4404,   qty =  1, name = "Silver Contact" },
        },
    },
    [4371] = { name = "Bronze Tube", skill = 105, spec = nil,
        components = {
            { id = 2841,   qty =  2, name = "Tin Bar" },
            { id = 2880,   qty =  1, name = "Weak Flux" },
        },
    },
    [4406] = { name = "Standard Scope", skill = 110, spec = nil,
        components = {
            { id = 4371,   qty =  1, name = "Bronze Tube" },
            { id = 1206,   qty =  1, name = "Moss Agate" },
        },
    },
    [4372] = { name = "Lovingly Crafted Boomstick", skill = 120, spec = nil,
        components = {
            { id = 4371,   qty =  2, name = "Bronze Tube" },
            { id = 4359,   qty =  2, name = "Handful of Copper Bolts" },
            { id = 4400,   qty =  1, name = "Heavy Stock" },
            { id = 1206,   qty =  3, name = "Moss Agate" },
        },
    },
    [4373] = { name = "Shadow Goggles", skill = 120, spec = nil,
        components = {
            { id = 2319,   qty =  4, name = "Medium Leather" },
            { id = 1210,   qty =  2, name = "Tigerseye" },
        },
    },
    [4374] = { name = "Small Bronze Bomb", skill = 120, spec = nil,
        components = {
            { id = 4364,   qty =  4, name = "Coarse Blasting Powder" },
            { id = 2841,   qty =  2, name = "Tin Bar" },
            { id = 4404,   qty =  1, name = "Silver Contact" },
            { id = 2592,   qty =  1, name = "Wool Cloth" },
        },
    },
    [4375] = { name = "Whirring Bronze Gizmo", skill = 125, spec = nil,
        components = {
            { id = 2841,   qty =  2, name = "Tin Bar" },
            { id = 2592,   qty =  1, name = "Wool Cloth" },
        },
    },
    [4376] = { name = "Flame Deflector", skill = 125, spec = nil,
        components = {
            { id = 4375,   qty =  1, name = "Whirring Bronze Gizmo" },
            { id = 4402,   qty =  1, name = "Small Flame Sac" },
        },
    },
    [4377] = { name = "Heavy Blasting Powder", skill = 125, spec = nil,
        components = {
            { id = 2838,   qty =  1, name = "Heavy Stone" },
        },
    },
    [4378] = { name = "Heavy Dynamite", skill = 125, spec = nil,
        components = {
            { id = 4377,   qty =  2, name = "Heavy Blasting Powder" },
            { id = 2592,   qty =  1, name = "Wool Cloth" },
        },
    },
    [7506] = { name = "Gnomish Universal Remote", skill = 125, spec = "Gnomish",
        components = {
            { id = 2841,   qty =  6, name = "Tin Bar" },
            { id = 4375,   qty =  1, name = "Whirring Bronze Gizmo" },
            { id = 814,    qty =  2, name = "Flask of Oil" },
            { id = 818,    qty =  1, name = "Malachite" },
            { id = 774,    qty =  1, name = "Malachite" },
        },
    },
    [8069] = { name = "Crafted Solid Shot", skill = 125, spec = nil,
        components = {
            { id = 4377,   qty =  1, name = "Heavy Blasting Powder" },
            { id = 2841,   qty =  1, name = "Tin Bar" },
        },
    },
    [21557] = { name = "Small Red Rocket", skill = 125, spec = nil,
        components = {
            { id = 4364,   qty =  1, name = "Coarse Blasting Powder" },
            { id = 2319,   qty =  1, name = "Medium Leather" },
        },
    },
    [21558] = { name = "Small Blue Rocket", skill = 125, spec = nil,
        components = {
            { id = 4364,   qty =  1, name = "Coarse Blasting Powder" },
            { id = 2319,   qty =  1, name = "Medium Leather" },
        },
    },
    [21559] = { name = "Small Green Rocket", skill = 125, spec = nil,
        components = {
            { id = 4364,   qty =  1, name = "Coarse Blasting Powder" },
            { id = 2319,   qty =  1, name = "Medium Leather" },
        },
    },
    [4379] = { name = "Silver-plated Shotgun", skill = 130, spec = nil,
        components = {
            { id = 4371,   qty =  2, name = "Bronze Tube" },
            { id = 4375,   qty =  2, name = "Whirring Bronze Gizmo" },
            { id = 4400,   qty =  1, name = "Heavy Stock" },
            { id = 2842,   qty =  3, name = "Silver Bar" },
        },
    },
    [5507] = { name = "Ornate Spyglass", skill = 135, spec = nil,
        components = {
            { id = 4371,   qty =  2, name = "Bronze Tube" },
            { id = 4375,   qty =  2, name = "Whirring Bronze Gizmo" },
            { id = 4363,   qty =  1, name = "Copper Modulator" },
            { id = 1206,   qty =  1, name = "Moss Agate" },
        },
    },
    [4380] = { name = "Big Bronze Bomb", skill = 140, spec = nil,
        components = {
            { id = 4377,   qty =  2, name = "Heavy Blasting Powder" },
            { id = 2841,   qty =  3, name = "Tin Bar" },
            { id = 4404,   qty =  1, name = "Silver Contact" },
        },
    },
    [4381] = { name = "Minor Recombobulator", skill = 140, spec = "Gnomish",
        components = {
            { id = 4371,   qty =  1, name = "Bronze Tube" },
            { id = 4375,   qty =  2, name = "Whirring Bronze Gizmo" },
            { id = 2319,   qty =  2, name = "Medium Leather" },
            { id = 1206,   qty =  1, name = "Moss Agate" },
        },
    },
    [4382] = { name = "Bronze Framework", skill = 145, spec = nil,
        components = {
            { id = 2841,   qty =  2, name = "Tin Bar" },
            { id = 2319,   qty =  1, name = "Medium Leather" },
            { id = 2592,   qty =  1, name = "Wool Cloth" },
        },
    },
    [4383] = { name = "Moonsight Rifle", skill = 145, spec = nil,
        components = {
            { id = 4371,   qty =  3, name = "Bronze Tube" },
            { id = 4375,   qty =  3, name = "Whirring Bronze Gizmo" },
            { id = 4400,   qty =  1, name = "Heavy Stock" },
            { id = 1705,   qty =  2, name = "Lesser Moonstone" },
        },
    },
    [4384] = { name = "Explosive Sheep", skill = 150, spec = nil,
        components = {
            { id = 4382,   qty =  1, name = "Bronze Framework" },
            { id = 4375,   qty =  1, name = "Whirring Bronze Gizmo" },
            { id = 4377,   qty =  2, name = "Heavy Blasting Powder" },
            { id = 2592,   qty =  2, name = "Wool Cloth" },
        },
    },
    [4385] = { name = "Green Tinted Goggles", skill = 150, spec = nil,
        components = {
            { id = 2319,   qty =  4, name = "Medium Leather" },
            { id = 1206,   qty =  2, name = "Moss Agate" },
            { id = 4368,   qty =  1, name = "Flying Tiger Goggles" },
        },
    },
    [6533] = { name = "Aquadynamic Fish Attractor", skill = 150, spec = nil,
        components = {
            { id = 2841,   qty =  2, name = "Tin Bar" },
            { id = 6530,   qty =  1, name = "Nightcrawlers" },
            { id = 4364,   qty =  1, name = "Coarse Blasting Powder" },
        },
    },
    [9312] = { name = "Blue Firework", skill = 150, spec = nil,
        components = {
            { id = 4377,   qty =  1, name = "Heavy Blasting Powder" },
            { id = 4234,   qty =  1, name = "Heavy Leather" },
        },
    },
    [9313] = { name = "Green Firework", skill = 150, spec = nil,
        components = {
            { id = 4377,   qty =  1, name = "Heavy Blasting Powder" },
            { id = 4234,   qty =  1, name = "Heavy Leather" },
        },
    },
    [9318] = { name = "Red Firework", skill = 150, spec = nil,
        components = {
            { id = 4377,   qty =  1, name = "Heavy Blasting Powder" },
            { id = 4234,   qty =  1, name = "Heavy Leather" },
        },
    },
    [10558] = { name = "Gold Power Core", skill = 150, spec = nil,
        components = {
            { id = 3577,   qty =  1, name = "Steel Bar" },
        },
    },
    [4386] = { name = "Ice Deflector", skill = 155, spec = nil,
        components = {
            { id = 4375,   qty =  1, name = "Whirring Bronze Gizmo" },
            { id = 3829,   qty =  1, name = "Frost Oil" },
        },
    },
    [4387] = { name = "Iron Strut", skill = 160, spec = nil,
        components = {
            { id = 3575,   qty =  2, name = "Iron Bar" },
        },
    },
    [4388] = { name = "Discombobulator Ray", skill = 160, spec = nil,
        components = {
            { id = 4375,   qty =  3, name = "Whirring Bronze Gizmo" },
            { id = 4306,   qty =  2, name = "Silk Cloth" },
            { id = 1529,   qty =  1, name = "Jade" },
            { id = 4371,   qty =  1, name = "Bronze Tube" },
        },
    },
    [4403] = { name = "Portable Bronze Mortar", skill = 165, spec = nil,
        components = {
            { id = 4371,   qty =  4, name = "Bronze Tube" },
            { id = 4387,   qty =  1, name = "Iron Strut" },
            { id = 4377,   qty =  4, name = "Heavy Blasting Powder" },
            { id = 2319,   qty =  4, name = "Medium Leather" },
        },
    },
    [7148] = { name = "Goblin Jumper Cables", skill = 165, spec = nil,
        components = {
            { id = 3575,   qty =  6, name = "Iron Bar" },
            { id = 4375,   qty =  2, name = "Whirring Bronze Gizmo" },
            { id = 814,    qty =  2, name = "Flask of Oil" },
            { id = 4306,   qty =  2, name = "Silk Cloth" },
            { id = 1210,   qty =  2, name = "Tigerseye" },
            { id = 7191,   qty =  1, name = "Fused Wiring" },
        },
    },
    [4389] = { name = "Gyrochronatom", skill = 170, spec = nil,
        components = {
            { id = 3575,   qty =  1, name = "Iron Bar" },
            { id = 10558,  qty =  1, name = "Gold Power Core" },
        },
    },
    [4390] = { name = "Iron Grenade", skill = 175, spec = nil,
        components = {
            { id = 3575,   qty =  1, name = "Iron Bar" },
            { id = 4377,   qty =  1, name = "Heavy Blasting Powder" },
            { id = 4306,   qty =  1, name = "Silk Cloth" },
        },
    },
    [4391] = { name = "Compact Harvest Reaper Kit", skill = 175, spec = nil,
        components = {
            { id = 4387,   qty =  2, name = "Iron Strut" },
            { id = 4382,   qty =  1, name = "Bronze Framework" },
            { id = 4389,   qty =  2, name = "Gyrochronatom" },
            { id = 4234,   qty =  4, name = "Heavy Leather" },
        },
    },
    [10498] = { name = "Gyromatic Micro-Adjustor", skill = 175, spec = nil,
        components = {
            { id = 3859,   qty =  4, name = "Gold Ore" },
        },
    },
    [10499] = { name = "Bright-Eye Goggles", skill = 175, spec = nil,
        components = {
            { id = 4234,   qty =  6, name = "Heavy Leather" },
            { id = 3864,   qty =  2, name = "Citrine" },
        },
    },
    [10505] = { name = "Solid Blasting Powder", skill = 175, spec = nil,
        components = {
            { id = 7912,   qty =  2, name = "Solid Stone" },
        },
    },
    [10507] = { name = "Solid Dynamite", skill = 175, spec = nil,
        components = {
            { id = 10505,  qty =  1, name = "Solid Blasting Powder" },
            { id = 4306,   qty =  1, name = "Silk Cloth" },
        },
    },
    [21589] = { name = "Large Blue Rocket", skill = 175, spec = nil,
        components = {
            { id = 4377,   qty =  1, name = "Heavy Blasting Powder" },
            { id = 4234,   qty =  1, name = "Heavy Leather" },
        },
    },
    [21590] = { name = "Large Green Rocket", skill = 175, spec = nil,
        components = {
            { id = 4377,   qty =  1, name = "Heavy Blasting Powder" },
            { id = 4234,   qty =  1, name = "Heavy Leather" },
        },
    },
    [21592] = { name = "Large Red Rocket", skill = 175, spec = nil,
        components = {
            { id = 4377,   qty =  1, name = "Heavy Blasting Powder" },
            { id = 4234,   qty =  1, name = "Heavy Leather" },
        },
    },
    [4407] = { name = "Accurate Scope", skill = 180, spec = nil,
        components = {
            { id = 4371,   qty =  1, name = "Bronze Tube" },
            { id = 1529,   qty =  1, name = "Jade" },
            { id = 3864,   qty =  1, name = "Citrine" },
        },
    },
    [4392] = { name = "Advanced Target Dummy", skill = 185, spec = nil,
        components = {
            { id = 4387,   qty =  1, name = "Iron Strut" },
            { id = 4382,   qty =  1, name = "Bronze Framework" },
            { id = 4389,   qty =  1, name = "Gyrochronatom" },
            { id = 4234,   qty =  4, name = "Heavy Leather" },
        },
    },
    [4393] = { name = "Craftsman's Monocle", skill = 185, spec = nil,
        components = {
            { id = 4234,   qty =  6, name = "Heavy Leather" },
            { id = 3864,   qty =  2, name = "Citrine" },
        },
    },
    [4852] = { name = "Flash Bomb", skill = 185, spec = nil,
        components = {
            { id = 4611,   qty =  1, name = "Blue Pearl" },
            { id = 4377,   qty =  1, name = "Heavy Blasting Powder" },
            { id = 4306,   qty =  1, name = "Silk Cloth" },
        },
    },
    [4394] = { name = "Big Iron Bomb", skill = 190, spec = nil,
        components = {
            { id = 3575,   qty =  3, name = "Iron Bar" },
            { id = 4377,   qty =  3, name = "Heavy Blasting Powder" },
            { id = 4404,   qty =  1, name = "Silver Contact" },
        },
    },
    [17716] = { name = "Snowmaster 9000", skill = 190, spec = nil,
        components = {
            { id = 3860,   qty =  8, name = "Mithril Bar" },
            { id = 4389,   qty =  4, name = "Gyrochronatom" },
            { id = 17202,  qty =  4, name = "Snowball" },
            { id = 3829,   qty =  1, name = "Frost Oil" },
        },
    },
    [4395] = { name = "Goblin Land Mine", skill = 195, spec = "Goblin",
        components = {
            { id = 4377,   qty =  3, name = "Heavy Blasting Powder" },
            { id = 3575,   qty =  2, name = "Iron Bar" },
            { id = 4389,   qty =  1, name = "Gyrochronatom" },
        },
    },
    [10559] = { name = "Mithril Tube", skill = 195, spec = nil,
        components = {
            { id = 3860,   qty =  3, name = "Mithril Bar" },
        },
    },
    [4396] = { name = "Mechanical Dragonling", skill = 200, spec = nil,
        components = {
            { id = 4382,   qty =  1, name = "Bronze Framework" },
            { id = 4387,   qty =  4, name = "Iron Strut" },
            { id = 4389,   qty =  4, name = "Gyrochronatom" },
            { id = 3864,   qty =  2, name = "Citrine" },
            { id = 7191,   qty =  1, name = "Fused Wiring" },
        },
    },
    [4397] = { name = "Gnomish Cloaking Device", skill = 200, spec = "Gnomish",
        components = {
            { id = 4389,   qty =  4, name = "Gyrochronatom" },
            { id = 1529,   qty =  2, name = "Jade" },
            { id = 1705,   qty =  2, name = "Lesser Moonstone" },
            { id = 3864,   qty =  2, name = "Citrine" },
            { id = 7191,   qty =  1, name = "Fused Wiring" },
        },
    },
    [4398] = { name = "Large Seaforium Charge", skill = 200, spec = nil,
        components = {
            { id = 10505,  qty =  2, name = "Solid Blasting Powder" },
            { id = 4234,   qty =  2, name = "Heavy Leather" },
            { id = 159,    qty =  1, name = "Refreshing Spring Water" },
        },
    },
    [10560] = { name = "Unstable Trigger", skill = 200, spec = nil,
        components = {
            { id = 3860,   qty =  1, name = "Mithril Bar" },
            { id = 4338,   qty =  1, name = "Mageweave Cloth" },
            { id = 10505,  qty =  1, name = "Solid Blasting Powder" },
        },
    },
    [11590] = { name = "Mechanical Repair Kit", skill = 200, spec = nil,
        components = {
            { id = 3860,   qty =  1, name = "Mithril Bar" },
            { id = 4338,   qty =  1, name = "Mageweave Cloth" },
            { id = 10505,  qty =  1, name = "Solid Blasting Powder" },
        },
    },
    [18588] = { name = "Ez-Thro Dynamite II", skill = 200, spec = nil,
        components = {
            { id = 10505,  qty =  1, name = "Solid Blasting Powder" },
            { id = 4338,   qty =  2, name = "Mageweave Cloth" },
        },
    },
    [10500] = { name = "Fire Goggles", skill = 205, spec = nil,
        components = {
            { id = 4385,   qty =  1, name = "Green Tinted Goggles" },
            { id = 3864,   qty =  2, name = "Citrine" },
            { id = 7068,   qty =  2, name = "Elemental Fire" },
            { id = 4234,   qty =  4, name = "Heavy Leather" },
        },
    },
    [10508] = { name = "Mithril Blunderbuss", skill = 205, spec = nil,
        components = {
            { id = 10559,  qty =  1, name = "Mithril Tube" },
            { id = 10560,  qty =  1, name = "Unstable Trigger" },
            { id = 4400,   qty =  1, name = "Heavy Stock" },
            { id = 3860,   qty =  4, name = "Mithril Bar" },
            { id = 7068,   qty =  2, name = "Elemental Fire" },
        },
    },
    [10542] = { name = "Goblin Mining Helmet", skill = 205, spec = "Goblin",
        components = {
            { id = 3860,   qty =  8, name = "Mithril Bar" },
            { id = 3864,   qty =  1, name = "Citrine" },
            { id = 7067,   qty =  4, name = "Elemental Earth" },
        },
    },
    [10543] = { name = "Goblin Construction Helmet", skill = 205, spec = "Goblin",
        components = {
            { id = 3860,   qty =  8, name = "Mithril Bar" },
            { id = 3864,   qty =  1, name = "Citrine" },
            { id = 7068,   qty =  4, name = "Elemental Fire" },
        },
    },
    [10644] = { name = "Recipe: Goblin Rocket Fuel", skill = 205, spec = nil,
        components = {
            { id = 10648,  qty =  1, name = "Common Parchment" },
            { id = 10647,  qty =  1, name = "Engineer's Ink" },
        },
    },
    [10646] = { name = "Goblin Sapper Charge", skill = 205, spec = "Goblin",
        components = {
            { id = 4338,   qty =  1, name = "Mageweave Cloth" },
            { id = 10505,  qty =  3, name = "Solid Blasting Powder" },
            { id = 10560,  qty =  1, name = "Unstable Trigger" },
        },
    },
    [10713] = { name = "Plans: Inlaid Mithril Cylinder", skill = 205, spec = nil,
        components = {
            { id = 10648,  qty =  1, name = "Common Parchment" },
            { id = 10647,  qty =  1, name = "Engineer's Ink" },
        },
    },
    [10716] = { name = "Gnomish Shrink Ray", skill = 205, spec = "Gnomish",
        components = {
            { id = 10559,  qty =  1, name = "Mithril Tube" },
            { id = 10560,  qty =  1, name = "Unstable Trigger" },
            { id = 3860,   qty =  4, name = "Mithril Bar" },
            { id = 8151,   qty =  4, name = "Flask of Mojo" },
            { id = 1529,   qty =  2, name = "Jade" },
        },
    },
    [11825] = { name = "Pet Bombling", skill = 205, spec = nil,
        components = {
            { id = 4394,   qty =  1, name = "Big Iron Bomb" },
            { id = 7077,   qty =  1, name = "Heart of Fire" },
            { id = 7191,   qty =  1, name = "Fused Wiring" },
            { id = 3860,   qty =  6, name = "Mithril Bar" },
        },
    },
    [11826] = { name = "Lil' Smoky", skill = 205, spec = nil,
        components = {
            { id = 7075,   qty =  1, name = "Core of Earth" },
            { id = 4389,   qty =  2, name = "Gyrochronatom" },
            { id = 7191,   qty =  1, name = "Fused Wiring" },
            { id = 3860,   qty =  2, name = "Mithril Bar" },
            { id = 6037,   qty =  1, name = "Truesilver Bar" },
        },
    },
    [10512] = { name = "Hi-Impact Mithril Slugs", skill = 210, spec = nil,
        components = {
            { id = 3860,   qty =  1, name = "Mithril Bar" },
            { id = 10505,  qty =  1, name = "Solid Blasting Powder" },
        },
    },
    [10545] = { name = "Gnomish Goggles", skill = 210, spec = "Gnomish",
        components = {
            { id = 10500,  qty =  1, name = "Fire Goggles" },
            { id = 10559,  qty =  1, name = "Mithril Tube" },
            { id = 10558,  qty =  2, name = "Gold Power Core" },
            { id = 8151,   qty =  2, name = "Flask of Mojo" },
            { id = 4234,   qty =  2, name = "Heavy Leather" },
        },
    },
    [10546] = { name = "Deadly Scope", skill = 210, spec = nil,
        components = {
            { id = 10559,  qty =  1, name = "Mithril Tube" },
            { id = 7909,   qty =  2, name = "Aquamarine" },
            { id = 4304,   qty =  2, name = "Thick Leather" },
        },
    },
    [10720] = { name = "Gnomish Net-o-Matic Projector", skill = 210, spec = "Gnomish",
        components = {
            { id = 10559,  qty =  1, name = "Mithril Tube" },
            { id = 10285,  qty =  2, name = "Shadow Silk" },
            { id = 4337,   qty =  4, name = "Soie d'araignée épaisse" },
            { id = 10505,  qty =  2, name = "Solid Blasting Powder" },
            { id = 3860,   qty =  4, name = "Mithril Bar" },
        },
    },
    [10514] = { name = "Mithril Frag Bomb", skill = 215, spec = nil,
        components = {
            { id = 10561,  qty =  1, name = "Mithril Casing" },
            { id = 10560,  qty =  1, name = "Unstable Trigger" },
            { id = 10505,  qty =  1, name = "Solid Blasting Powder" },
        },
    },
    [10561] = { name = "Mithril Casing", skill = 215, spec = nil,
        components = {
            { id = 3860,   qty =  3, name = "Mithril Bar" },
        },
    },
    [10721] = { name = "Gnomish Harm Prevention Belt", skill = 215, spec = "Gnomish",
        components = {
            { id = 7387,   qty =  1, name = "Ceinture matte" },
            { id = 3860,   qty =  4, name = "Mithril Bar" },
            { id = 6037,   qty =  2, name = "Truesilver Bar" },
            { id = 10560,  qty =  1, name = "Unstable Trigger" },
            { id = 7909,   qty =  2, name = "Aquamarine" },
        },
    },
    [10501] = { name = "Catseye Ultra Goggles", skill = 220, spec = "Gnomish",
        components = {
            { id = 4304,   qty =  4, name = "Thick Leather" },
            { id = 7909,   qty =  2, name = "Aquamarine" },
            { id = 10592,  qty =  1, name = "Catseye Elixir" },
        },
    },
    [10510] = { name = "Mithril Heavy-bore Rifle", skill = 220, spec = nil,
        components = {
            { id = 10559,  qty =  2, name = "Mithril Tube" },
            { id = 10560,  qty =  1, name = "Unstable Trigger" },
            { id = 4400,   qty =  1, name = "Heavy Stock" },
            { id = 3860,   qty =  6, name = "Mithril Bar" },
            { id = 3864,   qty =  2, name = "Citrine" },
        },
    },
    [7189] = { name = "Goblin Rocket Boots", skill = 225, spec = "Goblin",
        components = {
            { id = 10026,  qty =  1, name = "Bottes noires en tisse-mage" },
            { id = 10559,  qty =  2, name = "Mithril Tube" },
            { id = 4234,   qty =  4, name = "Heavy Leather" },
            { id = 9061,   qty =  2, name = "Goblin Rocket Fuel" },
            { id = 10560,  qty =  1, name = "Unstable Trigger" },
        },
    },
    [10502] = { name = "Spellpower Goggles Xtreme", skill = 225, spec = "Gnomish",
        components = {
            { id = 4304,   qty =  4, name = "Thick Leather" },
            { id = 7910,   qty =  2, name = "Star Ruby" },
        },
    },
    [10518] = { name = "Parachute Cloak", skill = 225, spec = nil,
        components = {
            { id = 4339,   qty =  4, name = "Bolt of Mageweave" },
            { id = 10285,  qty =  2, name = "Shadow Silk" },
            { id = 10560,  qty =  1, name = "Unstable Trigger" },
            { id = 10505,  qty =  4, name = "Solid Blasting Powder" },
        },
    },
    [10577] = { name = "Goblin Mortar", skill = 225, spec = "Goblin",
        components = {
            { id = 10561,  qty =  4, name = "Mithril Casing" },
            { id = 10560,  qty =  2, name = "Unstable Trigger" },
            { id = 10505,  qty =  4, name = "Solid Blasting Powder" },
        },
    },
    [10724] = { name = "Gnomish Rocket Boots", skill = 225, spec = "Gnomish",
        components = {
            { id = 10026,  qty =  1, name = "Bottes noires en tisse-mage" },
            { id = 10559,  qty =  2, name = "Mithril Tube" },
            { id = 4234,   qty =  4, name = "Heavy Leather" },
            { id = 10505,  qty =  8, name = "Solid Blasting Powder" },
            { id = 4389,   qty =  4, name = "Gyrochronatom" },
        },
    },
    [21569] = { name = "Firework Launcher", skill = 225, spec = nil,
        components = {
            { id = 9060,   qty =  1, name = "Inlaid Mithril Cylinder" },
            { id = 9061,   qty =  1, name = "Goblin Rocket Fuel" },
            { id = 10560,  qty =  1, name = "Unstable Trigger" },
            { id = 10561,  qty =  1, name = "Mithril Casing" },
        },
    },
    [21571] = { name = "Blue Rocket Cluster", skill = 225, spec = nil,
        components = {
            { id = 10505,  qty =  1, name = "Solid Blasting Powder" },
            { id = 4304,   qty =  1, name = "Thick Leather" },
        },
    },
    [21574] = { name = "Green Rocket Cluster", skill = 225, spec = nil,
        components = {
            { id = 10505,  qty =  1, name = "Solid Blasting Powder" },
            { id = 4304,   qty =  1, name = "Thick Leather" },
        },
    },
    [21576] = { name = "Red Rocket Cluster", skill = 225, spec = nil,
        components = {
            { id = 10505,  qty =  1, name = "Solid Blasting Powder" },
            { id = 4304,   qty =  1, name = "Thick Leather" },
        },
    },
    [10503] = { name = "Rose Colored Goggles", skill = 230, spec = "Gnomish",
        components = {
            { id = 4304,   qty =  6, name = "Thick Leather" },
            { id = 7910,   qty =  2, name = "Star Ruby" },
        },
    },
    [10506] = { name = "Deepdive Helmet", skill = 230, spec = nil,
        components = {
            { id = 3860,   qty =  8, name = "Mithril Bar" },
            { id = 10561,  qty =  1, name = "Mithril Casing" },
            { id = 6037,   qty =  1, name = "Truesilver Bar" },
            { id = 818,    qty =  4, name = "Malachite" },
            { id = 774,    qty =  4, name = "Malachite" },
        },
    },
    [10587] = { name = "Goblin Bomb Dispenser", skill = 230, spec = "Goblin",
        components = {
            { id = 10561,  qty =  2, name = "Mithril Casing" },
            { id = 10505,  qty =  4, name = "Solid Blasting Powder" },
            { id = 6037,   qty =  6, name = "Truesilver Bar" },
            { id = 10560,  qty =  1, name = "Unstable Trigger" },
            { id = 4407,   qty =  2, name = "Lunette de précision" },
        },
    },
    [10725] = { name = "Gnomish Battle Chicken", skill = 230, spec = "Gnomish",
        components = {
            { id = 10561,  qty =  1, name = "Mithril Casing" },
            { id = 6037,   qty =  6, name = "Truesilver Bar" },
            { id = 3860,   qty =  6, name = "Mithril Bar" },
            { id = 9060,   qty =  2, name = "Inlaid Mithril Cylinder" },
            { id = 10558,  qty =  1, name = "Gold Power Core" },
            { id = 1529,   qty =  2, name = "Jade" },
        },
    },
    [10562] = { name = "Hi-Explosive Bomb", skill = 235, spec = nil,
        components = {
            { id = 10561,  qty =  2, name = "Mithril Casing" },
            { id = 10560,  qty =  1, name = "Unstable Trigger" },
            { id = 10505,  qty =  2, name = "Solid Blasting Powder" },
        },
    },
    [10586] = { name = "The Big One", skill = 235, spec = "Goblin",
        components = {
            { id = 10561,  qty =  1, name = "Mithril Casing" },
            { id = 9061,   qty =  1, name = "Goblin Rocket Fuel" },
            { id = 10507,  qty =  6, name = "Dynamite solide" },
            { id = 10560,  qty =  1, name = "Unstable Trigger" },
        },
    },
    [10726] = { name = "Gnomish Mind Control Cap", skill = 235, spec = "Gnomish",
        components = {
            { id = 3860,   qty = 10, name = "Mithril Bar" },
            { id = 6037,   qty =  4, name = "Truesilver Bar" },
            { id = 10558,  qty =  1, name = "Gold Power Core" },
            { id = 7910,   qty =  2, name = "Star Ruby" },
            { id = 4338,   qty =  4, name = "Mageweave Cloth" },
        },
    },
    [10548] = { name = "Sniper Scope", skill = 240, spec = nil,
        components = {
            { id = 10559,  qty =  1, name = "Mithril Tube" },
            { id = 7910,   qty =  1, name = "Star Ruby" },
            { id = 6037,   qty =  2, name = "Truesilver Bar" },
        },
    },
    [10645] = { name = "Gnomish Death Ray", skill = 240, spec = "Gnomish",
        components = {
            { id = 10559,  qty =  2, name = "Mithril Tube" },
            { id = 10560,  qty =  1, name = "Unstable Trigger" },
            { id = 12808,  qty =  1, name = "Essence de non-mort" },
            { id = 7972,   qty =  4, name = "Ichor of Undeath" },
            { id = 9060,   qty =  1, name = "Inlaid Mithril Cylinder" },
        },
    },
    [10727] = { name = "Goblin Dragon Gun", skill = 240, spec = "Goblin",
        components = {
            { id = 10559,  qty =  2, name = "Mithril Tube" },
            { id = 9061,   qty =  4, name = "Goblin Rocket Fuel" },
            { id = 3860,   qty =  6, name = "Mithril Bar" },
            { id = 6037,   qty =  6, name = "Truesilver Bar" },
            { id = 10560,  qty =  1, name = "Unstable Trigger" },
        },
    },
    [10504] = { name = "Green Lens", skill = 245, spec = "Gnomish",
        components = {
            { id = 4304,   qty =  8, name = "Thick Leather" },
            { id = 1529,   qty =  3, name = "Jade" },
            { id = 7909,   qty =  3, name = "Aquamarine" },
            { id = 10286,  qty =  2, name = "Heart of the Wild" },
            { id = 8153,   qty =  2, name = "Purple Lotus" },
        },
    },
    [10513] = { name = "Mithril Gyro-Shot", skill = 245, spec = nil,
        components = {
            { id = 3860,   qty =  2, name = "Mithril Bar" },
            { id = 10505,  qty =  2, name = "Solid Blasting Powder" },
        },
    },
    [10588] = { name = "Goblin Rocket Helmet", skill = 245, spec = "Goblin",
        components = {
            { id = 10543,  qty =  1, name = "Goblin Construction Helmet" },
            { id = 9061,   qty =  4, name = "Goblin Rocket Fuel" },
            { id = 3860,   qty =  4, name = "Mithril Bar" },
            { id = 10560,  qty =  1, name = "Unstable Trigger" },
        },
    },
    [10576] = { name = "Mithril Mechanical Dragonling", skill = 250, spec = nil,
        components = {
            { id = 3860,   qty = 14, name = "Mithril Bar" },
            { id = 7077,   qty =  4, name = "Heart of Fire" },
            { id = 6037,   qty =  4, name = "Truesilver Bar" },
            { id = 9060,   qty =  2, name = "Inlaid Mithril Cylinder" },
            { id = 9061,   qty =  2, name = "Goblin Rocket Fuel" },
            { id = 7910,   qty =  2, name = "Star Ruby" },
        },
    },
    [15846] = { name = "Salt Shaker", skill = 250, spec = nil,
        components = {
            { id = 10561,  qty =  1, name = "Mithril Casing" },
            { id = 12359,  qty =  6, name = "Thorium Bar" },
            { id = 10558,  qty =  1, name = "Gold Power Core" },
            { id = 10560,  qty =  4, name = "Unstable Trigger" },
        },
    },
    [15992] = { name = "Dense Blasting Powder", skill = 250, spec = nil,
        components = {
            { id = 12365,  qty =  2, name = "Dense Stone" },
        },
    },
    [18641] = { name = "Dense Dynamite", skill = 250, spec = nil,
        components = {
            { id = 15992,  qty =  2, name = "Dense Blasting Powder" },
            { id = 14047,  qty =  3, name = "Runecloth" },
        },
    },
    [19026] = { name = "Snake Burst Firework", skill = 250, spec = nil,
        components = {
            { id = 15992,  qty =  2, name = "Dense Blasting Powder" },
            { id = 14047,  qty =  2, name = "Runecloth" },
            { id = 8150,   qty =  1, name = "Deeprock Salt" },
        },
    },
    [21277] = { name = "Tranquil Mechanical Yeti", skill = 250, spec = nil,
        components = {
            { id = 15407,  qty =  1, name = "Cured Rugged Hide" },
            { id = 15994,  qty =  4, name = "Thorium Widget" },
            { id = 7079,   qty =  2, name = "Essence of Earth" },
            { id = 18631,  qty =  2, name = "Truesilver Transformer" },
            { id = 10558,  qty =  1, name = "Gold Power Core" },
        },
    },
    [15993] = { name = "Thorium Grenade", skill = 260, spec = nil,
        components = {
            { id = 15994,  qty =  1, name = "Thorium Widget" },
            { id = 12359,  qty =  3, name = "Thorium Bar" },
            { id = 15992,  qty =  3, name = "Dense Blasting Powder" },
            { id = 14047,  qty =  3, name = "Runecloth" },
        },
    },
    [15994] = { name = "Thorium Widget", skill = 260, spec = nil,
        components = {
            { id = 12359,  qty =  3, name = "Thorium Bar" },
            { id = 14047,  qty =  1, name = "Runecloth" },
        },
    },
    [15995] = { name = "Thorium Rifle", skill = 260, spec = nil,
        components = {
            { id = 10559,  qty =  2, name = "Mithril Tube" },
            { id = 10561,  qty =  2, name = "Mithril Casing" },
            { id = 15994,  qty =  2, name = "Thorium Widget" },
            { id = 12359,  qty =  4, name = "Thorium Bar" },
            { id = 10546,  qty =  1, name = "Deadly Scope" },
        },
    },
    [18631] = { name = "Truesilver Transformer", skill = 260, spec = nil,
        components = {
            { id = 6037,   qty =  2, name = "Truesilver Bar" },
            { id = 7067,   qty =  2, name = "Elemental Earth" },
            { id = 7069,   qty =  1, name = "Elemental Air" },
        },
    },
    [18634] = { name = "Gyrofreeze Ice Reflector", skill = 260, spec = nil,
        components = {
            { id = 15994,  qty =  6, name = "Thorium Widget" },
            { id = 18631,  qty =  2, name = "Truesilver Transformer" },
            { id = 12361,  qty =  2, name = "Large Opal" },
            { id = 7078,   qty =  4, name = "Essence of Fire" },
            { id = 3829,   qty =  2, name = "Frost Oil" },
            { id = 13467,  qty =  4, name = "Icecap" },
        },
    },
    [18660] = { name = "World Enlarger", skill = 260, spec = nil,
        components = {
            { id = 10561,  qty =  1, name = "Mithril Casing" },
            { id = 15994,  qty =  2, name = "Thorium Widget" },
            { id = 10558,  qty =  1, name = "Gold Power Core" },
            { id = 10560,  qty =  1, name = "Unstable Trigger" },
            { id = 3864,   qty =  1, name = "Citrine" },
        },
    },
    [15996] = { name = "Lifelike Mechanical Toad", skill = 265, spec = nil,
        components = {
            { id = 12803,  qty =  1, name = "Living Essence" },
            { id = 15994,  qty =  4, name = "Thorium Widget" },
            { id = 10558,  qty =  1, name = "Gold Power Core" },
            { id = 8170,   qty =  1, name = "Rugged Leather" },
        },
    },
    [18587] = { name = "Goblin Jumper Cables XL", skill = 265, spec = "Goblin",
        components = {
            { id = 15994,  qty =  2, name = "Thorium Widget" },
            { id = 18631,  qty =  2, name = "Truesilver Transformer" },
            { id = 7191,   qty =  2, name = "Fused Wiring" },
            { id = 14227,  qty =  2, name = "Ironweb Spider Silk" },
            { id = 7910,   qty =  2, name = "Star Ruby" },
        },
    },
    [18645] = { name = "Gnomish Alarm-o-Bot", skill = 265, spec = nil,
        components = {
            { id = 12359,  qty =  4, name = "Thorium Bar" },
            { id = 15994,  qty =  2, name = "Thorium Widget" },
            { id = 8170,   qty =  4, name = "Rugged Leather" },
            { id = 7910,   qty =  1, name = "Star Ruby" },
            { id = 7191,   qty =  1, name = "Fused Wiring" },
        },
    },
    [15999] = { name = "Spellpower Goggles Xtreme Plus", skill = 270, spec = "Gnomish",
        components = {
            { id = 10502,  qty =  1, name = "Spellpower Goggles Xtreme" },
            { id = 7910,   qty =  4, name = "Star Ruby" },
            { id = 12810,  qty =  2, name = "Enchanted Leather" },
            { id = 14047,  qty =  8, name = "Runecloth" },
        },
    },
    [7191] = { name = "Fused Wiring", skill = 275, spec = nil,
        components = {
            { id = 20816,  qty =  3, name = "Delicate Copper Wire" },
            { id = 7078,   qty =  2, name = "Essence of Fire" },
        },
    },
    [16000] = { name = "Thorium Tube", skill = 275, spec = nil,
        components = {
            { id = 12359,  qty =  6, name = "Thorium Bar" },
        },
    },
    [16004] = { name = "Dark Iron Rifle", skill = 275, spec = nil,
        components = {
            { id = 16000,  qty =  2, name = "Thorium Tube" },
            { id = 11371,  qty =  6, name = "Dark Iron Bar" },
            { id = 10546,  qty =  2, name = "Deadly Scope" },
            { id = 12361,  qty =  2, name = "Large Opal" },
            { id = 12799,  qty =  2, name = "Blue Sapphire" },
            { id = 8170,   qty =  4, name = "Rugged Leather" },
        },
    },
    [16023] = { name = "Masterwork Target Dummy", skill = 275, spec = nil,
        components = {
            { id = 10561,  qty =  1, name = "Mithril Casing" },
            { id = 16000,  qty =  1, name = "Thorium Tube" },
            { id = 15994,  qty =  2, name = "Thorium Widget" },
            { id = 6037,   qty =  1, name = "Truesilver Bar" },
            { id = 8170,   qty =  2, name = "Rugged Leather" },
            { id = 14047,  qty =  4, name = "Runecloth" },
        },
    },
    [18594] = { name = "Powerful Seaforium Charge", skill = 275, spec = nil,
        components = {
            { id = 15994,  qty =  2, name = "Thorium Widget" },
            { id = 15992,  qty =  3, name = "Dense Blasting Powder" },
            { id = 8170,   qty =  2, name = "Rugged Leather" },
            { id = 159,    qty =  1, name = "Refreshing Spring Water" },
        },
    },
    [18637] = { name = "Major Recombobulator", skill = 275, spec = "Gnomish",
        components = {
            { id = 16000,  qty =  2, name = "Thorium Tube" },
            { id = 18631,  qty =  1, name = "Truesilver Transformer" },
            { id = 14047,  qty =  2, name = "Runecloth" },
        },
    },
    [21570] = { name = "Cluster Launcher", skill = 275, spec = nil,
        components = {
            { id = 9060,   qty =  4, name = "Inlaid Mithril Cylinder" },
            { id = 9061,   qty =  4, name = "Goblin Rocket Fuel" },
            { id = 18631,  qty =  2, name = "Truesilver Transformer" },
            { id = 10561,  qty =  1, name = "Mithril Casing" },
        },
    },
    [21714] = { name = "Large Blue Rocket Cluster", skill = 275, spec = nil,
        components = {
            { id = 15992,  qty =  1, name = "Dense Blasting Powder" },
            { id = 8170,   qty =  1, name = "Rugged Leather" },
        },
    },
    [21716] = { name = "Large Green Rocket Cluster", skill = 275, spec = nil,
        components = {
            { id = 15992,  qty =  1, name = "Dense Blasting Powder" },
            { id = 8170,   qty =  1, name = "Rugged Leather" },
        },
    },
    [21718] = { name = "Large Red Rocket Cluster", skill = 275, spec = nil,
        components = {
            { id = 15992,  qty =  1, name = "Dense Blasting Powder" },
            { id = 8170,   qty =  1, name = "Rugged Leather" },
        },
    },
    [22728] = { name = "Steam Tonk Controller", skill = 275, spec = nil,
        components = {
            { id = 15994,  qty =  2, name = "Thorium Widget" },
            { id = 10561,  qty =  1, name = "Mithril Casing" },
            { id = 10558,  qty =  1, name = "Gold Power Core" },
        },
    },
    [15997] = { name = "Thorium Shells", skill = 285, spec = nil,
        components = {
            { id = 12359,  qty =  2, name = "Thorium Bar" },
            { id = 15992,  qty =  1, name = "Dense Blasting Powder" },
        },
    },
    [16005] = { name = "Dark Iron Bomb", skill = 285, spec = nil,
        components = {
            { id = 15994,  qty =  2, name = "Thorium Widget" },
            { id = 11371,  qty =  1, name = "Dark Iron Bar" },
            { id = 15992,  qty =  3, name = "Dense Blasting Powder" },
            { id = 14047,  qty =  3, name = "Runecloth" },
        },
    },
    [16006] = { name = "Delicate Arcanite Converter", skill = 285, spec = nil,
        components = {
            { id = 12360,  qty =  1, name = "Arcanite Bar" },
            { id = 14227,  qty =  1, name = "Ironweb Spider Silk" },
        },
    },
    [18984] = { name = "Dimensional Ripper - Everlook", skill = 285, spec = "Goblin",
        components = {
            { id = 3860,   qty = 10, name = "Mithril Bar" },
            { id = 18631,  qty =  1, name = "Truesilver Transformer" },
            { id = 7077,   qty =  4, name = "Heart of Fire" },
            { id = 7910,   qty =  2, name = "Star Ruby" },
            { id = 10586,  qty =  1, name = "Le Mastoc" },
        },
    },
    [18986] = { name = "Ultrasafe Transporter: Gadgetzan", skill = 285, spec = "Gnomish",
        components = {
            { id = 3860,   qty = 12, name = "Mithril Bar" },
            { id = 18631,  qty =  2, name = "Truesilver Transformer" },
            { id = 7075,   qty =  4, name = "Core of Earth" },
            { id = 7079,   qty =  2, name = "Essence of Earth" },
            { id = 7909,   qty =  4, name = "Aquamarine" },
            { id = 9060,   qty =  1, name = "Inlaid Mithril Cylinder" },
        },
    },
    [16008] = { name = "Master Engineer's Goggles", skill = 290, spec = nil,
        components = {
            { id = 10500,  qty =  1, name = "Fire Goggles" },
            { id = 12364,  qty =  2, name = "Arcane Crystal" },
            { id = 12810,  qty =  4, name = "Enchanted Leather" },
        },
    },
    [16009] = { name = "Voice Amplification Modulator", skill = 290, spec = nil,
        components = {
            { id = 16006,  qty =  2, name = "Delicate Arcanite Converter" },
            { id = 10558,  qty =  1, name = "Gold Power Core" },
            { id = 15994,  qty =  1, name = "Thorium Widget" },
            { id = 12799,  qty =  1, name = "Blue Sapphire" },
        },
    },
    [18638] = { name = "Hyper-Radiant Flame Reflector", skill = 290, spec = nil,
        components = {
            { id = 11371,  qty =  4, name = "Dark Iron Bar" },
            { id = 18631,  qty =  3, name = "Truesilver Transformer" },
            { id = 7080,   qty =  6, name = "Essence of Water" },
            { id = 7910,   qty =  4, name = "Star Ruby" },
            { id = 12800,  qty =  2, name = "Azerothian Diamond" },
        },
    },
    [16007] = { name = "Flawless Arcanite Rifle", skill = 300, spec = nil,
        components = {
            { id = 12360,  qty = 10, name = "Arcanite Bar" },
            { id = 16000,  qty =  2, name = "Thorium Tube" },
            { id = 7078,   qty =  2, name = "Essence of Fire" },
            { id = 7076,   qty =  2, name = "Essence of Earth" },
            { id = 12800,  qty =  2, name = "Azerothian Diamond" },
            { id = 12810,  qty =  2, name = "Enchanted Leather" },
        },
    },
    [16022] = { name = "Arcanite Dragonling", skill = 300, spec = nil,
        components = {
            { id = 10576,  qty =  1, name = "Petit dragon mécanique en mithril" },
            { id = 16006,  qty =  8, name = "Delicate Arcanite Converter" },
            { id = 12655,  qty = 10, name = "Barre de thorium enchanté" },
            { id = 15994,  qty =  6, name = "Thorium Widget" },
            { id = 10558,  qty =  4, name = "Gold Power Core" },
            { id = 12810,  qty =  6, name = "Enchanted Leather" },
        },
    },
    [16040] = { name = "Arcane Bomb", skill = 300, spec = nil,
        components = {
            { id = 16006,  qty =  1, name = "Delicate Arcanite Converter" },
            { id = 12359,  qty =  3, name = "Thorium Bar" },
            { id = 14047,  qty =  1, name = "Runecloth" },
        },
    },
    [18168] = { name = "Force Reactive Disk", skill = 300, spec = nil,
        components = {
            { id = 12360,  qty =  6, name = "Arcanite Bar" },
            { id = 16006,  qty =  2, name = "Delicate Arcanite Converter" },
            { id = 7082,   qty =  8, name = "Essence of Air" },
            { id = 12803,  qty = 12, name = "Living Essence" },
            { id = 7076,   qty =  8, name = "Essence of Earth" },
        },
    },
    [18232] = { name = "Field Repair Bot 74A", skill = 300, spec = nil,
        components = {
            { id = 12359,  qty = 12, name = "Thorium Bar" },
            { id = 8170,   qty =  4, name = "Rugged Leather" },
            { id = 7191,   qty =  1, name = "Fused Wiring" },
            { id = 7067,   qty =  2, name = "Elemental Earth" },
            { id = 7068,   qty =  1, name = "Elemental Fire" },
        },
    },
    [18282] = { name = "Core Marksman Rifle", skill = 300, spec = nil,
        components = {
            { id = 17010,  qty =  4, name = "Sulfuron Ingot" },
            { id = 17011,  qty =  2, name = "Lava Core" },
            { id = 12360,  qty =  6, name = "Arcanite Bar" },
            { id = 16006,  qty =  2, name = "Delicate Arcanite Converter" },
            { id = 16000,  qty =  2, name = "Thorium Tube" },
        },
    },
    [18283] = { name = "Biznicks 247x128 Accurascope", skill = 300, spec = nil,
        components = {
            { id = 17011,  qty =  2, name = "Lava Core" },
            { id = 7076,   qty =  2, name = "Essence of Earth" },
            { id = 16006,  qty =  4, name = "Delicate Arcanite Converter" },
            { id = 11371,  qty =  6, name = "Dark Iron Bar" },
            { id = 16000,  qty =  1, name = "Thorium Tube" },
        },
    },
    [18639] = { name = "Ultra-Flash Shadow Reflector", skill = 300, spec = nil,
        components = {
            { id = 11371,  qty =  8, name = "Dark Iron Bar" },
            { id = 18631,  qty =  4, name = "Truesilver Transformer" },
            { id = 12803,  qty =  6, name = "Living Essence" },
            { id = 12808,  qty =  4, name = "Essence de non-mort" },
            { id = 12800,  qty =  2, name = "Azerothian Diamond" },
            { id = 12799,  qty =  2, name = "Blue Sapphire" },
        },
    },
    [19998] = { name = "Bloodvine Lens", skill = 300, spec = "Gnomish",
        components = {
            { id = 19726,  qty =  5, name = "Bloodvine" },
            { id = 19774,  qty =  5, name = "Ooze Covered Thorium Vein" },
            { id = 16006,  qty =  1, name = "Delicate Arcanite Converter" },
            { id = 12804,  qty =  8, name = "Powerful Mojo" },
            { id = 12810,  qty =  4, name = "Enchanted Leather" },
        },
    },
    [19999] = { name = "Bloodvine Goggles", skill = 300, spec = "Gnomish",
        components = {
            { id = 19726,  qty =  4, name = "Bloodvine" },
            { id = 19774,  qty =  5, name = "Ooze Covered Thorium Vein" },
            { id = 16006,  qty =  2, name = "Delicate Arcanite Converter" },
            { id = 12804,  qty =  8, name = "Powerful Mojo" },
            { id = 12810,  qty =  4, name = "Enchanted Leather" },
        },
    },
}