-- Blacksmithing recipes - Source: wow-classic-items npm
-- WoW Classic Era (Interface 11508)

ProfTooltip_Blacksmithing = {

    [2852] = { name = "Copper Chain Pants", skill = 1, spec = nil,
        components = {
            { id = 2840,   qty =  4, name = "Copper Bar" },
        },
    },
    [2853] = { name = "Copper Bracers", skill = 1, spec = nil,
        components = {
            { id = 2840,   qty =  2, name = "Copper Bar" },
        },
    },
    [2862] = { name = "Rough Sharpening Stone", skill = 1, spec = nil,
        components = {
            { id = 2835,   qty =  1, name = "Rough Stone" },
        },
    },
    [3239] = { name = "Rough Weightstone", skill = 1, spec = nil,
        components = {
            { id = 2835,   qty =  1, name = "Rough Stone" },
            { id = 2589,   qty =  1, name = "Linen Cloth" },
        },
    },
    [10421] = { name = "Rough Copper Vest", skill = 1, spec = nil,
        components = {
            { id = 2840,   qty =  4, name = "Copper Bar" },
        },
    },
    [2844] = { name = "Copper Mace", skill = 15, spec = nil,
        components = {
            { id = 2840,   qty =  6, name = "Copper Bar" },
            { id = 2880,   qty =  1, name = "Weak Flux" },
            { id = 2589,   qty =  2, name = "Linen Cloth" },
        },
    },
    [2845] = { name = "Copper Axe", skill = 20, spec = nil,
        components = {
            { id = 2840,   qty =  6, name = "Copper Bar" },
            { id = 2880,   qty =  1, name = "Weak Flux" },
            { id = 2589,   qty =  2, name = "Linen Cloth" },
        },
    },
    [3469] = { name = "Copper Chain Boots", skill = 20, spec = nil,
        components = {
            { id = 2840,   qty =  8, name = "Copper Bar" },
        },
    },
    [2847] = { name = "Copper Shortsword", skill = 25, spec = nil,
        components = {
            { id = 2840,   qty =  6, name = "Copper Bar" },
            { id = 2880,   qty =  1, name = "Weak Flux" },
            { id = 2589,   qty =  2, name = "Linen Cloth" },
        },
    },
    [3470] = { name = "Rough Grinding Stone", skill = 25, spec = nil,
        components = {
            { id = 2835,   qty =  2, name = "Rough Stone" },
        },
    },
    [7166] = { name = "Copper Dagger", skill = 30, spec = nil,
        components = {
            { id = 2840,   qty =  6, name = "Copper Bar" },
            { id = 2880,   qty =  1, name = "Weak Flux" },
            { id = 3470,   qty =  1, name = "Rough Grinding Stone" },
            { id = 2318,   qty =  1, name = "Light Leather" },
        },
    },
    [7955] = { name = "Copper Claymore", skill = 30, spec = nil,
        components = {
            { id = 2840,   qty = 10, name = "Copper Bar" },
            { id = 2880,   qty =  2, name = "Weak Flux" },
            { id = 3470,   qty =  1, name = "Rough Grinding Stone" },
            { id = 2318,   qty =  1, name = "Light Leather" },
        },
    },
    [2851] = { name = "Copper Chain Belt", skill = 35, spec = nil,
        components = {
            { id = 2840,   qty =  6, name = "Copper Bar" },
        },
    },
    [3471] = { name = "Copper Chain Vest", skill = 35, spec = nil,
        components = {
            { id = 2840,   qty =  8, name = "Copper Bar" },
            { id = 3470,   qty =  2, name = "Rough Grinding Stone" },
        },
    },
    [3488] = { name = "Copper Battle Axe", skill = 35, spec = nil,
        components = {
            { id = 2840,   qty = 12, name = "Copper Bar" },
            { id = 2880,   qty =  2, name = "Weak Flux" },
            { id = 774,    qty =  2, name = "Malachite" },
            { id = 3470,   qty =  2, name = "Rough Grinding Stone" },
            { id = 2318,   qty =  2, name = "Light Leather" },
        },
    },
    [3472] = { name = "Runed Copper Gauntlets", skill = 40, spec = nil,
        components = {
            { id = 2840,   qty =  8, name = "Copper Bar" },
            { id = 3470,   qty =  2, name = "Rough Grinding Stone" },
        },
    },
    [3473] = { name = "Runed Copper Pants", skill = 45, spec = nil,
        components = {
            { id = 2840,   qty =  8, name = "Copper Bar" },
            { id = 2321,   qty =  2, name = "Fine Thread" },
            { id = 3470,   qty =  3, name = "Rough Grinding Stone" },
        },
    },
    [3474] = { name = "Gemmed Copper Gauntlets", skill = 60, spec = nil,
        components = {
            { id = 2840,   qty =  8, name = "Copper Bar" },
            { id = 818,    qty =  1, name = "Tigerseye" },
            { id = 774,    qty =  1, name = "Malachite" },
        },
    },
    [2863] = { name = "Coarse Sharpening Stone", skill = 65, spec = nil,
        components = {
            { id = 2836,   qty =  1, name = "Coarse Stone" },
        },
    },
    [3240] = { name = "Coarse Weightstone", skill = 65, spec = nil,
        components = {
            { id = 2836,   qty =  1, name = "Coarse Stone" },
            { id = 2592,   qty =  1, name = "Wool Cloth" },
        },
    },
    [6214] = { name = "Heavy Copper Maul", skill = 65, spec = nil,
        components = {
            { id = 2840,   qty = 12, name = "Copper Bar" },
            { id = 2880,   qty =  2, name = "Weak Flux" },
            { id = 2318,   qty =  2, name = "Light Leather" },
        },
    },
    [2857] = { name = "Runed Copper Belt", skill = 70, spec = nil,
        components = {
            { id = 2840,   qty = 10, name = "Copper Bar" },
        },
    },
    [3489] = { name = "Thick War Axe", skill = 70, spec = nil,
        components = {
            { id = 2840,   qty = 10, name = "Copper Bar" },
            { id = 2880,   qty =  2, name = "Weak Flux" },
            { id = 2842,   qty =  2, name = "Silver Bar" },
            { id = 3470,   qty =  2, name = "Rough Grinding Stone" },
            { id = 2318,   qty =  2, name = "Light Leather" },
        },
    },
    [3478] = { name = "Coarse Grinding Stone", skill = 75, spec = nil,
        components = {
            { id = 2836,   qty =  2, name = "Coarse Stone" },
        },
    },
    [2864] = { name = "Runed Copper Breastplate", skill = 80, spec = nil,
        components = {
            { id = 2840,   qty = 12, name = "Copper Bar" },
            { id = 1210,   qty =  1, name = "Shadowgem" },
            { id = 3470,   qty =  2, name = "Rough Grinding Stone" },
        },
    },
    [2854] = { name = "Runed Copper Bracers", skill = 90, spec = nil,
        components = {
            { id = 2840,   qty = 10, name = "Copper Bar" },
            { id = 3470,   qty =  3, name = "Rough Grinding Stone" },
        },
    },
    [3487] = { name = "Heavy Copper Broadsword", skill = 95, spec = nil,
        components = {
            { id = 2840,   qty = 14, name = "Copper Bar" },
            { id = 2880,   qty =  2, name = "Weak Flux" },
            { id = 818,    qty =  2, name = "Tigerseye" },
            { id = 2319,   qty =  2, name = "Medium Leather" },
        },
    },
    [6350] = { name = "Rough Bronze Boots", skill = 95, spec = nil,
        components = {
            { id = 2841,   qty =  6, name = "Bronze Bar" },
            { id = 3470,   qty =  6, name = "Rough Grinding Stone" },
        },
    },
    [6338] = { name = "Silver Rod", skill = 100, spec = nil,
        components = {
            { id = 2842,   qty =  1, name = "Silver Bar" },
            { id = 3470,   qty =  2, name = "Rough Grinding Stone" },
        },
    },
    [6731] = { name = "Ironforge Breastplate", skill = 100, spec = nil,
        components = {
            { id = 2840,   qty = 16, name = "Copper Bar" },
            { id = 818,    qty =  2, name = "Tigerseye" },
            { id = 3470,   qty =  3, name = "Rough Grinding Stone" },
        },
    },
    [15869] = { name = "Silver Skeleton Key", skill = 100, spec = nil,
        components = {
            { id = 2842,   qty =  1, name = "Silver Bar" },
            { id = 3470,   qty =  1, name = "Rough Grinding Stone" },
        },
    },
    [2865] = { name = "Rough Bronze Leggings", skill = 105, spec = nil,
        components = {
            { id = 2841,   qty =  6, name = "Bronze Bar" },
        },
    },
    [2866] = { name = "Rough Bronze Cuirass", skill = 105, spec = nil,
        components = {
            { id = 2841,   qty =  7, name = "Bronze Bar" },
        },
    },
    [3848] = { name = "Big Bronze Knife", skill = 105, spec = nil,
        components = {
            { id = 2841,   qty =  6, name = "Bronze Bar" },
            { id = 2880,   qty =  4, name = "Weak Flux" },
            { id = 3470,   qty =  2, name = "Rough Grinding Stone" },
            { id = 818,    qty =  1, name = "Tigerseye" },
            { id = 2319,   qty =  1, name = "Medium Leather" },
        },
    },
    [2848] = { name = "Bronze Mace", skill = 110, spec = nil,
        components = {
            { id = 2841,   qty =  6, name = "Bronze Bar" },
            { id = 2880,   qty =  4, name = "Weak Flux" },
            { id = 2319,   qty =  1, name = "Medium Leather" },
        },
    },
    [3480] = { name = "Rough Bronze Shoulders", skill = 110, spec = nil,
        components = {
            { id = 2841,   qty =  5, name = "Bronze Bar" },
            { id = 3478,   qty =  1, name = "Coarse Grinding Stone" },
        },
    },
    [5540] = { name = "Pearl-handled Dagger", skill = 110, spec = nil,
        components = {
            { id = 2841,   qty =  6, name = "Bronze Bar" },
            { id = 3466,   qty =  1, name = "Strong Flux" },
            { id = 5498,   qty =  2, name = "Small Lustrous Pearl" },
            { id = 3478,   qty =  2, name = "Coarse Grinding Stone" },
        },
    },
    [2849] = { name = "Bronze Axe", skill = 115, spec = nil,
        components = {
            { id = 2841,   qty =  7, name = "Bronze Bar" },
            { id = 2880,   qty =  4, name = "Weak Flux" },
            { id = 2319,   qty =  1, name = "Medium Leather" },
        },
    },
    [2850] = { name = "Bronze Shortsword", skill = 120, spec = nil,
        components = {
            { id = 2841,   qty =  5, name = "Bronze Bar" },
            { id = 2880,   qty =  4, name = "Weak Flux" },
            { id = 2319,   qty =  2, name = "Medium Leather" },
        },
    },
    [2868] = { name = "Patterned Bronze Bracers", skill = 120, spec = nil,
        components = {
            { id = 2841,   qty =  5, name = "Bronze Bar" },
            { id = 3478,   qty =  2, name = "Coarse Grinding Stone" },
        },
    },
    [2871] = { name = "Heavy Sharpening Stone", skill = 125, spec = nil,
        components = {
            { id = 2838,   qty =  1, name = "Heavy Stone" },
        },
    },
    [3241] = { name = "Heavy Weightstone", skill = 125, spec = nil,
        components = {
            { id = 2838,   qty =  1, name = "Heavy Stone" },
            { id = 2592,   qty =  1, name = "Wool Cloth" },
        },
    },
    [3481] = { name = "Silvered Bronze Shoulders", skill = 125, spec = nil,
        components = {
            { id = 2841,   qty =  8, name = "Bronze Bar" },
            { id = 2842,   qty =  2, name = "Silver Bar" },
            { id = 3478,   qty =  2, name = "Coarse Grinding Stone" },
        },
    },
    [3486] = { name = "Heavy Grinding Stone", skill = 125, spec = nil,
        components = {
            { id = 2838,   qty =  3, name = "Heavy Stone" },
        },
    },
    [3490] = { name = "Deadly Bronze Poniard", skill = 125, spec = nil,
        components = {
            { id = 2841,   qty =  4, name = "Bronze Bar" },
            { id = 3466,   qty =  1, name = "Strong Flux" },
            { id = 2459,   qty =  1, name = "Swiftness Potion" },
            { id = 1210,   qty =  2, name = "Shadowgem" },
            { id = 3478,   qty =  2, name = "Coarse Grinding Stone" },
            { id = 2319,   qty =  2, name = "Medium Leather" },
        },
    },
    [7956] = { name = "Bronze Warhammer", skill = 125, spec = nil,
        components = {
            { id = 2841,   qty =  8, name = "Bronze Bar" },
            { id = 3466,   qty =  1, name = "Strong Flux" },
            { id = 2319,   qty =  1, name = "Medium Leather" },
        },
    },
    [2869] = { name = "Silvered Bronze Breastplate", skill = 130, spec = nil,
        components = {
            { id = 2841,   qty = 10, name = "Bronze Bar" },
            { id = 2842,   qty =  2, name = "Silver Bar" },
            { id = 3478,   qty =  2, name = "Coarse Grinding Stone" },
        },
    },
    [3482] = { name = "Silvered Bronze Boots", skill = 130, spec = nil,
        components = {
            { id = 2841,   qty =  6, name = "Bronze Bar" },
            { id = 2842,   qty =  1, name = "Silver Bar" },
            { id = 3478,   qty =  2, name = "Coarse Grinding Stone" },
        },
    },
    [3491] = { name = "Heavy Bronze Mace", skill = 130, spec = nil,
        components = {
            { id = 2841,   qty =  8, name = "Bronze Bar" },
            { id = 3466,   qty =  1, name = "Strong Flux" },
            { id = 1206,   qty =  1, name = "Moss Agate" },
            { id = 1210,   qty =  1, name = "Shadowgem" },
            { id = 3478,   qty =  2, name = "Coarse Grinding Stone" },
            { id = 2319,   qty =  2, name = "Medium Leather" },
        },
    },
    [7957] = { name = "Bronze Greatsword", skill = 130, spec = nil,
        components = {
            { id = 2841,   qty = 12, name = "Bronze Bar" },
            { id = 3466,   qty =  2, name = "Strong Flux" },
            { id = 2319,   qty =  2, name = "Medium Leather" },
        },
    },
    [3483] = { name = "Silvered Bronze Gauntlets", skill = 135, spec = nil,
        components = {
            { id = 2841,   qty =  8, name = "Bronze Bar" },
            { id = 2842,   qty =  1, name = "Silver Bar" },
            { id = 3478,   qty =  2, name = "Coarse Grinding Stone" },
        },
    },
    [7958] = { name = "Bronze Battle Axe", skill = 135, spec = nil,
        components = {
            { id = 2841,   qty = 14, name = "Bronze Bar" },
            { id = 3466,   qty =  1, name = "Strong Flux" },
            { id = 2319,   qty =  2, name = "Medium Leather" },
        },
    },
    [5541] = { name = "Iridescent Hammer", skill = 140, spec = nil,
        components = {
            { id = 2841,   qty = 10, name = "Bronze Bar" },
            { id = 3466,   qty =  1, name = "Strong Flux" },
            { id = 5500,   qty =  1, name = "Iridescent Pearl" },
            { id = 3478,   qty =  2, name = "Coarse Grinding Stone" },
            { id = 2319,   qty =  2, name = "Medium Leather" },
        },
    },
    [2870] = { name = "Shining Silver Breastplate", skill = 145, spec = nil,
        components = {
            { id = 2841,   qty = 20, name = "Bronze Bar" },
            { id = 1206,   qty =  2, name = "Moss Agate" },
            { id = 1705,   qty =  2, name = "Lesser Moonstone" },
            { id = 5500,   qty =  2, name = "Iridescent Pearl" },
            { id = 2842,   qty =  4, name = "Silver Bar" },
        },
    },
    [3484] = { name = "Green Iron Boots", skill = 145, spec = nil,
        components = {
            { id = 3575,   qty =  6, name = "Iron Bar" },
            { id = 3478,   qty =  2, name = "Coarse Grinding Stone" },
            { id = 2605,   qty =  1, name = "Green Dye" },
        },
    },
    [3492] = { name = "Mighty Iron Hammer", skill = 145, spec = nil,
        components = {
            { id = 3575,   qty =  6, name = "Iron Bar" },
            { id = 3466,   qty =  2, name = "Strong Flux" },
            { id = 3391,   qty =  1, name = "Elixir of Ogre's Strength" },
            { id = 1705,   qty =  2, name = "Lesser Moonstone" },
            { id = 3478,   qty =  2, name = "Coarse Grinding Stone" },
            { id = 2319,   qty =  2, name = "Medium Leather" },
        },
    },
    [3485] = { name = "Green Iron Gauntlets", skill = 150, spec = nil,
        components = {
            { id = 3575,   qty =  4, name = "Iron Bar" },
            { id = 5498,   qty =  2, name = "Small Lustrous Pearl" },
            { id = 3478,   qty =  2, name = "Coarse Grinding Stone" },
            { id = 2605,   qty =  1, name = "Green Dye" },
        },
    },
    [6042] = { name = "Iron Shield Spike", skill = 150, spec = nil,
        components = {
            { id = 3575,   qty =  6, name = "Iron Bar" },
            { id = 3478,   qty =  4, name = "Coarse Grinding Stone" },
        },
    },
    [7071] = { name = "Iron Buckle", skill = 150, spec = nil,
        components = {
            { id = 3575,   qty =  1, name = "Iron Bar" },
        },
    },
    [11128] = { name = "Golden Rod", skill = 150, spec = nil,
        components = {
            { id = 3577,   qty =  1, name = "Gold Bar" },
            { id = 3478,   qty =  2, name = "Coarse Grinding Stone" },
        },
    },
    [15870] = { name = "Golden Skeleton Key", skill = 150, spec = nil,
        components = {
            { id = 3577,   qty =  1, name = "Gold Bar" },
            { id = 3486,   qty =  1, name = "Heavy Grinding Stone" },
        },
    },
    [3842] = { name = "Green Iron Leggings", skill = 155, spec = nil,
        components = {
            { id = 3575,   qty =  8, name = "Iron Bar" },
            { id = 3486,   qty =  1, name = "Heavy Grinding Stone" },
            { id = 2605,   qty =  1, name = "Green Dye" },
        },
    },
    [3851] = { name = "Solid Iron Maul", skill = 155, spec = nil,
        components = {
            { id = 3575,   qty =  8, name = "Iron Bar" },
            { id = 3466,   qty =  2, name = "Strong Flux" },
            { id = 3486,   qty =  1, name = "Heavy Grinding Stone" },
            { id = 2842,   qty =  4, name = "Silver Bar" },
            { id = 4234,   qty =  2, name = "Heavy Leather" },
        },
    },
    [10423] = { name = "Silvered Bronze Leggings", skill = 155, spec = nil,
        components = {
            { id = 2841,   qty = 12, name = "Bronze Bar" },
            { id = 2842,   qty =  4, name = "Silver Bar" },
            { id = 3478,   qty =  2, name = "Coarse Grinding Stone" },
        },
    },
    [3840] = { name = "Green Iron Shoulders", skill = 160, spec = nil,
        components = {
            { id = 3575,   qty =  7, name = "Iron Bar" },
            { id = 3486,   qty =  1, name = "Heavy Grinding Stone" },
            { id = 2605,   qty =  1, name = "Green Dye" },
        },
    },
    [3849] = { name = "Hardened Iron Shortsword", skill = 160, spec = nil,
        components = {
            { id = 3575,   qty =  6, name = "Iron Bar" },
            { id = 3466,   qty =  2, name = "Strong Flux" },
            { id = 3486,   qty =  1, name = "Heavy Grinding Stone" },
            { id = 1705,   qty =  2, name = "Lesser Moonstone" },
            { id = 4234,   qty =  3, name = "Heavy Leather" },
        },
    },
    [7913] = { name = "Barbaric Iron Shoulders", skill = 160, spec = nil,
        components = {
            { id = 3575,   qty =  8, name = "Iron Bar" },
            { id = 5635,   qty =  4, name = "Sharp Claw" },
            { id = 3486,   qty =  2, name = "Heavy Grinding Stone" },
        },
    },
    [7914] = { name = "Barbaric Iron Breastplate", skill = 160, spec = nil,
        components = {
            { id = 3575,   qty = 20, name = "Iron Bar" },
            { id = 3486,   qty =  4, name = "Heavy Grinding Stone" },
        },
    },
    [3835] = { name = "Green Iron Bracers", skill = 165, spec = nil,
        components = {
            { id = 3575,   qty =  6, name = "Iron Bar" },
            { id = 2605,   qty =  1, name = "Green Dye" },
        },
    },
    [6043] = { name = "Iron Counterweight", skill = 165, spec = nil,
        components = {
            { id = 3575,   qty =  4, name = "Iron Bar" },
            { id = 3478,   qty =  2, name = "Coarse Grinding Stone" },
            { id = 1705,   qty =  1, name = "Lesser Moonstone" },
        },
    },
    [3836] = { name = "Green Iron Helm", skill = 170, spec = nil,
        components = {
            { id = 3575,   qty = 12, name = "Iron Bar" },
            { id = 3864,   qty =  1, name = "Citrine" },
            { id = 2605,   qty =  1, name = "Green Dye" },
        },
    },
    [3843] = { name = "Golden Scale Leggings", skill = 170, spec = nil,
        components = {
            { id = 3575,   qty = 10, name = "Iron Bar" },
            { id = 3577,   qty =  2, name = "Gold Bar" },
            { id = 3486,   qty =  1, name = "Heavy Grinding Stone" },
        },
    },
    [3852] = { name = "Golden Iron Destroyer", skill = 170, spec = nil,
        components = {
            { id = 3575,   qty = 10, name = "Iron Bar" },
            { id = 3577,   qty =  4, name = "Gold Bar" },
            { id = 1705,   qty =  2, name = "Lesser Moonstone" },
            { id = 3466,   qty =  2, name = "Strong Flux" },
            { id = 4234,   qty =  2, name = "Heavy Leather" },
            { id = 3486,   qty =  2, name = "Heavy Grinding Stone" },
        },
    },
    [3841] = { name = "Golden Scale Shoulders", skill = 175, spec = nil,
        components = {
            { id = 3859,   qty =  6, name = "Steel Bar" },
            { id = 3577,   qty =  2, name = "Gold Bar" },
            { id = 3486,   qty =  1, name = "Heavy Grinding Stone" },
        },
    },
    [3850] = { name = "Jade Serpentblade", skill = 175, spec = nil,
        components = {
            { id = 3575,   qty =  8, name = "Iron Bar" },
            { id = 3466,   qty =  2, name = "Strong Flux" },
            { id = 3486,   qty =  2, name = "Heavy Grinding Stone" },
            { id = 1529,   qty =  2, name = "Jade" },
            { id = 4234,   qty =  3, name = "Heavy Leather" },
        },
    },
    [7915] = { name = "Barbaric Iron Helm", skill = 175, spec = nil,
        components = {
            { id = 3575,   qty = 10, name = "Iron Bar" },
            { id = 5637,   qty =  2, name = "Large Fang" },
            { id = 5635,   qty =  2, name = "Sharp Claw" },
        },
    },
    [3844] = { name = "Green Iron Hauberk", skill = 180, spec = nil,
        components = {
            { id = 3575,   qty = 20, name = "Iron Bar" },
            { id = 3486,   qty =  4, name = "Heavy Grinding Stone" },
            { id = 1529,   qty =  2, name = "Jade" },
            { id = 1206,   qty =  2, name = "Moss Agate" },
            { id = 4255,   qty =  1, name = "Green Leather Armor" },
        },
    },
    [3853] = { name = "Moonsteel Broadsword", skill = 180, spec = nil,
        components = {
            { id = 3859,   qty =  8, name = "Steel Bar" },
            { id = 3466,   qty =  2, name = "Strong Flux" },
            { id = 3486,   qty =  2, name = "Heavy Grinding Stone" },
            { id = 1705,   qty =  3, name = "Lesser Moonstone" },
            { id = 4234,   qty =  3, name = "Heavy Leather" },
        },
    },
    [7916] = { name = "Barbaric Iron Boots", skill = 180, spec = nil,
        components = {
            { id = 3575,   qty = 12, name = "Iron Bar" },
            { id = 5637,   qty =  4, name = "Large Fang" },
            { id = 3486,   qty =  2, name = "Heavy Grinding Stone" },
        },
    },
    [12259] = { name = "Glinting Steel Dagger", skill = 180, spec = nil,
        components = {
            { id = 3859,   qty = 10, name = "Steel Bar" },
            { id = 3466,   qty =  2, name = "Strong Flux" },
            { id = 1206,   qty =  1, name = "Moss Agate" },
            { id = 7067,   qty =  1, name = "Elemental Earth" },
            { id = 4234,   qty =  1, name = "Heavy Leather" },
        },
    },
    [3846] = { name = "Polished Steel Boots", skill = 185, spec = nil,
        components = {
            { id = 3859,   qty =  8, name = "Steel Bar" },
            { id = 3864,   qty =  1, name = "Citrine" },
            { id = 1705,   qty =  1, name = "Lesser Moonstone" },
            { id = 3486,   qty =  2, name = "Heavy Grinding Stone" },
        },
    },
    [3855] = { name = "Massive Iron Axe", skill = 185, spec = nil,
        components = {
            { id = 3575,   qty = 14, name = "Iron Bar" },
            { id = 3466,   qty =  2, name = "Strong Flux" },
            { id = 3486,   qty =  2, name = "Heavy Grinding Stone" },
            { id = 3577,   qty =  4, name = "Gold Bar" },
            { id = 4234,   qty =  2, name = "Heavy Leather" },
        },
    },
    [6040] = { name = "Golden Scale Bracers", skill = 185, spec = nil,
        components = {
            { id = 3859,   qty =  5, name = "Steel Bar" },
            { id = 3486,   qty =  2, name = "Heavy Grinding Stone" },
        },
    },
    [7917] = { name = "Barbaric Iron Gloves", skill = 185, spec = nil,
        components = {
            { id = 3575,   qty = 14, name = "Iron Bar" },
            { id = 3486,   qty =  3, name = "Heavy Grinding Stone" },
            { id = 5637,   qty =  2, name = "Large Fang" },
        },
    },
    [3837] = { name = "Golden Scale Coif", skill = 190, spec = nil,
        components = {
            { id = 3859,   qty =  8, name = "Steel Bar" },
            { id = 3577,   qty =  2, name = "Gold Bar" },
            { id = 3486,   qty =  2, name = "Heavy Grinding Stone" },
        },
    },
    [6041] = { name = "Steel Weapon Chain", skill = 190, spec = nil,
        components = {
            { id = 3859,   qty =  8, name = "Steel Bar" },
            { id = 3486,   qty =  2, name = "Heavy Grinding Stone" },
            { id = 4234,   qty =  4, name = "Heavy Leather" },
        },
    },
    [12260] = { name = "Searing Golden Blade", skill = 190, spec = nil,
        components = {
            { id = 3859,   qty = 10, name = "Steel Bar" },
            { id = 3577,   qty =  4, name = "Gold Bar" },
            { id = 7068,   qty =  2, name = "Elemental Fire" },
            { id = 4234,   qty =  2, name = "Heavy Leather" },
        },
    },
    [17704] = { name = "Edge of Winter", skill = 190, spec = nil,
        components = {
            { id = 3859,   qty = 10, name = "Steel Bar" },
            { id = 3829,   qty =  1, name = "Frost Oil" },
            { id = 7070,   qty =  2, name = "Elemental Water" },
            { id = 7069,   qty =  2, name = "Elemental Air" },
            { id = 4234,   qty =  2, name = "Heavy Leather" },
        },
    },
    [3845] = { name = "Golden Scale Cuirass", skill = 195, spec = nil,
        components = {
            { id = 3859,   qty = 12, name = "Steel Bar" },
            { id = 3577,   qty =  2, name = "Gold Bar" },
            { id = 3486,   qty =  4, name = "Heavy Grinding Stone" },
        },
    },
    [3847] = { name = "Golden Scale Boots", skill = 200, spec = nil,
        components = {
            { id = 3859,   qty = 10, name = "Steel Bar" },
            { id = 3577,   qty =  4, name = "Gold Bar" },
            { id = 3486,   qty =  4, name = "Heavy Grinding Stone" },
        },
    },
    [3854] = { name = "Frost Tiger Blade", skill = 200, spec = nil,
        components = {
            { id = 3859,   qty = 12, name = "Steel Bar" },
            { id = 1529,   qty =  2, name = "Jade" },
            { id = 3829,   qty =  2, name = "Frost Oil" },
        },
    },
    [3856] = { name = "Shadow Crescent Axe", skill = 200, spec = nil,
        components = {
            { id = 3859,   qty = 10, name = "Steel Bar" },
            { id = 3864,   qty =  2, name = "Citrine" },
            { id = 3824,   qty =  2, name = "Shadow Oil" },
        },
    },
    [7963] = { name = "Steel Breastplate", skill = 200, spec = nil,
        components = {
            { id = 3859,   qty = 16, name = "Steel Bar" },
            { id = 3486,   qty =  3, name = "Heavy Grinding Stone" },
        },
    },
    [7964] = { name = "Solid Sharpening Stone", skill = 200, spec = "Arms",
        components = {
            { id = 7912,   qty =  1, name = "Solid Stone" },
        },
    },
    [7965] = { name = "Solid Weightstone", skill = 200, spec = nil,
        components = {
            { id = 7912,   qty =  1, name = "Solid Stone" },
            { id = 4306,   qty =  1, name = "Silk Cloth" },
        },
    },
    [7966] = { name = "Solid Grinding Stone", skill = 200, spec = nil,
        components = {
            { id = 7912,   qty =  4, name = "Solid Stone" },
        },
    },
    [9060] = { name = "Inlaid Mithril Cylinder", skill = 200, spec = nil,
        components = {
            { id = 3860,   qty =  5, name = "Mithril Bar" },
            { id = 3577,   qty =  1, name = "Gold Bar" },
            { id = 6037,   qty =  1, name = "Truesilver Bar" },
        },
    },
    [11144] = { name = "Truesilver Rod", skill = 200, spec = nil,
        components = {
            { id = 6037,   qty =  1, name = "Truesilver Bar" },
            { id = 3486,   qty =  1, name = "Heavy Grinding Stone" },
        },
    },
    [15871] = { name = "Truesilver Skeleton Key", skill = 200, spec = nil,
        components = {
            { id = 6037,   qty =  1, name = "Truesilver Bar" },
            { id = 7966,   qty =  1, name = "Solid Grinding Stone" },
        },
    },
    [7918] = { name = "Heavy Mithril Shoulder", skill = 205, spec = nil,
        components = {
            { id = 3860,   qty =  8, name = "Mithril Bar" },
            { id = 4234,   qty =  6, name = "Heavy Leather" },
        },
    },
    [7919] = { name = "Heavy Mithril Gauntlet", skill = 205, spec = nil,
        components = {
            { id = 3860,   qty =  6, name = "Mithril Bar" },
            { id = 4338,   qty =  4, name = "Mageweave Cloth" },
        },
    },
    [9366] = { name = "Golden Scale Gauntlets", skill = 205, spec = nil,
        components = {
            { id = 3859,   qty = 10, name = "Steel Bar" },
            { id = 3577,   qty =  4, name = "Gold Bar" },
            { id = 3486,   qty =  4, name = "Heavy Grinding Stone" },
        },
    },
    [7920] = { name = "Mithril Scale Pants", skill = 210, spec = nil,
        components = {
            { id = 3860,   qty = 12, name = "Mithril Bar" },
        },
    },
    [7921] = { name = "Heavy Mithril Pants", skill = 210, spec = nil,
        components = {
            { id = 3860,   qty = 10, name = "Mithril Bar" },
        },
    },
    [7941] = { name = "Heavy Mithril Axe", skill = 210, spec = nil,
        components = {
            { id = 3860,   qty = 12, name = "Mithril Bar" },
            { id = 3864,   qty =  2, name = "Citrine" },
            { id = 7966,   qty =  1, name = "Solid Grinding Stone" },
            { id = 4234,   qty =  4, name = "Heavy Leather" },
        },
    },
    [7922] = { name = "Steel Plate Helm", skill = 215, spec = nil,
        components = {
            { id = 3859,   qty = 14, name = "Steel Bar" },
            { id = 3864,   qty =  1, name = "Citrine" },
            { id = 7966,   qty =  1, name = "Solid Grinding Stone" },
        },
    },
    [7924] = { name = "Mithril Scale Bracers", skill = 215, spec = nil,
        components = {
            { id = 3860,   qty =  8, name = "Mithril Bar" },
        },
    },
    [7967] = { name = "Mithril Shield Spike", skill = 215, spec = nil,
        components = {
            { id = 3860,   qty =  4, name = "Mithril Bar" },
            { id = 6037,   qty =  2, name = "Truesilver Bar" },
            { id = 7966,   qty =  4, name = "Solid Grinding Stone" },
        },
    },
    [7926] = { name = "Ornate Mithril Pants", skill = 220, spec = nil,
        components = {
            { id = 3860,   qty = 12, name = "Mithril Bar" },
            { id = 6037,   qty =  1, name = "Truesilver Bar" },
            { id = 7966,   qty =  1, name = "Solid Grinding Stone" },
        },
    },
    [7927] = { name = "Ornate Mithril Gloves", skill = 220, spec = nil,
        components = {
            { id = 3860,   qty = 10, name = "Mithril Bar" },
            { id = 4338,   qty =  6, name = "Mageweave Cloth" },
            { id = 6037,   qty =  1, name = "Truesilver Bar" },
            { id = 7966,   qty =  1, name = "Solid Grinding Stone" },
        },
    },
    [7942] = { name = "Blue Glittering Axe", skill = 220, spec = nil,
        components = {
            { id = 3860,   qty = 16, name = "Mithril Bar" },
            { id = 7909,   qty =  2, name = "Aquamarine" },
            { id = 7966,   qty =  1, name = "Solid Grinding Stone" },
            { id = 4304,   qty =  4, name = "Thick Leather" },
        },
    },
    [7928] = { name = "Ornate Mithril Shoulder", skill = 225, spec = nil,
        components = {
            { id = 3860,   qty = 12, name = "Mithril Bar" },
            { id = 6037,   qty =  1, name = "Truesilver Bar" },
            { id = 4304,   qty =  6, name = "Thick Leather" },
        },
    },
    [7938] = { name = "Truesilver Gauntlets", skill = 225, spec = nil,
        components = {
            { id = 3860,   qty = 10, name = "Mithril Bar" },
            { id = 6037,   qty =  8, name = "Truesilver Bar" },
            { id = 7909,   qty =  3, name = "Aquamarine" },
            { id = 3864,   qty =  3, name = "Citrine" },
            { id = 5966,   qty =  1, name = "Guardian Gloves" },
            { id = 7966,   qty =  2, name = "Solid Grinding Stone" },
        },
    },
    [7943] = { name = "Wicked Mithril Blade", skill = 225, spec = nil,
        components = {
            { id = 3860,   qty = 14, name = "Mithril Bar" },
            { id = 6037,   qty =  4, name = "Truesilver Bar" },
            { id = 7966,   qty =  1, name = "Solid Grinding Stone" },
            { id = 4304,   qty =  2, name = "Thick Leather" },
        },
    },
    [7929] = { name = "Orcish War Leggings", skill = 230, spec = nil,
        components = {
            { id = 3860,   qty = 12, name = "Mithril Bar" },
            { id = 7067,   qty =  1, name = "Elemental Earth" },
        },
    },
    [7930] = { name = "Heavy Mithril Breastplate", skill = 230, spec = nil,
        components = {
            { id = 3860,   qty = 16, name = "Mithril Bar" },
        },
    },
    [7931] = { name = "Mithril Coif", skill = 230, spec = nil,
        components = {
            { id = 3860,   qty = 10, name = "Mithril Bar" },
            { id = 4338,   qty =  6, name = "Mageweave Cloth" },
        },
    },
    [7945] = { name = "Big Black Mace", skill = 230, spec = nil,
        components = {
            { id = 3860,   qty = 16, name = "Mithril Bar" },
            { id = 7971,   qty =  1, name = "Black Pearl" },
            { id = 1210,   qty =  4, name = "Shadowgem" },
            { id = 7966,   qty =  1, name = "Solid Grinding Stone" },
            { id = 4304,   qty =  2, name = "Thick Leather" },
        },
    },
    [7932] = { name = "Mithril Scale Shoulders", skill = 235, spec = nil,
        components = {
            { id = 3860,   qty = 14, name = "Mithril Bar" },
            { id = 4304,   qty =  4, name = "Thick Leather" },
        },
    },
    [7933] = { name = "Heavy Mithril Boots", skill = 235, spec = nil,
        components = {
            { id = 3860,   qty = 14, name = "Mithril Bar" },
            { id = 4304,   qty =  4, name = "Thick Leather" },
        },
    },
    [7954] = { name = "The Shatterer", skill = 235, spec = nil,
        components = {
            { id = 3860,   qty = 24, name = "Mithril Bar" },
            { id = 7075,   qty =  4, name = "Core of Earth" },
            { id = 6037,   qty =  6, name = "Truesilver Bar" },
            { id = 3864,   qty =  5, name = "Citrine" },
            { id = 1529,   qty =  5, name = "Jade" },
            { id = 7966,   qty =  4, name = "Solid Grinding Stone" },
            { id = 4304,   qty =  4, name = "Thick Leather" },
        },
    },
    [7969] = { name = "Mithril Spurs", skill = 235, spec = nil,
        components = {
            { id = 3860,   qty =  4, name = "Mithril Bar" },
            { id = 7966,   qty =  3, name = "Solid Grinding Stone" },
        },
    },
    [7935] = { name = "Ornate Mithril Breastplate", skill = 240, spec = nil,
        components = {
            { id = 3860,   qty = 16, name = "Mithril Bar" },
            { id = 6037,   qty =  6, name = "Truesilver Bar" },
            { id = 7077,   qty =  1, name = "Heart of Fire" },
            { id = 7966,   qty =  1, name = "Solid Grinding Stone" },
        },
    },
    [7944] = { name = "Dazzling Mithril Rapier", skill = 240, spec = nil,
        components = {
            { id = 3860,   qty = 14, name = "Mithril Bar" },
            { id = 7909,   qty =  1, name = "Aquamarine" },
            { id = 1705,   qty =  2, name = "Lesser Moonstone" },
            { id = 1206,   qty =  2, name = "Moss Agate" },
            { id = 7966,   qty =  1, name = "Solid Grinding Stone" },
            { id = 4338,   qty =  2, name = "Mageweave Cloth" },
        },
    },
    [7934] = { name = "Heavy Mithril Helm", skill = 245, spec = nil,
        components = {
            { id = 3860,   qty = 14, name = "Mithril Bar" },
            { id = 7909,   qty =  1, name = "Aquamarine" },
        },
    },
    [7936] = { name = "Ornate Mithril Boots", skill = 245, spec = nil,
        components = {
            { id = 3860,   qty = 14, name = "Mithril Bar" },
            { id = 6037,   qty =  2, name = "Truesilver Bar" },
            { id = 4304,   qty =  4, name = "Thick Leather" },
            { id = 7966,   qty =  1, name = "Solid Grinding Stone" },
            { id = 7909,   qty =  1, name = "Aquamarine" },
        },
    },
    [7937] = { name = "Ornate Mithril Helm", skill = 245, spec = nil,
        components = {
            { id = 3860,   qty = 16, name = "Mithril Bar" },
            { id = 6037,   qty =  2, name = "Truesilver Bar" },
            { id = 7966,   qty =  1, name = "Solid Grinding Stone" },
        },
    },
    [7939] = { name = "Truesilver Breastplate", skill = 245, spec = nil,
        components = {
            { id = 3860,   qty = 12, name = "Mithril Bar" },
            { id = 6037,   qty = 12, name = "Truesilver Bar" },
            { id = 7910,   qty =  2, name = "Star Ruby" },
            { id = 7971,   qty =  2, name = "Black Pearl" },
            { id = 7966,   qty =  2, name = "Solid Grinding Stone" },
        },
    },
    [7946] = { name = "Runed Mithril Hammer", skill = 245, spec = nil,
        components = {
            { id = 3860,   qty = 18, name = "Mithril Bar" },
            { id = 7075,   qty =  2, name = "Core of Earth" },
            { id = 7966,   qty =  1, name = "Solid Grinding Stone" },
            { id = 4304,   qty =  4, name = "Thick Leather" },
        },
    },
    [7961] = { name = "Phantom Blade", skill = 245, spec = nil,
        components = {
            { id = 3860,   qty = 28, name = "Mithril Bar" },
            { id = 7081,   qty =  6, name = "Breath of Wind" },
            { id = 6037,   qty =  8, name = "Truesilver Bar" },
            { id = 3823,   qty =  2, name = "Lesser Invisibility Potion" },
            { id = 7909,   qty =  6, name = "Aquamarine" },
            { id = 7966,   qty =  4, name = "Solid Grinding Stone" },
            { id = 4304,   qty =  2, name = "Thick Leather" },
        },
    },
    [7959] = { name = "Blight", skill = 250, spec = nil,
        components = {
            { id = 3860,   qty = 28, name = "Mithril Bar" },
            { id = 7972,   qty = 10, name = "Ichor of Undeath" },
            { id = 6037,   qty = 10, name = "Truesilver Bar" },
            { id = 7966,   qty =  6, name = "Solid Grinding Stone" },
            { id = 4304,   qty =  6, name = "Thick Leather" },
        },
    },
    [12404] = { name = "Dense Sharpening Stone", skill = 250, spec = nil,
        components = {
            { id = 12365,  qty =  1, name = "Dense Stone" },
        },
    },
    [12405] = { name = "Thorium Armor", skill = 250, spec = nil,
        components = {
            { id = 12359,  qty = 16, name = "Thorium Bar" },
            { id = 12361,  qty =  1, name = "Blue Sapphire" },
        },
    },
    [12406] = { name = "Thorium Belt", skill = 250, spec = nil,
        components = {
            { id = 12359,  qty =  8, name = "Thorium Bar" },
        },
    },
    [12643] = { name = "Dense Weightstone", skill = 250, spec = nil,
        components = {
            { id = 12365,  qty =  1, name = "Dense Stone" },
            { id = 14047,  qty =  1, name = "Runecloth" },
        },
    },
    [12644] = { name = "Dense Grinding Stone", skill = 250, spec = nil,
        components = {
            { id = 12365,  qty =  4, name = "Dense Stone" },
        },
    },
    [7947] = { name = "Ebon Shiv", skill = 255, spec = nil,
        components = {
            { id = 3860,   qty = 12, name = "Mithril Bar" },
            { id = 6037,   qty =  6, name = "Truesilver Bar" },
            { id = 7910,   qty =  2, name = "Star Ruby" },
            { id = 7966,   qty =  1, name = "Solid Grinding Stone" },
            { id = 4304,   qty =  2, name = "Thick Leather" },
        },
    },
    [12408] = { name = "Thorium Bracers", skill = 255, spec = nil,
        components = {
            { id = 12359,  qty =  8, name = "Thorium Bar" },
        },
    },
    [7960] = { name = "Truesilver Champion", skill = 260, spec = nil,
        components = {
            { id = 3860,   qty = 30, name = "Mithril Bar" },
            { id = 6037,   qty = 16, name = "Truesilver Bar" },
            { id = 7910,   qty =  6, name = "Star Ruby" },
            { id = 7081,   qty =  4, name = "Breath of Wind" },
            { id = 7966,   qty =  8, name = "Solid Grinding Stone" },
            { id = 4304,   qty =  6, name = "Thick Leather" },
        },
    },
    [12416] = { name = "Radiant Belt", skill = 260, spec = nil,
        components = {
            { id = 12359,  qty = 10, name = "Thorium Bar" },
            { id = 7077,   qty =  2, name = "Heart of Fire" },
        },
    },
    [11608] = { name = "Dark Iron Pulverizer", skill = 265, spec = nil,
        components = {
            { id = 11371,  qty = 18, name = "Dark Iron Bar" },
            { id = 7077,   qty =  4, name = "Heart of Fire" },
        },
    },
    [12424] = { name = "Imperial Plate Belt", skill = 265, spec = "Weap",
        components = {
            { id = 12359,  qty = 10, name = "Thorium Bar" },
            { id = 8170,   qty =  6, name = "Rugged Leather" },
        },
    },
    [12428] = { name = "Imperial Plate Shoulders", skill = 265, spec = "Weap",
        components = {
            { id = 12359,  qty = 12, name = "Thorium Bar" },
            { id = 8170,   qty =  6, name = "Rugged Leather" },
        },
    },
    [11606] = { name = "Dark Iron Mail", skill = 270, spec = nil,
        components = {
            { id = 11371,  qty = 10, name = "Dark Iron Bar" },
            { id = 7077,   qty =  2, name = "Heart of Fire" },
        },
    },
    [12415] = { name = "Radiant Breastplate", skill = 270, spec = nil,
        components = {
            { id = 12359,  qty = 18, name = "Thorium Bar" },
            { id = 7077,   qty =  2, name = "Heart of Fire" },
            { id = 7910,   qty =  1, name = "Star Ruby" },
        },
    },
    [12425] = { name = "Imperial Plate Bracers", skill = 270, spec = "Arms",
        components = {
            { id = 12359,  qty = 12, name = "Thorium Bar" },
        },
    },
    [12624] = { name = "Wildthorn Mail", skill = 270, spec = nil,
        components = {
            { id = 12359,  qty = 40, name = "Thorium Bar" },
            { id = 12655,  qty =  2, name = "Enchanted Thorium Bar" },
            { id = 12803,  qty =  4, name = "Living Essence" },
            { id = 8153,   qty =  4, name = "Wildvine" },
            { id = 12364,  qty =  1, name = "Huge Emerald" },
        },
    },
    [11607] = { name = "Dark Iron Sunderer", skill = 275, spec = nil,
        components = {
            { id = 11371,  qty = 26, name = "Dark Iron Bar" },
            { id = 7077,   qty =  4, name = "Heart of Fire" },
        },
    },
    [12645] = { name = "Thorium Shield Spike", skill = 275, spec = nil,
        components = {
            { id = 12359,  qty =  4, name = "Thorium Bar" },
            { id = 12644,  qty =  4, name = "Dense Grinding Stone" },
            { id = 7076,   qty =  2, name = "Essence of Earth" },
        },
    },
    [12773] = { name = "Ornate Thorium Handaxe", skill = 275, spec = nil,
        components = {
            { id = 12359,  qty = 10, name = "Thorium Bar" },
            { id = 12799,  qty =  2, name = "Large Opal" },
            { id = 12644,  qty =  2, name = "Dense Grinding Stone" },
            { id = 8170,   qty =  4, name = "Rugged Leather" },
        },
    },
    [12774] = { name = "Dawn's Edge", skill = 275, spec = nil,
        components = {
            { id = 12359,  qty = 30, name = "Thorium Bar" },
            { id = 12655,  qty =  4, name = "Enchanted Thorium Bar" },
            { id = 7910,   qty =  4, name = "Star Ruby" },
            { id = 12361,  qty =  4, name = "Blue Sapphire" },
            { id = 12644,  qty =  2, name = "Dense Grinding Stone" },
            { id = 8170,   qty =  4, name = "Rugged Leather" },
        },
    },
    [15872] = { name = "Arcanite Skeleton Key", skill = 275, spec = nil,
        components = {
            { id = 12360,  qty =  1, name = "Arcanite Bar" },
            { id = 12644,  qty =  1, name = "Dense Grinding Stone" },
        },
    },
    [16206] = { name = "Arcanite Rod", skill = 275, spec = nil,
        components = {
            { id = 12360,  qty =  3, name = "Arcanite Bar" },
            { id = 12644,  qty =  1, name = "Dense Grinding Stone" },
        },
    },
    [11605] = { name = "Dark Iron Shoulders", skill = 280, spec = nil,
        components = {
            { id = 11371,  qty =  6, name = "Dark Iron Bar" },
            { id = 7077,   qty =  1, name = "Heart of Fire" },
        },
    },
    [12409] = { name = "Thorium Boots", skill = 280, spec = nil,
        components = {
            { id = 12359,  qty = 12, name = "Thorium Bar" },
            { id = 8170,   qty =  8, name = "Rugged Leather" },
        },
    },
    [12410] = { name = "Thorium Helm", skill = 280, spec = nil,
        components = {
            { id = 12359,  qty = 12, name = "Thorium Bar" },
            { id = 7910,   qty =  1, name = "Star Ruby" },
        },
    },
    [12775] = { name = "Huge Thorium Battleaxe", skill = 280, spec = nil,
        components = {
            { id = 12359,  qty = 12, name = "Thorium Bar" },
            { id = 12644,  qty =  6, name = "Dense Grinding Stone" },
            { id = 8170,   qty =  6, name = "Rugged Leather" },
        },
    },
    [12776] = { name = "Enchanted Battlehammer", skill = 280, spec = nil,
        components = {
            { id = 12359,  qty = 20, name = "Thorium Bar" },
            { id = 12655,  qty =  6, name = "Enchanted Thorium Bar" },
            { id = 12364,  qty =  2, name = "Huge Emerald" },
            { id = 12804,  qty =  4, name = "Powerful Mojo" },
            { id = 8170,   qty =  4, name = "Rugged Leather" },
        },
    },
    [12777] = { name = "Blazing Rapier", skill = 280, spec = nil,
        components = {
            { id = 12655,  qty = 10, name = "Enchanted Thorium Bar" },
            { id = 7078,   qty =  4, name = "Essence of Fire" },
            { id = 7077,   qty =  4, name = "Heart of Fire" },
            { id = 12800,  qty =  2, name = "Azerothian Diamond" },
            { id = 12644,  qty =  2, name = "Dense Grinding Stone" },
        },
    },
    [11604] = { name = "Dark Iron Plate", skill = 285, spec = nil,
        components = {
            { id = 11371,  qty = 20, name = "Dark Iron Bar" },
            { id = 7077,   qty =  8, name = "Heart of Fire" },
        },
    },
    [12418] = { name = "Radiant Gloves", skill = 285, spec = "Arms",
        components = {
            { id = 12359,  qty = 18, name = "Thorium Bar" },
            { id = 7077,   qty =  4, name = "Heart of Fire" },
        },
    },
    [12628] = { name = "Demon Forged Breastplate", skill = 285, spec = nil,
        components = {
            { id = 12359,  qty = 40, name = "Thorium Bar" },
            { id = 12662,  qty = 10, name = "Demonic Rune" },
            { id = 12361,  qty =  4, name = "Blue Sapphire" },
            { id = 7910,   qty =  4, name = "Star Ruby" },
        },
    },
    [12781] = { name = "Serenity", skill = 285, spec = nil,
        components = {
            { id = 12655,  qty =  6, name = "Enchanted Thorium Bar" },
            { id = 12360,  qty =  2, name = "Arcanite Bar" },
            { id = 12804,  qty =  4, name = "Powerful Mojo" },
            { id = 12799,  qty =  2, name = "Large Opal" },
            { id = 12361,  qty =  2, name = "Blue Sapphire" },
            { id = 12364,  qty =  1, name = "Huge Emerald" },
        },
    },
    [12419] = { name = "Radiant Boots", skill = 290, spec = "Arms",
        components = {
            { id = 12359,  qty = 14, name = "Thorium Bar" },
            { id = 7077,   qty =  4, name = "Heart of Fire" },
        },
    },
    [12625] = { name = "Dawnbringer Shoulders", skill = 290, spec = nil,
        components = {
            { id = 12359,  qty = 20, name = "Thorium Bar" },
            { id = 12360,  qty =  4, name = "Arcanite Bar" },
            { id = 12364,  qty =  2, name = "Huge Emerald" },
            { id = 7080,   qty =  2, name = "Essence of Water" },
        },
    },
    [12631] = { name = "Fiery Plate Gauntlets", skill = 290, spec = nil,
        components = {
            { id = 12359,  qty = 20, name = "Thorium Bar" },
            { id = 12655,  qty =  6, name = "Enchanted Thorium Bar" },
            { id = 7078,   qty =  2, name = "Essence of Fire" },
            { id = 7910,   qty =  4, name = "Star Ruby" },
        },
    },
    [12782] = { name = "Corruption", skill = 290, spec = nil,
        components = {
            { id = 12359,  qty = 40, name = "Thorium Bar" },
            { id = 12360,  qty =  2, name = "Arcanite Bar" },
            { id = 12662,  qty = 16, name = "Demonic Rune" },
            { id = 12808,  qty =  8, name = "Essence of Undeath" },
            { id = 12361,  qty =  2, name = "Blue Sapphire" },
            { id = 12644,  qty =  2, name = "Dense Grinding Stone" },
            { id = 8170,   qty =  4, name = "Rugged Leather" },
        },
    },
    [12792] = { name = "Volcanic Hammer", skill = 290, spec = nil,
        components = {
            { id = 12359,  qty = 30, name = "Thorium Bar" },
            { id = 7077,   qty =  4, name = "Heart of Fire" },
            { id = 7910,   qty =  4, name = "Star Ruby" },
            { id = 8170,   qty =  4, name = "Rugged Leather" },
        },
    },
    [19043] = { name = "Heavy Timbermaw Belt", skill = 290, spec = nil,
        components = {
            { id = 12359,  qty = 12, name = "Thorium Bar" },
            { id = 7076,   qty =  3, name = "Essence of Earth" },
            { id = 12803,  qty =  3, name = "Living Essence" },
        },
    },
    [19051] = { name = "Girdle of the Dawn", skill = 290, spec = nil,
        components = {
            { id = 12359,  qty =  8, name = "Thorium Bar" },
            { id = 6037,   qty =  6, name = "Truesilver Bar" },
            { id = 12811,  qty =  1, name = "Righteous Orb" },
        },
    },
    [12417] = { name = "Radiant Circlet", skill = 295, spec = nil,
        components = {
            { id = 12359,  qty = 18, name = "Thorium Bar" },
            { id = 7077,   qty =  4, name = "Heart of Fire" },
        },
    },
    [12426] = { name = "Imperial Plate Boots", skill = 295, spec = nil,
        components = {
            { id = 12359,  qty = 18, name = "Thorium Bar" },
        },
    },
    [12427] = { name = "Imperial Plate Helm", skill = 295, spec = "Arms",
        components = {
            { id = 12359,  qty = 18, name = "Thorium Bar" },
            { id = 7910,   qty =  1, name = "Star Ruby" },
        },
    },
    [12632] = { name = "Storm Gauntlets", skill = 295, spec = nil,
        components = {
            { id = 12359,  qty = 20, name = "Thorium Bar" },
            { id = 12655,  qty =  4, name = "Enchanted Thorium Bar" },
            { id = 7080,   qty =  4, name = "Essence of Water" },
            { id = 12361,  qty =  4, name = "Blue Sapphire" },
        },
    },
    [16989] = { name = "Fiery Chain Girdle", skill = 295, spec = "Ham",
        components = {
            { id = 11371,  qty =  6, name = "Dark Iron Bar" },
            { id = 17010,  qty =  3, name = "Fiery Core" },
            { id = 17011,  qty =  3, name = "Lava Core" },
        },
    },
    [17014] = { name = "Dark Iron Bracers", skill = 295, spec = nil,
        components = {
            { id = 11371,  qty =  4, name = "Dark Iron Bar" },
            { id = 17010,  qty =  2, name = "Fiery Core" },
            { id = 17011,  qty =  2, name = "Lava Core" },
        },
    },
    [12414] = { name = "Thorium Leggings", skill = 300, spec = nil,
        components = {
            { id = 12359,  qty = 12, name = "Thorium Bar" },
        },
    },
    [12420] = { name = "Radiant Leggings", skill = 300, spec = "Arms",
        components = {
            { id = 12359,  qty = 20, name = "Thorium Bar" },
            { id = 7077,   qty =  4, name = "Heart of Fire" },
        },
    },
    [12422] = { name = "Imperial Plate Chest", skill = 300, spec = "Arms",
        components = {
            { id = 12359,  qty = 20, name = "Thorium Bar" },
        },
    },
    [12429] = { name = "Imperial Plate Leggings", skill = 300, spec = nil,
        components = {
            { id = 12359,  qty = 24, name = "Thorium Bar" },
        },
    },
    [12610] = { name = "Runic Plate Shoulders", skill = 300, spec = nil,
        components = {
            { id = 12359,  qty = 20, name = "Thorium Bar" },
            { id = 12360,  qty =  2, name = "Arcanite Bar" },
            { id = 3577,   qty =  6, name = "Gold Bar" },
        },
    },
    [12611] = { name = "Runic Plate Boots", skill = 300, spec = nil,
        components = {
            { id = 12359,  qty = 20, name = "Thorium Bar" },
            { id = 12360,  qty =  2, name = "Arcanite Bar" },
            { id = 2842,   qty = 10, name = "Silver Bar" },
        },
    },
    [12612] = { name = "Runic Plate Helm", skill = 300, spec = nil,
        components = {
            { id = 12359,  qty = 30, name = "Thorium Bar" },
            { id = 12360,  qty =  2, name = "Arcanite Bar" },
            { id = 6037,   qty =  2, name = "Truesilver Bar" },
            { id = 12364,  qty =  1, name = "Huge Emerald" },
        },
    },
    [12613] = { name = "Runic Breastplate", skill = 300, spec = nil,
        components = {
            { id = 12359,  qty = 40, name = "Thorium Bar" },
            { id = 12360,  qty =  2, name = "Arcanite Bar" },
            { id = 7910,   qty =  1, name = "Star Ruby" },
        },
    },
    [12614] = { name = "Runic Plate Leggings", skill = 300, spec = nil,
        components = {
            { id = 12359,  qty = 40, name = "Thorium Bar" },
            { id = 12360,  qty =  2, name = "Arcanite Bar" },
            { id = 7910,   qty =  1, name = "Star Ruby" },
        },
    },
    [12618] = { name = "Enchanted Thorium Breastplate", skill = 300, spec = nil,
        components = {
            { id = 12360,  qty =  8, name = "Arcanite Bar" },
            { id = 12655,  qty = 24, name = "Enchanted Thorium Bar" },
            { id = 7076,   qty =  4, name = "Essence of Earth" },
            { id = 7080,   qty =  4, name = "Essence of Water" },
            { id = 12364,  qty =  2, name = "Huge Emerald" },
            { id = 12800,  qty =  2, name = "Azerothian Diamond" },
        },
    },
    [12619] = { name = "Enchanted Thorium Leggings", skill = 300, spec = nil,
        components = {
            { id = 12360,  qty = 10, name = "Arcanite Bar" },
            { id = 12655,  qty = 20, name = "Enchanted Thorium Bar" },
            { id = 7080,   qty =  6, name = "Essence of Water" },
            { id = 12361,  qty =  2, name = "Blue Sapphire" },
            { id = 12364,  qty =  1, name = "Huge Emerald" },
        },
    },
    [12620] = { name = "Enchanted Thorium Helm", skill = 300, spec = nil,
        components = {
            { id = 12360,  qty =  6, name = "Arcanite Bar" },
            { id = 12655,  qty = 16, name = "Enchanted Thorium Bar" },
            { id = 7076,   qty =  6, name = "Essence of Earth" },
            { id = 12799,  qty =  2, name = "Large Opal" },
            { id = 12800,  qty =  1, name = "Azerothian Diamond" },
        },
    },
    [12633] = { name = "Whitesoul Helm", skill = 300, spec = nil,
        components = {
            { id = 12359,  qty = 20, name = "Thorium Bar" },
            { id = 12655,  qty =  4, name = "Enchanted Thorium Bar" },
            { id = 6037,   qty =  6, name = "Truesilver Bar" },
            { id = 3577,   qty =  6, name = "Gold Bar" },
            { id = 12800,  qty =  2, name = "Azerothian Diamond" },
        },
    },
    [12636] = { name = "Helm of the Great Chief", skill = 300, spec = nil,
        components = {
            { id = 12359,  qty = 40, name = "Thorium Bar" },
            { id = 12655,  qty =  4, name = "Enchanted Thorium Bar" },
            { id = 12799,  qty =  6, name = "Large Opal" },
            { id = 12364,  qty =  2, name = "Huge Emerald" },
        },
    },
    [12639] = { name = "Stronghold Gauntlets", skill = 300, spec = nil,
        components = {
            { id = 12360,  qty = 15, name = "Arcanite Bar" },
            { id = 12655,  qty = 20, name = "Enchanted Thorium Bar" },
            { id = 7076,   qty = 10, name = "Essence of Earth" },
            { id = 12361,  qty =  4, name = "Blue Sapphire" },
            { id = 12799,  qty =  4, name = "Large Opal" },
        },
    },
    [12640] = { name = "Lionheart Helm", skill = 300, spec = nil,
        components = {
            { id = 12359,  qty = 80, name = "Thorium Bar" },
            { id = 12360,  qty = 12, name = "Arcanite Bar" },
            { id = 12361,  qty = 10, name = "Blue Sapphire" },
            { id = 12800,  qty =  4, name = "Azerothian Diamond" },
        },
    },
    [12641] = { name = "Invulnerable Mail", skill = 300, spec = nil,
        components = {
            { id = 12360,  qty = 30, name = "Arcanite Bar" },
            { id = 12655,  qty = 30, name = "Enchanted Thorium Bar" },
            { id = 12364,  qty =  6, name = "Huge Emerald" },
            { id = 12800,  qty =  6, name = "Azerothian Diamond" },
        },
    },
    [12783] = { name = "Heartseeker", skill = 300, spec = nil,
        components = {
            { id = 12360,  qty = 10, name = "Arcanite Bar" },
            { id = 12655,  qty = 10, name = "Enchanted Thorium Bar" },
            { id = 12810,  qty =  2, name = "Enchanted Leather" },
            { id = 7910,   qty =  6, name = "Star Ruby" },
            { id = 12800,  qty =  6, name = "Azerothian Diamond" },
            { id = 12799,  qty =  6, name = "Large Opal" },
            { id = 12644,  qty =  4, name = "Dense Grinding Stone" },
        },
    },
    [12784] = { name = "Arcanite Reaper", skill = 300, spec = nil,
        components = {
            { id = 12360,  qty = 20, name = "Arcanite Bar" },
            { id = 12810,  qty =  6, name = "Enchanted Leather" },
            { id = 12644,  qty =  2, name = "Dense Grinding Stone" },
        },
    },
    [12790] = { name = "Arcanite Champion", skill = 300, spec = nil,
        components = {
            { id = 12360,  qty = 15, name = "Arcanite Bar" },
            { id = 12800,  qty =  8, name = "Azerothian Diamond" },
            { id = 12811,  qty =  1, name = "Righteous Orb" },
            { id = 12799,  qty =  4, name = "Large Opal" },
            { id = 12810,  qty =  8, name = "Enchanted Leather" },
            { id = 12644,  qty =  2, name = "Dense Grinding Stone" },
        },
    },
    [12794] = { name = "Masterwork Stormhammer", skill = 300, spec = nil,
        components = {
            { id = 12655,  qty = 20, name = "Enchanted Thorium Bar" },
            { id = 12364,  qty =  8, name = "Huge Emerald" },
            { id = 12799,  qty =  8, name = "Large Opal" },
            { id = 7076,   qty =  6, name = "Essence of Earth" },
            { id = 12810,  qty =  4, name = "Enchanted Leather" },
        },
    },
    [12796] = { name = "Hammer of the Titans", skill = 300, spec = nil,
        components = {
            { id = 12359,  qty = 50, name = "Thorium Bar" },
            { id = 12360,  qty = 15, name = "Arcanite Bar" },
            { id = 12809,  qty =  4, name = "Guardian Stone" },
            { id = 12810,  qty =  6, name = "Enchanted Leather" },
            { id = 7076,   qty = 10, name = "Essence of Earth" },
        },
    },
    [12797] = { name = "Frostguard", skill = 300, spec = nil,
        components = {
            { id = 12360,  qty = 18, name = "Arcanite Bar" },
            { id = 12361,  qty =  8, name = "Blue Sapphire" },
            { id = 12800,  qty =  8, name = "Azerothian Diamond" },
            { id = 7080,   qty =  4, name = "Essence of Water" },
            { id = 12644,  qty =  2, name = "Dense Grinding Stone" },
            { id = 12810,  qty =  4, name = "Enchanted Leather" },
        },
    },
    [12798] = { name = "Annihilator", skill = 300, spec = nil,
        components = {
            { id = 12359,  qty = 40, name = "Thorium Bar" },
            { id = 12360,  qty = 12, name = "Arcanite Bar" },
            { id = 12808,  qty = 10, name = "Essence of Undeath" },
            { id = 12364,  qty =  8, name = "Huge Emerald" },
            { id = 12644,  qty =  2, name = "Dense Grinding Stone" },
            { id = 12810,  qty =  4, name = "Enchanted Leather" },
        },
    },
    [16988] = { name = "Fiery Chain Shoulders", skill = 300, spec = nil,
        components = {
            { id = 11371,  qty = 16, name = "Dark Iron Bar" },
            { id = 17010,  qty =  4, name = "Fiery Core" },
            { id = 17011,  qty =  5, name = "Lava Core" },
        },
    },
    [17013] = { name = "Dark Iron Leggings", skill = 300, spec = nil,
        components = {
            { id = 11371,  qty = 16, name = "Dark Iron Bar" },
            { id = 17010,  qty =  4, name = "Fiery Core" },
            { id = 17011,  qty =  6, name = "Lava Core" },
        },
    },
    [17015] = { name = "Dark Iron Reaver", skill = 300, spec = nil,
        components = {
            { id = 11371,  qty = 16, name = "Dark Iron Bar" },
            { id = 17010,  qty = 12, name = "Fiery Core" },
            { id = 11382,  qty =  2, name = "Blood of the Mountain" },
            { id = 12810,  qty =  2, name = "Enchanted Leather" },
        },
    },
    [17016] = { name = "Dark Iron Destroyer", skill = 300, spec = nil,
        components = {
            { id = 11371,  qty = 18, name = "Dark Iron Bar" },
            { id = 17011,  qty = 12, name = "Lava Core" },
            { id = 11382,  qty =  2, name = "Blood of the Mountain" },
            { id = 12810,  qty =  2, name = "Enchanted Leather" },
        },
    },
    [17193] = { name = "Sulfuron Hammer", skill = 300, spec = nil,
        components = {
            { id = 17203,  qty =  8, name = "Sulfuron Ingot" },
            { id = 11371,  qty = 20, name = "Dark Iron Bar" },
            { id = 12360,  qty = 50, name = "Arcanite Bar" },
            { id = 7078,   qty = 25, name = "Essence of Fire" },
            { id = 11382,  qty = 10, name = "Blood of the Mountain" },
            { id = 17011,  qty = 10, name = "Lava Core" },
            { id = 17010,  qty = 10, name = "Fiery Core" },
        },
    },
    [18262] = { name = "Elemental Sharpening Stone", skill = 300, spec = nil,
        components = {
            { id = 7067,   qty =  2, name = "Elemental Earth" },
            { id = 12365,  qty =  3, name = "Dense Stone" },
        },
    },
    [19048] = { name = "Heavy Timbermaw Boots", skill = 300, spec = nil,
        components = {
            { id = 12360,  qty =  4, name = "Arcanite Bar" },
            { id = 7076,   qty =  6, name = "Essence of Earth" },
            { id = 12803,  qty =  6, name = "Living Essence" },
        },
    },
    [19057] = { name = "Gloves of the Dawn", skill = 300, spec = nil,
        components = {
            { id = 12360,  qty =  2, name = "Arcanite Bar" },
            { id = 6037,   qty = 10, name = "Truesilver Bar" },
            { id = 12811,  qty =  1, name = "Righteous Orb" },
        },
    },
    [19148] = { name = "Dark Iron Helm", skill = 300, spec = nil,
        components = {
            { id = 17011,  qty =  4, name = "Lava Core" },
            { id = 17010,  qty =  2, name = "Fiery Core" },
            { id = 11371,  qty =  4, name = "Dark Iron Bar" },
        },
    },
    [19164] = { name = "Dark Iron Gauntlets", skill = 300, spec = nil,
        components = {
            { id = 17011,  qty =  3, name = "Lava Core" },
            { id = 17010,  qty =  5, name = "Fiery Core" },
            { id = 17012,  qty =  4, name = "Core Leather" },
            { id = 11371,  qty =  4, name = "Dark Iron Bar" },
            { id = 11382,  qty =  2, name = "Blood of the Mountain" },
        },
    },
    [19166] = { name = "Black Amnesty", skill = 300, spec = nil,
        components = {
            { id = 17011,  qty =  3, name = "Lava Core" },
            { id = 17010,  qty =  6, name = "Fiery Core" },
            { id = 12360,  qty = 12, name = "Arcanite Bar" },
            { id = 11382,  qty =  1, name = "Blood of the Mountain" },
            { id = 11371,  qty =  4, name = "Dark Iron Bar" },
        },
    },
    [19167] = { name = "Blackfury", skill = 300, spec = nil,
        components = {
            { id = 17011,  qty =  5, name = "Lava Core" },
            { id = 17010,  qty =  2, name = "Fiery Core" },
            { id = 12360,  qty = 16, name = "Arcanite Bar" },
            { id = 11371,  qty =  6, name = "Dark Iron Bar" },
        },
    },
    [19168] = { name = "Blackguard", skill = 300, spec = nil,
        components = {
            { id = 17011,  qty =  6, name = "Lava Core" },
            { id = 17010,  qty =  6, name = "Fiery Core" },
            { id = 12360,  qty = 10, name = "Arcanite Bar" },
            { id = 11371,  qty =  6, name = "Dark Iron Bar" },
            { id = 12809,  qty = 12, name = "Guardian Stone" },
        },
    },
    [19169] = { name = "Nightfall", skill = 300, spec = nil,
        components = {
            { id = 17011,  qty =  8, name = "Lava Core" },
            { id = 17010,  qty =  5, name = "Fiery Core" },
            { id = 12360,  qty = 10, name = "Arcanite Bar" },
            { id = 11371,  qty = 12, name = "Dark Iron Bar" },
            { id = 12364,  qty =  4, name = "Huge Emerald" },
        },
    },
    [19170] = { name = "Ebon Hand", skill = 300, spec = nil,
        components = {
            { id = 17011,  qty =  4, name = "Lava Core" },
            { id = 17010,  qty =  7, name = "Fiery Core" },
            { id = 12360,  qty = 12, name = "Arcanite Bar" },
            { id = 11371,  qty =  8, name = "Dark Iron Bar" },
            { id = 12800,  qty =  4, name = "Azerothian Diamond" },
        },
    },
    [19690] = { name = "Bloodsoul Breastplate", skill = 300, spec = nil,
        components = {
            { id = 12359,  qty = 20, name = "Thorium Bar" },
            { id = 19774,  qty = 10, name = "Souldarite" },
            { id = 7910,   qty =  2, name = "Star Ruby" },
        },
    },
    [19691] = { name = "Bloodsoul Shoulders", skill = 300, spec = nil,
        components = {
            { id = 12359,  qty = 16, name = "Thorium Bar" },
            { id = 19774,  qty =  8, name = "Souldarite" },
            { id = 7910,   qty =  1, name = "Star Ruby" },
        },
    },
    [19692] = { name = "Bloodsoul Gauntlets", skill = 300, spec = nil,
        components = {
            { id = 12359,  qty = 12, name = "Thorium Bar" },
            { id = 19774,  qty =  6, name = "Souldarite" },
            { id = 12810,  qty =  4, name = "Enchanted Leather" },
        },
    },
    [19693] = { name = "Darksoul Breastplate", skill = 300, spec = nil,
        components = {
            { id = 12359,  qty = 20, name = "Thorium Bar" },
            { id = 19774,  qty = 14, name = "Souldarite" },
            { id = 12799,  qty =  2, name = "Large Opal" },
        },
    },
    [19694] = { name = "Darksoul Leggings", skill = 300, spec = nil,
        components = {
            { id = 12359,  qty = 18, name = "Thorium Bar" },
            { id = 19774,  qty = 12, name = "Souldarite" },
            { id = 12799,  qty =  2, name = "Large Opal" },
        },
    },
    [19695] = { name = "Darksoul Shoulders", skill = 300, spec = nil,
        components = {
            { id = 12359,  qty = 16, name = "Thorium Bar" },
            { id = 19774,  qty = 10, name = "Souldarite" },
            { id = 12799,  qty =  1, name = "Large Opal" },
        },
    },
    [20039] = { name = "Dark Iron Boots", skill = 300, spec = nil,
        components = {
            { id = 17011,  qty =  3, name = "Lava Core" },
            { id = 17010,  qty =  3, name = "Fiery Core" },
            { id = 17012,  qty =  4, name = "Core Leather" },
            { id = 11371,  qty =  6, name = "Dark Iron Bar" },
        },
    },
    [20549] = { name = "Darkrune Gauntlets", skill = 300, spec = nil,
        components = {
            { id = 12359,  qty = 12, name = "Thorium Bar" },
            { id = 20520,  qty =  6, name = "Dark Rune" },
            { id = 6037,   qty =  6, name = "Truesilver Bar" },
            { id = 12810,  qty =  2, name = "Enchanted Leather" },
        },
    },
    [20550] = { name = "Darkrune Breastplate", skill = 300, spec = nil,
        components = {
            { id = 12359,  qty = 20, name = "Thorium Bar" },
            { id = 20520,  qty = 10, name = "Dark Rune" },
            { id = 6037,   qty = 10, name = "Truesilver Bar" },
        },
    },
    [20551] = { name = "Darkrune Helm", skill = 300, spec = nil,
        components = {
            { id = 12359,  qty = 16, name = "Thorium Bar" },
            { id = 20520,  qty =  8, name = "Dark Rune" },
            { id = 6037,   qty =  8, name = "Truesilver Bar" },
            { id = 11754,  qty =  1, name = "Black Diamond" },
        },
    },
    [22191] = { name = "Obsidian Mail Tunic", skill = 300, spec = nil,
        components = {
            { id = 22203,  qty = 15, name = "Large Obsidian Shard" },
            { id = 22202,  qty = 36, name = "Small Obsidian Shard" },
            { id = 12810,  qty = 12, name = "Enchanted Leather" },
            { id = 12809,  qty = 10, name = "Guardian Stone" },
            { id = 12800,  qty =  4, name = "Azerothian Diamond" },
        },
    },
    [22194] = { name = "Black Grasp of the Destroyer", skill = 300, spec = nil,
        components = {
            { id = 22203,  qty =  8, name = "Large Obsidian Shard" },
            { id = 22202,  qty = 24, name = "Small Obsidian Shard" },
            { id = 12810,  qty =  8, name = "Enchanted Leather" },
            { id = 13512,  qty =  1, name = "Flask of Supreme Power" },
        },
    },
    [22195] = { name = "Light Obsidian Belt", skill = 300, spec = nil,
        components = {
            { id = 22202,  qty = 14, name = "Small Obsidian Shard" },
            { id = 12810,  qty =  4, name = "Enchanted Leather" },
        },
    },
    [22196] = { name = "Thick Obsidian Breastplate", skill = 300, spec = nil,
        components = {
            { id = 22203,  qty = 18, name = "Large Obsidian Shard" },
            { id = 22202,  qty = 40, name = "Small Obsidian Shard" },
            { id = 12655,  qty = 12, name = "Enchanted Thorium Bar" },
            { id = 7076,   qty = 10, name = "Essence of Earth" },
            { id = 12364,  qty =  4, name = "Huge Emerald" },
        },
    },
    [22197] = { name = "Heavy Obsidian Belt", skill = 300, spec = nil,
        components = {
            { id = 22202,  qty = 14, name = "Small Obsidian Shard" },
            { id = 12655,  qty =  4, name = "Enchanted Thorium Bar" },
            { id = 7076,   qty =  2, name = "Essence of Earth" },
        },
    },
    [22198] = { name = "Jagged Obsidian Shield", skill = 300, spec = nil,
        components = {
            { id = 22203,  qty =  8, name = "Large Obsidian Shard" },
            { id = 22202,  qty = 24, name = "Small Obsidian Shard" },
            { id = 12655,  qty =  8, name = "Enchanted Thorium Bar" },
            { id = 7076,   qty =  4, name = "Essence of Earth" },
        },
    },
    [22383] = { name = "Sageblade", skill = 300, spec = nil,
        components = {
            { id = 12360,  qty = 12, name = "Arcanite Bar" },
            { id = 20725,  qty =  2, name = "Nexus Crystal" },
            { id = 13512,  qty =  2, name = "Flask of Supreme Power" },
            { id = 12810,  qty =  4, name = "Enchanted Leather" },
        },
    },
    [22384] = { name = "Persuader", skill = 300, spec = nil,
        components = {
            { id = 12360,  qty = 15, name = "Arcanite Bar" },
            { id = 11371,  qty = 10, name = "Dark Iron Bar" },
            { id = 12808,  qty = 20, name = "Essence of Undeath" },
            { id = 20520,  qty = 20, name = "Dark Rune" },
            { id = 15417,  qty = 10, name = "Devilsaur Leather" },
            { id = 12753,  qty =  2, name = "Skin of Shadow" },
        },
    },
    [22385] = { name = "Titanic Leggings", skill = 300, spec = nil,
        components = {
            { id = 12360,  qty = 12, name = "Arcanite Bar" },
            { id = 12655,  qty = 20, name = "Enchanted Thorium Bar" },
            { id = 7076,   qty = 10, name = "Essence of Earth" },
            { id = 13510,  qty =  2, name = "Flask of the Titans" },
        },
    },
    [22669] = { name = "Icebane Breastplate", skill = 300, spec = "Tribal",
        components = {
            { id = 22682,  qty =  7, name = "Frozen Rune" },
            { id = 12359,  qty = 16, name = "Thorium Bar" },
            { id = 12360,  qty =  2, name = "Arcanite Bar" },
            { id = 7080,   qty =  4, name = "Essence of Water" },
        },
    },
    [22670] = { name = "Icebane Gauntlets", skill = 300, spec = nil,
        components = {
            { id = 22682,  qty =  5, name = "Frozen Rune" },
            { id = 12359,  qty = 12, name = "Thorium Bar" },
            { id = 12360,  qty =  2, name = "Arcanite Bar" },
            { id = 7080,   qty =  2, name = "Essence of Water" },
        },
    },
    [22671] = { name = "Icebane Bracers", skill = 300, spec = nil,
        components = {
            { id = 22682,  qty =  4, name = "Frozen Rune" },
            { id = 12359,  qty = 12, name = "Thorium Bar" },
            { id = 12360,  qty =  2, name = "Arcanite Bar" },
            { id = 7080,   qty =  2, name = "Essence of Water" },
        },
    },
    [22762] = { name = "Ironvine Breastplate", skill = 300, spec = nil,
        components = {
            { id = 12655,  qty =  6, name = "Enchanted Thorium Bar" },
            { id = 19726,  qty =  2, name = "Bloodvine" },
            { id = 12360,  qty =  2, name = "Arcanite Bar" },
            { id = 12803,  qty =  2, name = "Living Essence" },
        },
    },
    [22763] = { name = "Ironvine Gloves", skill = 300, spec = nil,
        components = {
            { id = 12655,  qty =  8, name = "Enchanted Thorium Bar" },
            { id = 19726,  qty =  1, name = "Bloodvine" },
            { id = 12803,  qty =  2, name = "Living Essence" },
        },
    },
    [22764] = { name = "Ironvine Belt", skill = 300, spec = nil,
        components = {
            { id = 12655,  qty =  6, name = "Enchanted Thorium Bar" },
            { id = 12803,  qty =  2, name = "Living Essence" },
        },
    },
}