-- Enchanting reagents - Source: wowhead.com/classic + warcraft.wiki.gg
-- WoW Classic Era 1.12.1 (Interface 11508)
-- Format: reagent item ID → { skill, uses = { list of enchants } }

ProfTooltip_Enchanting = {

    -- ══════════════════════════════════════════════════════
    --  APPRENTICE reagents (skill 1–100)
    -- ══════════════════════════════════════════════════════

    [10938] = { skill = 1, name = "Lesser Magic Essence",
        uses = {
            "Enchant Bracer - Minor Strength",
            "Enchant Chest - Minor Absorption",
            "Enchant Chest - Minor Stats",
            "Enchant Cloak - Minor Protection",
            "Enchant Weapon - Minor Beastslaying",
            "Enchant Weapon - Minor Striking",
            "Enchant Shield - Minor Stamina",
        },
    },
    [10939] = { skill = 1, name = "Greater Magic Essence",
        uses = {
            "Enchant Boots - Minor Stamina",
            "Enchant Boots - Minor Agility",
            "Enchant Bracer - Minor Agility",
            "Enchant Chest - Health",
            "Enchant Gloves - Mining",
            "Enchant Gloves - Herbalism",
            "Enchant Gloves - Fishing",
            "Enchant Shield - Stamina",
            "Enchant Weapon - Fiery Weapon",
        },
    },
    [10940] = { skill = 1, name = "Strange Dust",
        uses = {
            "Enchant Bracer - Minor Strength",
            "Enchant Bracer - Minor Agility",
            "Enchant Chest - Minor Absorption",
            "Enchant Chest - Minor Stats",
            "Enchant Chest - Health",
            "Enchant Cloak - Minor Protection",
            "Enchant Gloves - Minor Agility",
            "Enchant Shield - Minor Stamina",
            "Enchant Shield - Stamina",
            "Enchant Weapon - Minor Beastslaying",
            "Enchant Weapon - Minor Striking",
            "Enchant Weapon - Lesser Striking",
            "Enchant 2H Weapon - Lesser Intellect",
        },
    },
    [10978] = { skill = 1, name = "Small Glimmering Shard",
        uses = {
            "Enchant Bracer - Lesser Stamina",
            "Enchant Chest - Lesser Absorption",
            "Enchant Cloak - Lesser Protection",
            "Enchant Weapon - Lesser Beastslaying",
            "Enchant Weapon - Lesser Striking",
        },
    },
    [11085] = { skill = 1, name = "Large Glimmering Shard",
        uses = {
            "Enchant Bracer - Stamina",
            "Enchant Boots - Lesser Stamina",
            "Enchant Cloak - Lesser Agility",
            "Enchant Weapon - Striking",
            "Enchant 2H Weapon - Lesser Spirit",
        },
    },

    -- ══════════════════════════════════════════════════════
    --  JOURNEYMAN reagents (skill 100–150)
    -- ══════════════════════════════════════════════════════

    [11082] = { skill = 100, name = "Lesser Astral Essence",
        uses = {
            "Enchant Boots - Lesser Stamina",
            "Enchant Boots - Lesser Agility",
            "Enchant Bracer - Stamina",
            "Enchant Chest - Lesser Stats",
            "Enchant Gloves - Agility",
            "Enchant Shield - Lesser Stamina",
            "Enchant Weapon - Striking",
        },
    },
    [11084] = { skill = 100, name = "Greater Astral Essence",
        uses = {
            "Enchant Boots - Agility",
            "Enchant Bracer - Lesser Deflection",
            "Enchant Bracer - Lesser Intellect",
            "Enchant Chest - Lesser Stats",
            "Enchant Gloves - Skinning",
            "Enchant Weapon - Spirit",
            "Enchant 2H Weapon - Lesser Intellect",
            "Enchant 2H Weapon - Intellect",
        },
    },
    [11083] = { skill = 100, name = "Soul Dust",
        uses = {
            "Enchant Boots - Agility",
            "Enchant Boots - Lesser Stamina",
            "Enchant Bracer - Stamina",
            "Enchant Bracer - Lesser Deflection",
            "Enchant Chest - Lesser Stats",
            "Enchant Gloves - Agility",
            "Enchant Shield - Lesser Stamina",
            "Enchant Shield - Blocking",
            "Enchant Weapon - Lesser Striking",
            "Enchant Weapon - Striking",
            "Enchant Weapon - Spirit",
            "Enchant 2H Weapon - Lesser Spirit",
        },
    },
    [11138] = { skill = 100, name = "Small Glowing Shard",
        uses = {
            "Enchant Bracer - Defense",
            "Enchant Chest - Minor Mana",
            "Enchant Weapon - Lesser Beastslaying",
            "Enchant Weapon - Strength",
            "Enchant 2H Weapon - Lesser Spirit",
        },
    },
    [11139] = { skill = 150, name = "Large Glowing Shard",
        uses = {
            "Enchant Bracer - Greater Stamina",
            "Enchant Gloves - Strength",
            "Enchant Weapon - Strength",
            "Enchant 2H Weapon - Spirit",
            "Enchant Shield - Greater Stamina",
        },
    },

    -- ══════════════════════════════════════════════════════
    --  EXPERT reagents (skill 150–200)
    -- ══════════════════════════════════════════════════════

    [11134] = { skill = 150, name = "Lesser Mystic Essence",
        uses = {
            "Enchant Bracer - Greater Stamina",
            "Enchant Bracer - Deflection",
            "Enchant Chest - Lesser Mana",
            "Enchant Gloves - Strength",
            "Enchant Gloves - Agility",
            "Enchant Shield - Greater Stamina",
            "Enchant Weapon - Lesser Beastslaying",
            "Enchant Weapon - Agility",
            "Enchant 2H Weapon - Spirit",
        },
    },
    [11135] = { skill = 150, name = "Greater Mystic Essence",
        uses = {
            "Enchant Bracer - Intellect",
            "Enchant Bracer - Deflection",
            "Enchant Chest - Mana",
            "Enchant Gloves - Advanced Mining",
            "Enchant Gloves - Advanced Herbalism",
            "Enchant Ring - Healing",
            "Enchant Ring - Mana",
            "Enchant Shield - Reflection",
            "Enchant Weapon - Fiery Weapon",
            "Enchant Weapon - Demonslaying",
            "Enchant 2H Weapon - Agility",
        },
    },
    [11137] = { skill = 150, name = "Vision Dust",
        uses = {
            "Enchant Bracer - Intellect",
            "Enchant Bracer - Greater Deflection",
            "Enchant Chest - Major Mana",
            "Enchant Chest - Major Stats",
            "Enchant Cloak - Greater Defense",
            "Enchant Cloak - Greater Agility",
            "Enchant Gloves - Advanced Mining",
            "Enchant Gloves - Advanced Herbalism",
            "Enchant Shield - Reflection",
            "Enchant Weapon - Fiery Weapon",
            "Enchant Weapon - Demonslaying",
            "Enchant Weapon - Unholy Weapon",
            "Enchant 2H Weapon - Agility",
            "Enchant Ring - Healing",
        },
    },
    [11177] = { skill = 150, name = "Small Radiant Shard",
        uses = {
            "Enchant Bracer - Greater Deflection",
            "Enchant Chest - Major Mana",
            "Enchant Weapon - Fiery Weapon",
            "Enchant Weapon - Demonslaying",
            "Enchant Weapon - Unholy Weapon",
            "Enchant 2H Weapon - Agility",
            "Enchant Shield - Frost Resistance",
            "Enchant Shield - Nature Resistance",
        },
    },
    [11178] = { skill = 200, name = "Large Radiant Shard",
        uses = {
            "Enchant Cloak - Greater Agility",
            "Enchant Cloak - Greater Defense",
            "Enchant Cloak - Shadow Resistance",
            "Enchant Chest - Major Stats",
            "Enchant Bracer - Superior Strength",
            "Enchant Gloves - Superior Agility",
            "Enchant Shield - Greater Stamina",
            "Enchant 2H Weapon - Superior Impact",
        },
    },

    -- ══════════════════════════════════════════════════════
    --  ARTISAN reagents (skill 200–300)
    -- ══════════════════════════════════════════════════════

    [11176] = { skill = 200, name = "Dream Dust",
        uses = {
            "Enchant Bracer - Superior Strength",
            "Enchant Bracer - Greater Intellect",
            "Enchant Chest - Major Stats",
            "Enchant Chest - Greater Stats",
            "Enchant Cloak - Greater Defense",
            "Enchant Cloak - Shadow Resistance",
            "Enchant Gloves - Superior Agility",
            "Enchant Gloves - Greater Strength",
            "Enchant Shield - Greater Stamina",
            "Enchant Weapon - Icy Chill",
            "Enchant 2H Weapon - Agility",
            "Enchant 2H Weapon - Superior Impact",
            "Enchant Ring - Agility",
        },
    },
    [16202] = { skill = 200, name = "Lesser Eternal Essence",
        uses = {
            "Enchant Bracer - Greater Intellect",
            "Enchant Bracer - Healing Power",
            "Enchant Cloak - Superior Defense",
            "Enchant Gloves - Greater Strength",
            "Enchant Ring - Agility",
            "Enchant Ring - Strength",
            "Enchant Ring - Intellect",
            "Enchant Shield - Resistance",
            "Enchant Weapon - Icy Chill",
            "Enchant Weapon - Unholy Weapon",
            "Enchant 2H Weapon - Superior Striking",
            "Enchant 2H Weapon - Ferocity",
        },
    },
    [16203] = { skill = 200, name = "Greater Eternal Essence",
        uses = {
            "Enchant Bracer - Healing Power",
            "Enchant Bracer - Mana Regeneration",
            "Enchant Chest - Excellent Stats",
            "Enchant Cloak - Superior Defense",
            "Enchant Cloak - Stealth",
            "Enchant Gloves - Greater Agility",
            "Enchant Ring - Strength",
            "Enchant Ring - Intellect",
            "Enchant Shield - Resistance",
            "Enchant Weapon - Spellpower",
            "Enchant Weapon - Spell Power",
            "Enchant 2H Weapon - Ferocity",
            "Enchant 2H Weapon - Major Intellect",
            "Enchant 2H Weapon - Major Spirit",
        },
    },
    [14343] = { skill = 200, name = "Small Brilliant Shard",
        uses = {
            "Enchant Bracer - Mana Regeneration",
            "Enchant Chest - Excellent Stats",
            "Enchant Cloak - Stealth",
            "Enchant Cloak - Dodge",
            "Enchant Gloves - Greater Agility",
            "Enchant Ring - Strength",
            "Enchant Shield - Resistance",
            "Enchant Weapon - Icy Chill",
            "Enchant Weapon - Spell Power",
            "Enchant 2H Weapon - Major Spirit",
        },
    },
    [16204] = { skill = 265, name = "Illusion Dust",
        uses = {
            "Enchant Boots - Greater Stamina",
            "Enchant Boots - Spirit",
            "Enchant Boots - Greater Agility",
            "Enchant Boots - Vitality",
            "Enchant Bracer - Superior Stamina",
            "Enchant Chest - Greater Stats",
            "Enchant Gloves - Riding Skill",
            "Enchant Weapon - Crusader",
            "Enchant Weapon - Lifestealing",
            "Enchant Weapon - Agility",
            "Enchant 2H Weapon - Agility",
        },
    },
    [14344] = { skill = 265, name = "Large Brilliant Shard",
        uses = {
            "Enchant Boots - Greater Stamina",
            "Enchant Boots - Greater Agility",
            "Enchant Bracer - Superior Stamina",
            "Enchant Chest - Greater Stats",
            "Enchant Chest - Major Health",
            "Enchant Gloves - Greater Strength",
            "Enchant Gloves - Greater Agility",
            "Enchant Ring - Strength",
            "Enchant Shield - Superior Stamina",
            "Enchant Weapon - Crusader",
            "Enchant Weapon - Lifestealing",
            "Enchant Weapon - Spellpower",
            "Enchant 2H Weapon - Major Intellect",
            "Enchant 2H Weapon - Major Spirit",
            "Enchant Weapon - Strength",
        },
    },

}
